OHIF/Viewers

Packages/ohif-cornerstone/package.js

- Updating latest versions of cornerstone node modules inside ohif-cornerstone package.

Bump version in OHIF-cornerstone package  of cornerstone node modules

---

Packages/ohif-wadoproxy/server/routes.js

- Adding POST method into WADOProxy

feature(WADOProxy): Adding proxy to POST method

---

config/ClearCanvasDIMSE.json
config/dcm4cheeDICOMWeb.json
config/dcm4cheeDIMSE.json
config/medkenOrthanc.json
config/orthancDICOMWeb.json
config/orthancDIMSE.json
config/osirixDIMSE.json
config/publicOrthancDICOMWeb.json
dockersupport/app.json

-  Enabling range day limits on study search

#200 bugfix: View Today's Results by Default

---

docker-compose.yml

- adding a relative path into docker-compose to use dockersupport/app.json

#199 bugfix: Docker Support

---

Packages/ohif-cornerstone/package.js
Packages/ohif-measurement-table/client/configuration/measurementTools.js
Packages/ohif-measurement-table/client/schema/arrowAnnotate.js
Packages/ohif-measurement-table/client/schema/ellipticalRoi.js
Packages/ohif-measurement-table/client/schema/rectangleRoi.js
Packages/ohif-measurement-table/client/schema/simpleAngle.js

- Small refactor into schema of all tools
- Add ArrowAnnotate tool support into measurement-table
- Add SimpleAngle support into measurement-table
- Updating cornerstoneTools version to latest

Adding ArrowAnnotate and simpleAngle into measurement-table

---

Packages/ohif-study-list/client/components/studylist/studylistResult/studylistResult.js

fix date parser for studyDate - convertStringToStudyDate was not been called in dicomweb-client - change convertStringToStudyDate call to momentjs

fix study date search

---

.gitignore
OHIFViewer-react/public/index.html
OHIFViewer-react/src/Header/Header.css
OHIFViewer-react/src/Header/Header.js
OHIFViewer-react/src/Header/HeaderMenuList.json
OHIFViewer-react/src/Header/index.js
OHIFViewer-react/src/Viewer/Viewer.js
OHIFViewer-react/src/components/Dropdown/Dropdown.css
OHIFViewer-react/src/components/Dropdown/Dropdown.js
OHIFViewer-react/src/components/index.js
OHIFViewer-react/src/images/icons.svg
OHIFViewer-react/src/theme-tide.css

This PR implements the `Header` component...
...and a shareable `Dropdown` component in React:

(React) - Header and Dropdown component

---

Packages/ohif-viewerbase/client/lib/classes/LayoutManager.js

Fix to #337.
This fix is for the `master` branch.

[Master] Memleak

---

Packages/ohif-viewerbase/client/components/viewer/imageViewerViewport/imageViewerViewport.js
Packages/ohif-viewerbase/client/lib/classes/LayoutManager.js

Fix to #337, (and similarly JamesAPetts/ohif-viewer-XNAT-plugin#25.).
This fix is for the `cornerstone-tools-next` branch.

[vNext] Memleak

---

.releaserc

https://semantic-release.gitbook.io/semantic-release/usage/configuration#branch

 Specify branch differently in releaserc

---

Packages/ohif-google-cloud/package.js

https://github.com/quantumsoftgroup/healthcare-api-adapter/issues/2

Update of healthcare-api-adapter to support more than 1000 projects

---

extensions/ohif-cornerstone-extension/src/ConnectedCornerstoneViewport.js
src/connectedComponents/ConnectedViewerMain.js
src/connectedComponents/ConnectedViewerRetrieveStudyData.js
src/connectedComponents/ViewerMain.js
src/studylist/ConnectedStudyList.js

Revert "React viewport"

---

extensions/ohif-cornerstone-extension/package.json
extensions/ohif-cornerstone-extension/yarn.lock
package.json
yarn.lock

Bump ohif-cornerstone-extension to 0.0.31

fix(dependencies): Bump react-cornerstone-viewport to 0.1.28

---

package.json
yarn.lock

fix(dependencies): Bump cornerstone-tools to 3.11.0

---

extensions/ohif-vtk-extension/package.json
extensions/ohif-vtk-extension/src/ConnectedToolbarSection.js
package.json
yarn.lock

Related to https://github.com/OHIF/Viewers/issues/563

@ohif/extension-vtk: Enable rotate button (0.0.5)

---

package.json
yarn.lock

feat(@ohif/extension-vtk): Add visible crosshair lines to MPR mode

---

extensions/ohif-dicom-microscopy-extension/package.json
extensions/ohif-dicom-microscopy-extension/src/DicomMicroscopyViewport.js

@ohif/extension-dicom-microscopy: Use retrieveRendered for frame retrieval

@ohif/extension-dicom-microscopy: Use retrieveRendered

---

package.json
yarn.lock

fix(extension-dicom-microscopy): Update to 0.0.8 to use retrieveRendered by default

fix(extension-dicom-microscopy): Update to 0.0.8

---

src/components/Header/Header.js

Bumping react-viewerbase version

feat(Header.js): Adding back the info at options

---

.gitattributes
docs/latest/essentials/translating.md
extensions/ohif-i18n/README.md
extensions/ohif-i18n/package.json
extensions/ohif-i18n/rollup.config.js
extensions/ohif-i18n/src/index.js
extensions/ohif-i18n/src/locales/en/UK/index.js
extensions/ohif-i18n/src/locales/en/US/index.js
extensions/ohif-i18n/src/locales/en/index.js
extensions/ohif-i18n/src/locales/es/AR/index.js
extensions/ohif-i18n/src/locales/es/Buttons.json
extensions/ohif-i18n/src/locales/es/Common.json
extensions/ohif-i18n/src/locales/es/MX/index.js
extensions/ohif-i18n/src/locales/es/MeasurementTable.json
extensions/ohif-i18n/src/locales/es/index.js
extensions/ohif-i18n/src/locales/index.js
extensions/ohif-vtk-extension/package.json
extensions/ohif-vtk-extension/src/loadLocales.js
extensions/ohif-vtk-extension/src/locales/en/index.js
extensions/ohif-vtk-extension/src/locales/es/index.js
extensions/ohif-vtk-extension/src/locales/index.js
extensions/ohif-vtk-extension/webpack.config.js
extensions/ohif-vtk-extension/yarn.lock
package.json
yarn.lock

Replace use of context to import locales

---

package.json
yarn.lock

fix(package.json): Bump ohif-core to fix broken multiframe usage with WADO-RS
fix #539

fix(package.json): Bump ohif-core to fix broken multiframes with WADO-RS

---

extensions/ohif-i18n/package.json
extensions/ohif-i18n/src/index.js

I'm not smart and should have guarded this statement...

@ohif-i18n 0.2.1: Prevent crashing when window.config is undefined

---

README.md

Adjusting README file related to Cypress to use the correct commands. We changed the commands for cypress and didn't update the documentation for it.

feat: Adjusts README file

---

extensions/ohif-dicom-microscopy-extension/package.json
extensions/ohif-dicom-microscopy-extension/rollup.config.js
extensions/ohif-dicom-microscopy-extension/src/DicomMicroscopyViewport.js
extensions/ohif-dicom-microscopy-extension/yarn.lock
package.json
yarn.lock

fix(DicomMicroscopyViewport): adding updateSize call when the viewport gets resized

Fixing issue #550

---

src/setupTools.js

- Update naming of configuration to props as cornerstoneTools has also changed

fix(labelling)

---

package.json
src/OHIFStandaloneViewer.js
src/connectedComponents/ViewerLocalFileData.css
src/connectedComponents/ViewerLocalFileData.js
src/lib/filesToStudies.js
src/studylist/StudyListWithData.js
yarn.lock

feat(ViewerLocalFileData): Add drag/drop to load DICOM files in the Viewer at /local
- Drag/drop onto the Study List will display the studies in the list
- Drag/drop onto the page at /local and you can view the studies in the viewer
- Stop throwing errors if non-DICOM files are found.
- Clicking on a study in the list should show it in the viewer. This doesn't happen yet
- Would be nice to add a Folder selector via the browser, but I think only Chrome supports that
Demo link: https://deploy-preview-644--ohif.netlify.com/demo/local

feat(ViewerLocalFileData): Add drag/drop to load DICOM files

---

src/setupTools.js

Adding the Eraser tool to the list of supported tools.
We could also add this to the toolbar easily enough but here we go for now.
https://github.com/trustsitka/sitka/issues/3403

Add the Eraser to the available tools

---

public/config/google.js

fix of hardcoded url

---

docs/latest/connecting-to-image-archives/google-cloud-healthcare.md

Brought up in #585, thanks @stormert!

docs(google-cloud): Fix OAuth Callback URL

---

package.json
yarn.lock

Finally closes #551 - Thanks @biharck!

fix(package.json): Bump cornerstone-tools to 3.16.0

---

package.json
public/config/google.js
public/config/local_dcm4chee.js
src/googleCloud/ConnectedDicomFilesUploader.js
src/googleCloud/DicomFileUploaderModal.js
src/googleCloud/DicomUploader.css
src/googleCloud/DicomUploader.js
src/googleCloud/api/DicomUploadService.js
src/googleCloud/googleCloud.css
src/googleCloud/utils/helpers.js
src/studylist/StudyListRouting.js
src/studylist/StudyListWithData.js
yarn.lock

**Note:**
- Removed the Metadata from the Google Cloud config because it seems to be changing on a day-to-day basis.

feat(DicomUploader): Make DICOM Uploader work with all DICOMWeb servers

---

extensions/ohif-i18n/package.json
extensions/ohif-i18n/src/locales/zh/Common.json
extensions/ohif-i18n/src/locales/zh/MeasurementTable.json
extensions/ohif-i18n/src/locales/zh/StudyList.json
extensions/ohif-i18n/src/locales/zh/index.js
package.json
yarn.lock

Add community-contributed Chinese translation improvements

---

.netlify/build-deploy-preview.sh
docs/latest/connecting-to-image-archives/google-cloud-healthcare.md
docs/latest/deployment/recipes/build-for-production.md
docs/latest/deployment/recipes/nginx--image-archive.md
docs/latest/deployment/recipes/user-account-control.md
docs/latest/essentials/configuration.md
docs/latest/essentials/data-source.md
platform/viewer/.recipes/Nginx-Dcm4che/docker-compose-dcm4che.yml
platform/viewer/.recipes/OpenResty-Orthanc-Keycloak/dockerfile
platform/viewer/.recipes/OpenResty-Orthanc/dockerfile

replaced REACT_APP_CONFIG with APP_CONFIG to reflect latest OHIF monorepo updates

fix: 🐛 replaced REACT_APP_CONFIG with APP_CONFIG

---

extensions/cornerstone/src/toolbarModule.js
platform/ui/src/elements/Icon/getIcon.js
platform/ui/src/elements/Icon/icons/eraser.svg

Adds the Eraser tool to OHIF viewer. 
Solves the issue: https://github.com/OHIF/Viewers/issues/819

feat(Eraser Tool)

---

extensions/cornerstone/src/toolbarModule.js

Adds the Bidirectional Tool and solves part of the issue: https://github.com/OHIF/Viewers/issues/819

feat(Bidirectional Tool)

---

platform/viewer/cypress/integration/common/OHIFStudyViewer.spec.js
platform/viewer/package.json

Address issues breaking e2e

---

extensions/cornerstone/.webpack/webpack.prod.js
extensions/cornerstone/src/asyncComponent.js
extensions/cornerstone/src/index.js
extensions/dicom-html/.webpack/webpack.prod.js
extensions/dicom-html/src/asyncComponent.js
extensions/dicom-html/src/index.js
extensions/dicom-microscopy/.webpack/webpack.prod.js
extensions/dicom-microscopy/src/DicomMicroscopyViewport.js
extensions/dicom-microscopy/src/asyncComponent.js
extensions/dicom-microscopy/src/index.js
extensions/vtk/.webpack/webpack.prod.js
extensions/vtk/src/asyncComponent.js
extensions/vtk/src/index.js
platform/viewer/.webpack/webpack.commonjs.js
platform/viewer/src/OHIFStandaloneViewer.js

TODO: Use React.Lazy and a Suspense wrapper thing: https://reactjs.org/docs/code-splitting.html#reactlazy

fix: Add some code splitting for PWA build

---

docs/latest/advanced/extensions.md
platform/viewer/src/connectedComponents/ToolbarRow.js

- Implement custom react component solution for toolbar elements
- Changes on docs
Closes: 924
The following screenshoot is a sample of its usage and it is NOT part of this PR

feat: 🎸 React custom component on toolbar button

---

extensions/cornerstone/package.json
platform/viewer/package.json

fix: version bump issue

---

package.json

fix: yarn run start as alias for yarn run dev

---

platform/viewer/src/connectedComponents/ConnectedLayoutButton.js

Small workaround to deal with this: https://github.com/OHIF/Viewers/issues/933

fix: Exit MPR mode if Layout is changed

---

platform/i18n/src/locales/en-US/CineDialog.json
platform/i18n/src/locales/es/CineDialog.json
platform/i18n/src/locales/ja-JP/CineDialog.json
platform/i18n/src/locales/vi/CineDialog.json

fix: CineDialog buttons label

---

platform/viewer/src/connectedComponents/PluginSwitch.js

fix: 🐛 Remove debugger statement left in from last PR

---

extensions/vtk/package.json
platform/viewer/package.json
yarn.lock

Switch to orthographic view for MPR.
Known issue, the MPR slider also acts as a zoom, as you are having to move the camera to sample the MIP.

fix: 🐛 Switch to orthographic view for 2D MPR

---

extensions/vtk/package.json
platform/core/src/classes/metadata/StudyMetadata.js
platform/viewer/package.json
yarn.lock

Fix the orthographic rendering in VTK ports.

fix: 🐛 Orthographic MPR fix

---

platform/core/src/redux/reducers/viewports.js
platform/viewer/src/connectedComponents/ConnectedStudyBrowser.js
platform/viewer/src/connectedComponents/Viewer.js

fix: set SR in ActiveViewport by clicking thumb

---

platform/viewer/.webpack/webpack.commonjs.js
platform/viewer/public/html-templates/script-tag.html

fix: update script-tag output to include config from default.js

---

platform/viewer/src/studylist/StudyListRoute.js

fix: get adapter store picker to show

---

platform/ui/src/components/measurementTable/MeasurementTableItem.styl
platform/ui/src/components/tableList/TableListItem.styl
platform/viewer/src/appExtensions/MeasurementsPanel/ConnectedMeasurementTable.js
platform/viewer/src/appExtensions/MeasurementsPanel/labelingFlowCallbacks.js
platform/viewer/src/components/Labelling/LabellingFlow.js

- Minor fixes only, related to description on measurement right panel
#1098

fix: 🐛 Minor issues measurement panel related to description

---

platform/viewer/src/connectedComponents/ConnectedHeader.js

- Prevent JS breaking on ConnectedHeader.js

fix: 🐛 Fix for JS breaking on header

---

platform/viewer/src/googleCloud/DatasetPicker.js
platform/viewer/src/googleCloud/DatasetsList.js
platform/viewer/src/googleCloud/DicomStoreList.js
platform/viewer/src/googleCloud/DicomStorePicker.js
platform/viewer/src/googleCloud/LocationPicker.js
platform/viewer/src/googleCloud/LocationsList.js
platform/viewer/src/googleCloud/ProjectPicker.js
platform/viewer/src/googleCloud/ProjectsList.js
platform/viewer/src/googleCloud/googleCloud.css

filter field for google windows

filter field for google windows

---

platform/ui/src/components/userPreferencesForm/HotKeysPreferences.js
platform/ui/src/components/userPreferencesForm/UserPreferences.js
platform/ui/src/components/userPreferencesForm/UserPreferencesForm.js

Improve hotkeyPreferences proptypes and lowercase event keys to guard
against different browsers casings

refactor: 💡 Improve hotkeyPreferences proptypes / add lowercase

---

platform/viewer/src/googleCloud/ProjectsList.js

seems like some of internal google's project may contain incorrect characters  and won't be parsed in json response

fix of undefined name of project

---

README.md
docs/latest/services/ui/index.md
platform/core/src/index.js
platform/core/src/index.test.js
platform/core/src/services/ServicesManager.js
platform/core/src/services/ServicesManager.test.js
platform/core/src/services/UIContextMenuService/index.js
platform/core/src/services/UIDialogService/index.js
platform/core/src/services/UILabellingFlowService/index.js
platform/core/src/services/UIModalService/index.js
platform/core/src/services/UINotificationService/index.js
platform/core/src/services/index.js
platform/viewer/src/App.js
yarn.lock

Refactor servicesManager to take factory functions instead of instances
Closes: #1265

refactor: 💡 ServicesManager factory functions vs instances

---

extensions/cornerstone/src/init.js

Fixes the broken wwwc region tool.
Fixes #1174 
@dannyrb, can you review, please?

fix: 🐛 add WwwcRegionTool to cornerstone tools initialization

---

platform/viewer/cypress/integration/pwa/OHIFExtensionVTK.spec.js

- Remove delay once we click on `2D MPR` button
Closes: #1167
@mirnasilva 

test: 💍 Updating tests after bug fix

---

extensions/vtk/src/commandsModule.js

Contributing: Fix a typo

---

platform/ui/src/components/measurementTable/MeasurementTableItem.styl
platform/ui/src/components/tableList/TableListItem.styl

Linked Issue : https://github.com/OHIF/Viewers/issues/1313
Fix css of measurements panel. There was an invisible delete button and some weird width calculations.
-OLD
-NEW

Fix measurements panel css and delete button visibility

---

platform/viewer/cypress/integration/visual-regression/PercyCheckOHIFExtensionVTK.spec.js

Percy tests - fix for CI failure

---

platform/viewer/cypress/integration/pwa/OHIFSaveMeasurements.spec.js
platform/viewer/cypress/support/commands.js

Percy ci fix

---

platform/viewer/cypress/integration/pwa/OHIFSaveMeasurements.spec.js
platform/viewer/cypress/integration/visual-regression/PercyCheckOHIFExtensionVTK.spec.js
platform/viewer/cypress/support/commands.js

Percy fix for CI failure

---

.circleci/config.yml

Changed the CI config file.
Fix for this CI [failure](http://email.circleci.com/c/eJwtj8tugzAQRb8Gdkb4gYkXLCIlUbvoQ110WxnbwFAbI2NA4evrKJVGo5lzR1d3dHPi4pRD83apjrGGqz02dXy-3-fgv84FrmpBS8xLLCjPWDn7JUpbKAjKGmRNL9UdTT5CByagDaOKccY6zeoajf3YiXxopO4Iq1rJCDVC4bYlirWUGkNYSxhWuW2GGOclo-eM3FI93RUUyru09kNqHy-vD-kbzG7CkiaBGc_obY3uR0k3S-injF52H34763fUSbBGZ4Q_DpzRsLokG5fwP1z8GpRJ8BlfyQh-ykPjIEyyWMBuMj0cpE6SBSd7mPpHoj8EZmTd)

Visual tests: Fixed ci config for visual tests (percy)

---

platform/viewer/cypress/integration/common/OHIFStudyList.spec.js
platform/viewer/cypress/integration/pwa/OHIFSaveMeasurements.spec.js

Due to one Patient that was removed from our server, some tests are failing on CI.
This PR will cover the fix for this, by choosing another Patient Study.

Fix on CI - Choosing another Patient Study

---

platform/viewer/src/OHIFStandaloneViewer.js

Implementation of the /login endpoint defined by OIDC.
https://openid.net/specs/openid-connect-core-1_0.html#ThirdPartyInitiatedLogin
@swederik @dannyrb

OIDC Initiating Login from a Third Party

---

platform/core/src/services/MeasurementService/MeasurementService.js
platform/core/src/services/MeasurementService/MeasurementService.test.js

Update measurement service log to warn
✅ Closes: #1451

refactor: 💡 Update measurement service log to warn

---

extensions/cornerstone/package.json
yarn.lock

fixes: https://github.com/OHIF/Viewers/issues/1472

fix: bump react-cornerstone-viewport version to address critical issue

---

platform/viewer/cypress/integration/common/OHIFCornerstoneToolbar.spec.js
platform/viewer/cypress/integration/common/OHIFStudyViewer.spec.js
platform/viewer/cypress/integration/pwa/OHIFSaveMeasurements.spec.js

This PR is intended to be merged into branch OHIF:igor/1370-cog-settings, to fix the test failures in PR #1392

Fix for failing tests

---

platform/ui/src/components/Button/Button.jsx
platform/ui/src/views/StudyList/StudyList.js
platform/ui/src/views/StudyList/components/Header.js
platform/ui/src/views/StudyList/components/StudyListFilter.js
platform/ui/src/views/StudyList/components/StudyListTable.js
platform/ui/tailwind.config.js

**OHIF-39**
**OHIF-36**
Some minor Study List style fixes.
**Sticky Header + Filter**

fix: UI v2 Study List style fixes

---

platform/viewer/src/connectedComponents/ConnectedStudyBrowser.js
platform/viewer/src/connectedComponents/findDisplaySetByUID.js
platform/viewer/src/connectedComponents/findDisplaySetByUID.test.js
yarn.lock

resolves #1483 by searching all displaySets instead of assuming it's in the first studyMetadata.  added to a separate file with a 100% covered test to try to reduce impact to project overall.

fix: resolves #1483

---

platform/core/package.json
platform/core/src/redux/reducers/viewports.js
platform/viewer/src/components/ViewportGrid/ConnectedViewportGrid.js
platform/viewer/src/components/ViewportGrid/ViewportGrid.js
platform/viewer/src/connectedComponents/ViewerMain.js
yarn.lock

avoid-wasteful-renders

---

platform/ui/src/components/Button/Button.mdx
platform/ui/src/components/ButtonGroup/ButtonGroup.mdx
platform/ui/src/components/DateRange/DateRange.mdx
platform/ui/src/components/Icon/icon.mdx
platform/ui/src/components/Input/Input.mdx
platform/ui/src/components/Label/Label.mdx
platform/ui/src/components/Select/Select.mdx
platform/ui/src/components/Typography/Typography.mdx
platform/ui/src/views/StudyList/StudyList.mdx

Fix docz import typo

---

platform/viewer/src/appExtensions/MeasurementsPanel/jumpToRowItem.js

Possible solution for request https://github.com/OHIF/Viewers/issues/1522 ?

Load measurement in active viewport.

---

.github/stale.yml

update stale.yml to not close IDC related issues

---

platform/ui/src/assets/icons/tool-annotate.svg
platform/ui/src/assets/icons/tool-bidirectional.svg
platform/ui/src/assets/icons/tool-elipse.svg
platform/ui/src/assets/icons/tool-length.svg
platform/ui/src/components/Icon/getIcon.jsx
platform/ui/src/components/SidePanel/SidePanel.jsx
platform/ui/src/components/SidePanel/SidePanel.mdx
platform/ui/src/gatsby-theme-docz/components/NavGroup/index.js
platform/ui/src/views/ToolbarHeader/ToolbarHeader.mdx
platform/ui/src/views/ToolbarSecondary/ToolbarSecondary.mdx
platform/ui/src/views/Viewer/Viewer.js
platform/ui/src/views/Viewer/Viewer.mdx

**OHIF-80**
This PR creates a doc page with an example showing how to build a Secondary Toolbar.

feat: Secondary Toolbar

---

docs/latest/deployment/recipes/embedded-viewer.md

Added how to embed OHIF viewer in an existing React application
- Added a small scrip on how to embed OHIF in an existing app, as I spent a lot of time doing this
- Relevant issues #899 

Embedding in existing react App (Documentation only)

---

platform/ui/index.js
platform/ui/src/assets/icons/circled-checkmark.svg
platform/ui/src/assets/icons/dotted-circle.svg
platform/ui/src/assets/icons/tracked.svg
platform/ui/src/assets/styles/styles.css
platform/ui/src/components/Icon/getIcon.jsx
platform/ui/src/components/SidePanel/SidePanel.jsx
platform/ui/src/components/StudyBrowser/StudyBrowser.jsx
platform/ui/src/components/StudyBrowser/StudyBrowser.mdx
platform/ui/src/components/StudyBrowser/index.js
platform/ui/src/components/StudyBrowser/mockData.js
platform/ui/src/components/StudyItem/StudyItem.jsx
platform/ui/src/components/StudyItem/index.js
platform/ui/src/components/Thumbnail/Thumbnail.jsx
platform/ui/src/components/Thumbnail/index.js
platform/ui/src/components/ThumbnailList/ThumbnailList.jsx
platform/ui/src/components/ThumbnailList/index.js
platform/ui/src/components/ThumbnailSR/ThumbnailSR.jsx
platform/ui/src/components/ThumbnailSR/index.js
platform/ui/src/components/index.js
platform/ui/src/views/ToolbarHeader/ToolbarHeader.mdx
platform/ui/src/views/Viewer/Viewer.js
platform/ui/src/views/Viewer/Viewer.mdx

**OHIF-79**
UI implementation using mockdata for StudyBrowser, designed to be the content of a sidePanel.

OHIF-79: Study Browser side panel

---

platform/ui/index.js
platform/ui/src/components/ViewportGrid/ViewportGrid.jsx
platform/ui/src/components/ViewportGrid/ViewportGrid.mdx
platform/ui/src/components/ViewportGrid/index.js
platform/ui/src/components/index.js

Create a component to organize nodes/component in a grid strucure.

OHIF-77: Viewport grid component

---

platform/ui/src/components/StudyListPagination/StudyListPagination.js
platform/ui/src/contextProviders/ModalComponent.jsx
platform/ui/src/contextProviders/ModalProvider.js
platform/ui/src/contextProviders/ModalProvider.mdx
platform/ui/src/gatsby-theme-docz/components/NavGroup/index.js
platform/ui/src/gatsby-theme-docz/components/Sidebar/index.js

Small doc page for Modal Provider
https://deploy-preview-1609--ohif.netlify.com/ui/contextProviders/modalProvider

OHIF-43: Modal Provider Docz

---

platform/ui/src/components/SidePanel/SidePanel.jsx
platform/ui/src/components/StudyBrowser/StudyBrowser.jsx
platform/ui/src/views/Viewer/Viewer.js
platform/ui/src/views/Viewer/Viewer.mdx
platform/ui/src/views/Viewer/components/Header.js
platform/ui/src/views/Viewer/components/ViewportToolBar.js

**OHIF-78**
Combining all components for Viewer in the viewer dicz example.

UI-v2: Viewer page

---

platform/ui/src/components/Notification/Notification.jsx
platform/ui/src/components/SidePanel/SidePanel.jsx
platform/ui/src/components/StudyBrowser/StudyBrowser.jsx
platform/ui/src/components/StudyItem/StudyItem.jsx
platform/ui/src/components/Thumbnail/Thumbnail.jsx
platform/ui/src/components/ThumbnailList/ThumbnailList.jsx
platform/ui/src/components/ThumbnailSR/ThumbnailSR.jsx
platform/ui/src/components/ViewportActionBar/ViewportActionBar.jsx
platform/ui/src/views/Viewer/Viewer.mdx
platform/ui/tailwind.config.js

Fixes: 
- Fix SidePanels width and inner Thumbnails paddings
- Remove outline border on selected Thumbnail
- SR Thumbnail -- added an `onClick` method and cursor-pointer -- needs clarification on hover/selected styles.
- SHOW: Example Viewport Notification

fix: UI-v2 Small defects

---

extensions/dicom-p10-downloader/.webpack/webpack.dev.js
extensions/dicom-p10-downloader/.webpack/webpack.prod.js
extensions/dicom-p10-downloader/CHANGELOG.md
extensions/dicom-p10-downloader/LICENSE
extensions/dicom-p10-downloader/README.md
extensions/dicom-p10-downloader/package.json
extensions/dicom-p10-downloader/src/commandsModule.js
extensions/dicom-p10-downloader/src/downloadAndZip.js
extensions/dicom-p10-downloader/src/index.js
extensions/dicom-p10-downloader/src/utils.js
platform/core/src/utils/Queue.js
platform/core/src/utils/Queue.test.js
platform/core/src/utils/hierarchicalListUtils.js
platform/core/src/utils/hierarchicalListUtils.test.js
platform/core/src/utils/index.js
platform/core/src/utils/index.test.js
platform/core/src/utils/isDicomUid.js
platform/core/src/utils/isDicomUid.test.js
platform/core/src/utils/makeDeferred.js
platform/core/src/utils/makeDeferred.test.js
platform/core/src/utils/progressTrackingUtils.js
platform/core/src/utils/progressTrackingUtils.test.js
platform/core/src/utils/resolveObjectPath.js
platform/core/src/utils/resolveObjectPath.test.js
platform/viewer/package.json
platform/viewer/public/config/default.js
platform/viewer/src/index.js

Introducing a new extension to support downloading and zipping SOP instances from a study

Feat #1130 [WIP] Adding support for downloading and zipping files

---

platform/viewer/src/App.js
platform/viewer/src/components/Header/Header.js
platform/viewer/src/connectedComponents/Viewer.js
platform/viewer/src/routes/routesUtil.js
platform/viewer/src/studylist/StudyListRoute.js

w/ `showStudyList` `false`
w/ `showStudyList` `true` or `undefined`

fix: `showStudyList` config

---

extensions/cornerstone/src/initCornerstoneTools.js
platform/core/src/studies/services/wado/studyInstanceHelpers.js
yarn.lock

@dannyrb Fixes multiframe image loading for wado-rs (it appears only wado-uri was fixed in #1595 .

fix: 🐛 Multiframe fix

---

platform/ui/index.js
platform/ui/src/components/Viewport/Viewport.jsx
platform/ui/src/components/Viewport/Viewport.mdx
platform/ui/src/components/Viewport/index.js
platform/ui/src/components/ViewportActionBar/ViewportActionBar.jsx
platform/ui/src/components/ViewportActionBar/ViewportActionBar.mdx
platform/ui/src/components/ViewportGrid/ViewportGrid.jsx
platform/ui/src/components/index.js
platform/ui/src/views/Viewer/Viewer.mdx
platform/ui/src/views/Viewer/components/ViewportToolBar.js

This PR creates the Viewport API definition, a `Viewport` Component that is used in the `ViewportGrid`, and updates in the documentation pages.
Nothing changes.

feat: OHIF-111 Viewport API

---

extensions/dicom-segmentation/src/components/SegmentationPanel/SegmentationPanel.js

Observe selectedSegmentation changes to refresh segment list
✅ Closes: #1669

fix: 🐛 Dropdown not updating when selecting segment

---

platform/ui/src/components/ViewportActionBar/ViewportActionBar.jsx
platform/ui/src/components/ViewportGrid/ViewportGrid.jsx
platform/ui/tailwind.config.js

fix small defects

---

extensions/dicom-html/src/DicomHtmlViewport.js
extensions/dicom-rt/src/loadRTStruct.js
extensions/dicom-segmentation/src/loadSegmentation.js
platform/core/src/DICOMSR/handleStructuredReport.js
platform/core/src/DICOMSR/parseDicomStructuredReport.js
platform/core/src/DICOMSR/parseMeasurementsData.js
platform/core/src/DICOMSR/utils/isToolSupported.js
platform/core/src/classes/MetadataProvider.js
platform/viewer/src/lib/localFileLoaders/dicomFileLoader.js

This PR changes `dcmjs` imports from `import * as dcmjs from 'dcmjs` to `import dcmjs from 'dcmjs'` in files in the `/extensions` and `/platform` projects. 
Closes #1599 
@swederik @dannyrb 

Cleanup imports

---

platform/core/src/index.js
platform/core/src/services/UIViewportDialogService/index.js
platform/core/src/services/index.js
platform/ui/index.js
platform/ui/src/components/Dialog/Dialog.jsx
platform/ui/src/components/Dialog/index.js
platform/ui/src/components/index.js
platform/ui/src/contextProviders/ViewportDialogProvider.jsx
platform/ui/src/contextProviders/ViewportDialogProvider.mdx
platform/ui/src/contextProviders/index.js
platform/ui/src/gatsby-theme-docz/components/Sidebar/index.js

- Create a Viewport Dialog Provider based on a dialog component. 
- Create a Viewport Dialog Service to be able to control multiple Viewport Dialog Providers
- Docz page with examples of both implementations

OHIF-112: Notification provider and service

---

platform/viewer/public/config/default.js
platform/viewer/public/config/netlify.js
platform/viewer/public/config/public_dicomweb.js

Add fuzzymatching to default server configs

---

extensions/cornerstone/package.json
extensions/dicom-rt/package.json
extensions/dicom-sr/package.json
extensions/measurement-tracking/src/viewports/TrackedCornerstoneViewport.js
extensions/vtk/package.json
platform/core/package.json
platform/viewer/package.json
yarn.lock

This PR adds dashed lines for non-tracked measurements.

OHIF-176: v2 - Render non-tracked measurements as a dashed lines.

---

extensions/default/src/ViewerLayout/index.jsx
modes/longitudinal/src/toolbarButtons.js
platform/core/src/services/ToolBarService/ToolBarService.js
platform/ui/index.js
platform/ui/src/components/ExpandableToolbarButton/ExpandableToolbarButton.css
platform/ui/src/components/ExpandableToolbarButton/ExpandableToolbarButton.jsx
platform/ui/src/components/ExpandableToolbarButton/ExpandableToolbarButton.mdx
platform/ui/src/components/ExpandableToolbarButton/index.js
platform/ui/src/components/IconButton/IconButton.jsx
platform/ui/src/components/ListMenu/ListMenu.jsx
platform/ui/src/components/ListMenu/ListMenu.mdx
platform/ui/src/components/ListMenu/index.js
platform/ui/src/components/Select/Select.jsx
platform/ui/src/components/Tooltip/Tooltip.jsx
platform/ui/src/components/index.js
platform/ui/tailwind.config.js

OHIF-152: Create window level dropdown menu

---

platform/core/src/DICOMSR/dataExchange.js
platform/core/src/extensions/ExtensionManager.js

responding to comments in #1811

[OHIF-177] - JSDocs

---

extensions/default/src/DicomWebDataSource/index.js
platform/core/src/DICOMSR/dataExchange.js
platform/core/src/extensions/ExtensionManager.js

RE OHIF-187, subticket of OHIF-11.

Add authoring information to exported DICOMs using the DICOMWeb DataSource

---

extensions/default/src/Panels/PanelStudyBrowser.jsx
extensions/default/src/Toolbar/ToolbarLayoutSelector.jsx
extensions/measurement-tracking/src/panels/PanelStudyBrowserTracking/PanelStudyBrowserTracking.jsx
extensions/measurement-tracking/src/viewports/TrackedCornerstoneViewport.js
platform/viewer/src/components/ViewportGrid.jsx

OHIF-165: Viewport grid should load in a 1x1 view by default

---

platform/ui/src/components/EmptyStudies/EmptyStudies.js
platform/viewer/src/routes/DataSourceWrapper.jsx
platform/viewer/src/routes/WorkList/WorkList.jsx

OHIF-150: Update worklist to use loading state of data source wrapper 

---

extensions/default/src/DicomWebDataSource/qido.js
extensions/dicom-sr/src/OHIFCornerstoneSRViewport.js
extensions/measurement-tracking/src/viewports/TrackedCornerstoneViewport.js
platform/core/src/utils/formatPN.js
platform/core/src/utils/index.js

OHIF-163: Patient Name is displayed in correct format "Last Name, First Name"

---

extensions/dicom-sr/src/OHIFCornerstoneSRViewport.js
extensions/measurement-tracking/src/viewports/TrackedCornerstoneViewport.js
platform/ui/src/components/ViewportActionBar/ViewportActionBar.jsx

OHIF-174: Patient Info Icon should be clickable and show the correct details

---

extensions/default/src/Toolbar/ToolbarLayoutSelector.jsx

OHIF-165: Fix broken solution after recent merge

---

extensions/measurement-tracking/src/getViewportModule.js
extensions/measurement-tracking/src/viewports/TrackedCornerstoneViewport.js
extensions/measurement-tracking/src/viewports/ViewportOverlay.js
platform/core/src/services/ToolBarService/ToolBarService.js
platform/ui/tailwind.config.js

OHIF-203: Add new viewport overlay

---

extensions/measurement-tracking/src/panels/PanelMeasurementTableTracking/index.js
platform/core/src/DICOMSR/dataExchange.js
platform/ui/src/assets/icons/close.svg
platform/ui/src/components/IconButton/IconButton.jsx
platform/ui/src/components/Snackbar/Snackbar.css
platform/ui/src/components/Snackbar/SnackbarContainer.jsx
platform/ui/src/components/Snackbar/SnackbarItem.jsx
platform/ui/src/contextProviders/DialogProvider.css
platform/ui/src/contextProviders/DialogProvider.jsx
platform/ui/tailwind.config.js

OHIF-179: UI for successful posting of SR data to PACS.

---

extensions/cornerstone/package.json
extensions/cornerstone/src/init.js
extensions/cornerstone/src/utils/measurementServiceMappings/ArrowAnnotate.js
extensions/cornerstone/src/utils/measurementServiceMappings/Bidirectional.js
extensions/cornerstone/src/utils/measurementServiceMappings/EllipticalRoi.js
extensions/cornerstone/src/utils/measurementServiceMappings/Length.js
extensions/dicom-sr/src/OHIFCornerstoneSRViewport.js
extensions/dicom-sr/src/getSopClassHandlerModule.js
extensions/dicom-sr/src/index.js
extensions/dicom-sr/src/utils/addMeasurement.js
extensions/dicom-sr/src/utils/getToolStateToCornerstoneMeasurementSchema.js
extensions/dicom-sr/src/utils/isRehydratable.js
extensions/measurement-tracking/src/contexts/TrackedMeasurementsContext/measurementTrackingMachine.js
extensions/measurement-tracking/src/viewports/TrackedCornerstoneViewport.js
platform/core/src/services/MeasurementService/MeasurementService.js
platform/ui/src/components/ViewportActionBar/ViewportActionBar.jsx
platform/viewer/src/components/ViewportGrid.jsx

SR's made by OHIF are rehydratable into the tracked measurements.
Currently has mock UI, a hydratable series has the [Edit] button. Currently this only usable performable once per displaySet to prevent loading of measurements twice.
With further guidance this can be changed later.

OHIF-190 - Rehydrate PR 

---

extensions/measurement-tracking/src/panels/PanelMeasurementTableTracking/index.js

OHIF-236: Measurement Table items should round measurements to two decimal places; matching cornerstone's rendered value

---

platform/ui/src/components/StudyItem/StudyItem.jsx
platform/ui/src/gatsby-theme-docz/tailwind.css

OHIF-264: Study Browser can be dragged partially out of view in Firefox

---

extensions/default/src/DicomWebDataSource/qido.js
platform/viewer/src/routes/DataSourceWrapper.jsx
platform/viewer/src/routes/WorkList/WorkList.jsx
platform/viewer/src/routes/index.js
yarn.lock

OHIF-149: Apply default sort of Study Date descending (most recent -> oldest) when < 101 studies

---

extensions/measurement-tracking/src/contexts/TrackedMeasurementsContext/promptTrackNewStudy.js

OHIF-242: Fix typo

---

platform/ui/src/components/Button/Button.jsx
platform/ui/src/components/StudyBrowser/StudyBrowser.jsx

OHIF-252: "Recent" and "All" tabs should be disabled if there are no studies on their category

---

platform/ui/src/components/MeasurementTable/MeasurementTable.jsx
platform/ui/src/components/ViewportActionBar/ViewportActionBar.jsx

OHIF-202: Add tooltip for locked/unlocked SR viewport icon

---

extensions/measurement-tracking/src/panels/PanelMeasurementTableTracking/index.js

Add support for "additional findings" section

---

extensions/dicom-sr/src/OHIFCornerstoneSRViewport.js

OHIF-286: Add missing patient info fields in sr

---

extensions/measurement-tracking/src/panels/PanelMeasurementTableTracking/index.js

Remove notification added in OHIF-208 PR, it's not necessary.

OHIF-208 Update: Remove measurements label updated successfully popup 

---

platform/ui/src/components/Modal/Modal.jsx

OHIF-330: Update Modal Styles

---

platform/ui/src/components/Thumbnail/Thumbnail.jsx
platform/ui/src/components/ThumbnailNoImage/ThumbnailNoImage.jsx

fix: OHIF-255 Fixes Thumbnail height for active item

---

extensions/cornerstone/package.json
extensions/cornerstone/src/commandsModule.js
extensions/dicom-rt/package.json
extensions/dicom-segmentation/package.json
extensions/dicom-sr/package.json
extensions/measurement-tracking/package.json
extensions/vtk/package.json
platform/core/package.json
platform/core/src/defaults/hotkeyBindings.js
platform/viewer/package.json
yarn.lock

Does what it says on the tin. Prevents the measurement being added to the measurement service and cancels it.

[OHIF-295] - Esc button should stop the creation of a measurement or annotation

---

platform/ui/src/assets/icons/external-link.svg
platform/ui/src/components/Icon/getIcon.jsx
platform/ui/src/components/Modal/Modal.jsx
platform/viewer/package.json
platform/viewer/src/components/PreferencesDropdown/AboutModal.jsx
platform/viewer/src/components/PreferencesDropdown/PreferencesDropdown.jsx

feat: OHIF-331 - About Modal

---

extensions/dicom-rt/src/OHIFDicomRTStructSopClassHandler.js
extensions/dicom-rt/src/components/RTPanel/RTPanel.js
extensions/dicom-rt/src/tools/modules/rtStructModule.js
extensions/dicom-segmentation/src/loadSegmentation.js
platform/core/src/classes/metadata/StudyMetadata.js
platform/core/src/utils/loadAndCacheDerivedDisplaySets.js
platform/viewer/cypress/integration/common/OHIFRoutes.spec.js
platform/viewer/cypress/integration/common/OHIFStudyList.spec.js
platform/viewer/cypress/integration/visual-regression/PercyCheckOHIFRoutes.spec.js
platform/viewer/public/config/idc.js

fix: 🐛 Fix RT Panel hide/show and Fix looping load errors

---

platform/ui/src/components/MeasurementTable/MeasurementItem.js

OHIF-284: Fix jump to measurement breaking keyboard shortcuts

---

platform/ui/index.js
platform/ui/src/assets/icons/clipboard.svg
platform/ui/src/components/Icon/getIcon.jsx
platform/ui/src/components/StudyListTable/StudyListTableRow.js
platform/ui/src/components/TooltipClipboard/TooltipClipboard.jsx
platform/ui/src/components/TooltipClipboard/TooltipClipboard.mdx
platform/ui/src/components/TooltipClipboard/index.js
platform/ui/src/components/index.js
platform/viewer/src/routes/WorkList/WorkList.jsx

Feat/OHIF-304 - Copying from Study List

---

platform/ui/src/components/StudyListPagination/StudyListPagination.js
platform/viewer/src/routes/WorkList/WorkList.jsx

- Fixes the "Clear Filters" button on first load.
- Fixes the pagination select value when clearing filters (clear was not reflecting).

fix: OHIF-260 - "Clear Filters" button should not be visible on first load, when no filters are set

---

extensions/cornerstone/src/init.js
modes/longitudinal/src/toolbarButtons.js

OHIF-324: Switch Probe to DragProbe and apply minimal strategy

---

extensions/cornerstone/package.json
extensions/dicom-rt/package.json
extensions/dicom-sr/package.json
platform/core/package.json
platform/viewer/package.json
yarn.lock

Updates cornerstoneTools to include this change:
https://github.com/cornerstonejs/cornerstoneTools/pull/1271

[OHIF-67] - Fix magnifying issues.

---

extensions/cornerstone/src/init.js
extensions/default/src/DicomWebDataSource/dcm4cheeReject.js
extensions/dicom-sr/src/OHIFCornerstoneSRViewport.js
extensions/measurement-tracking/src/panels/PanelMeasurementTableTracking/index.js
extensions/measurement-tracking/src/panels/PanelStudyBrowserTracking/PanelStudyBrowserTracking.jsx
extensions/measurement-tracking/src/panels/PanelStudyBrowserTracking/index.jsx
platform/ui/src/components/Dialog/Header.js
platform/ui/src/components/ThumbnailList/ThumbnailList.jsx
platform/ui/src/components/ThumbnailNoImage/ThumbnailNoImage.jsx

OHIF-316: Update DICOM SR thumbnail design to include a "delete" action

---

extensions/measurement-tracking/src/panels/PanelStudyBrowserTracking/PanelStudyBrowserTracking.jsx

OHIF-300: Add missing primary study to All tab

---

extensions/cornerstone/package.json
yarn.lock

Update react-cornerstone-viewport to 4.0.1.

[IDC-1956] - Remove loading %age which is always zero.

---

extensions/cornerstone/src/index.js
extensions/cornerstone/src/init.js
extensions/cornerstone/src/utils/getCornerstoneMeasurementById.js
extensions/cornerstone/src/utils/measurementServiceMappings/ArrowAnnotate.js
extensions/cornerstone/src/utils/measurementServiceMappings/Bidirectional.js
extensions/cornerstone/src/utils/measurementServiceMappings/EllipticalRoi.js
extensions/cornerstone/src/utils/measurementServiceMappings/Length.js
extensions/cornerstone/src/utils/measurementServiceMappings/measurementServiceMappingsFactory.test.js
extensions/cornerstone/src/utils/measurementServiceMappings/utils/getHandlesFromPoints.js
extensions/measurement-tracking/src/panels/PanelMeasurementTableTracking/index.js
platform/core/src/services/MeasurementService/MeasurementService.js
platform/core/src/services/UIDialogService/index.js
platform/ui/index.js
platform/ui/src/components/ContextMenu/ContextMenu.jsx
platform/ui/src/components/ContextMenu/ContextMenu.mdx
platform/ui/src/components/ContextMenu/index.js
platform/ui/src/components/ContextMenuMeasurements/ContextMenuMeasurements.jsx
platform/ui/src/components/ContextMenuMeasurements/index.js
platform/ui/src/components/index.js
platform/ui/src/contextProviders/DialogProvider.jsx

This PR contains the contents of #1830 #1928 and #1947 all bundled on top of the recent workflow changes, along with the rest of the features needed to complete OHIF-193.

[OHIF-193 + OHIF-313]

---

platform/ui/src/components/InputLabelWrapper/InputLabelWrapper.jsx

OHIF-320: Remove outline/shadow from Study List input filters when clicking to sort

---

extensions/measurement-tracking/src/panels/PanelMeasurementTableTracking/index.js
extensions/measurement-tracking/src/viewports/ViewportOverlay.js

In the viewport show: Instance# (imageIdIndex/stack size)
In the measurements panel imageIdIndex.
Where imageIdIndex is one-based rather than zero-based.

[OHIF-283] Show 1-based in stack position of measurement in measurements panel.

---

platform/ui/src/components/InputDateRange/InputDateRange.jsx

Clicking on the Study Date column header to sort by that column opens the date picker

OHIF-299: Fix focus on date picker

---

extensions/default/src/Panels/PanelStudyBrowser.jsx
extensions/default/src/Panels/requestDisplaySetCreationForStudy.js
extensions/measurement-tracking/src/panels/PanelStudyBrowserTracking/PanelStudyBrowserTracking.jsx
extensions/measurement-tracking/src/panels/PanelStudyBrowserTracking/requestDisplaySetCreationForStudy.js
platform/core/src/services/DisplaySetService/DisplaySetService.js

Fix study caching issues with related studies after navigating from a mode view of the same patient at a different study.

[OHIF-345] Fix caching issues with related studies.

---

platform/ui/src/components/InputGroup/InputGroup.jsx
platform/ui/src/components/InputLabelWrapper/InputLabelWrapper.jsx

OHIF-319: fix asc and desc order on sort label

---

platform/viewer/src/routes/WorkList/WorkList.jsx

OHIF-318: When the default sort "descending by study date" is applied, the UI should reflects the applied sorting

---

extensions/cornerstone/src/init.js

OHIF-303: Remove SVG cursors icons for tools

---

extensions/measurement-tracking/src/panels/PanelMeasurementTableTracking/index.js

OHIF-343: Jump to measurement on measurement edit

---

platform/ui/src/components/StudyListFilter/StudyListFilter.jsx

OHIF-145: Use sentence case for study list title

---

extensions/default/src/ViewerLayout/index.jsx

OHIF-276: Fix UI performance issues related to ToolbarService

---

extensions/cornerstone/package.json
extensions/cornerstone/src/utils/measurementServiceMappings/EllipticalRoi.js
extensions/dicom-rt/package.json
extensions/dicom-segmentation/package.json
extensions/dicom-sr/package.json
extensions/measurement-tracking/package.json
extensions/measurement-tracking/src/_shared/downloadCSVReport.js
extensions/measurement-tracking/src/panels/PanelMeasurementTableTracking/ActionButtons.jsx
extensions/measurement-tracking/src/panels/PanelMeasurementTableTracking/index.js
extensions/vtk/package.json
platform/core/package.json
platform/core/src/services/MeasurementService/MeasurementService.js
platform/viewer/package.json
yarn.lock

- Export as CSV on export click.
- Remove drop down on export for now.
Still awaiting feedback on the CSV columns format, do not merge yet.

[OHIF-326] Export as CSV.

---

platform/viewer/cypress/integration/visual-regression/PercyCheckOHIFExtensionVTK.spec.js

fix: Fix incorrect command name in Percy test

---

platform/ui/src/components/ThumbnailNoImage/ThumbnailNoImage.jsx

/viewer?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.3098.4963.203863325456615540256909411038

fix: set a min-width so flexbox doesn't shrink our lil svg

---

extensions/measurement-tracking/src/panels/PanelStudyBrowserTracking/PanelStudyBrowserTracking.jsx

fix: sort study cards by study date, descending

---

extensions/cornerstone/src/commandsModule.js
modes/longitudinal/src/index.js
platform/viewer/src/routes/Mode/Mode.jsx

fix: for incorrect toolbar state between routes

---

extensions/measurement-tracking/src/panels/PanelStudyBrowserTracking/PanelStudyBrowserTracking.jsx
platform/ui/src/components/Dialog/Dialog.jsx
platform/ui/src/components/Dialog/Footer.js

fix: autofocus reject SR dialog input focus to "Yes" button

---

modes/longitudinal/src/index.js
modes/longitudinal/src/toolbarButtons.js

fix: temporarily hide/disable capture until it can be repaired

---

extensions/measurement-tracking/src/_shared/downloadCSVReport.js

fix: update csv column titles to be consistent (UIDs)

---

extensions/cornerstone/src/CornerstoneViewportDownloadForm.js
extensions/measurement-tracking/src/panels/PanelMeasurementTableTracking/index.js
extensions/measurement-tracking/src/panels/PanelStudyBrowserTracking/PanelStudyBrowserTracking.jsx
platform/ui/src/components/MeasurementTable/MeasurementItem.js
platform/ui/src/components/ViewportDownloadForm/ViewportDownloadForm.jsx

Dannyrb/fix/ohif 380/ellipse should use exponent

---

platform/ui/src/components/ViewportActionBar/ViewportActionBar.jsx

fix: allow pointer events to pass through to arrow navigation buttons

---

platform/viewer/package.json
yarn.lock

fix: bump cornerstone-tools version to update rectangleROI behavior

---

extensions/cornerstone/src/init.js

fix: support for delete SR aliased measurements

---

extensions/dicom-rt/package.json
extensions/dicom-rt/src/loadRTStruct.js

RE #2063 
Hardens RTSTRUCT import for ContourSequence items that don't have a ContourImageSequence, by finding the nearest slice.

[IDC-2063] Harden RTSTRUCT import

---

extensions/vtk/package.json
yarn.lock

Fix https://github.com/OHIF/Viewers/issues/2127
see https://github.com/OHIF/react-vtkjs-viewport/pull/123

Update vtk crosshairs logic

---

.circleci/config.yml
package.json
platform/core/src/utils/Queue.test.js
platform/viewer/cypress.json
platform/viewer/cypress/integration/common/OHIFCornerstoneHotkeys.spec.js
platform/viewer/cypress/integration/common/OHIFCornerstoneToolbar.spec.js
platform/viewer/cypress/integration/common/OHIFDownloadSnapshotFile.spec.js
platform/viewer/cypress/integration/common/OHIFStudyList.spec.js
platform/viewer/cypress/integration/common/OHIFStudyViewer.spec.js
platform/viewer/cypress/integration/common/OHIFUserPreferences.spec.js
platform/viewer/cypress/integration/pwa/OHIFExtensionHTMLPDF.spec.js
platform/viewer/cypress/integration/pwa/OHIFExtensionMicroscopy.spec.js
platform/viewer/cypress/integration/pwa/OHIFExtensionVTK.spec.js
platform/viewer/cypress/integration/pwa/OHIFSaveMeasurements.spec.js
platform/viewer/cypress/integration/visual-regression/PercyCheckOHIFCornerstoneHotkeys.spec.js
platform/viewer/cypress/integration/visual-regression/PercyCheckOHIFCornerstoneToolbar.spec.js
platform/viewer/cypress/integration/visual-regression/PercyCheckOHIFDownloadSnapshotFile.spec.js
platform/viewer/cypress/integration/visual-regression/PercyCheckOHIFExtensionMicroscopy.spec.js
platform/viewer/cypress/integration/visual-regression/PercyCheckOHIFExtensionPDF.spec.js
platform/viewer/cypress/integration/visual-regression/PercyCheckOHIFExtensionVTK.spec.js
platform/viewer/cypress/integration/visual-regression/PercyCheckOHIFRoutes.spec.js
platform/viewer/cypress/integration/visual-regression/PercyCheckOHIFStudyViewer.spec.js
platform/viewer/cypress/integration/visual-regression/PercyCheckOHIFUserPreferences.spec.js
platform/viewer/cypress/plugins/index.js
platform/viewer/cypress/support/commands.js
platform/viewer/package.json
platform/viewer/public/config/dicomweb-server.js
yarn.lock

For some reason my Git client refuses to check out the branch in https://github.com/OHIF/Viewers/pull/1122 (something weird with the naming?), so I'm closing that PR and opening this one. Sorry @dannyrb :P

ci: trial run of using custom test data source #1122

---

.webpack/webpack.base.js

- Use runtime value configuration to get pkg version.
- Issue: #2023

About box reports incorrect version number

---

extensions/dicom-rt/src/OHIFDicomRTStructSopClassHandler.js
extensions/dicom-rt/src/components/RTPanel/RTPanel.js
extensions/dicom-rt/src/loadRTStruct.js
extensions/vtk/src/toolbarComponents/VTKMPRToolbarButton.js

- Comment: https://github.com/OHIF/Viewers/issues/2122#issuecomment-741820572
- Comment: https://github.com/OHIF/Viewers/issues/2117#issuecomment-741823904
- Related issue: #2117
- Related issue: #2122

Fix RTPanel and MPR button errors

---

extensions/vtk/src/OHIFVTKViewport.js
extensions/vtk/src/index.js
platform/core/src/services/UINotificationService/index.js
platform/ui/src/components/snackbar/Snackbar.css
platform/ui/src/components/snackbar/SnackbarItem.js
platform/ui/src/contextProviders/SnackbarProvider.js

Issue: #2192 
- Update the snack bar to have a new option to define an action.
- Add notification of exceeded buffer limit if buffer related errors.
- Add return button to exit mpr after failure.

feat(IDC-2192): Notify buffer allocation failure trying to do MPR for a large series

---

extensions/dicom-microscopy/src/DicomMicroscopyViewport.js
extensions/dicom-microscopy/src/index.js

feat(IDC-2223): Add error notification on microscopy viewport initialization errors

---

platform/viewer/src/studylist/StudyListRoute.js

fixes #2249

---

extensions/debugging/src/commandsModule.js
extensions/debugging/src/state.js
platform/viewer/src/index.js

Related issues:
- #2006
- #2223 (logger service)

bug(IDC-2006): Fix bug introduced with new logger service which broke debugger mailto functionality

---

extensions/cornerstone/src/OHIFCornerstoneViewport.js
extensions/cornerstone/src/commandsModule.js
extensions/cornerstone/src/index.js

IDC-2334: Resolve choppy scrolling in 2D mode 

---

Dockerfile

There were some utilities missing: python, make, g++. Also node version was too old - current node builds without problems. @swederik please, merge it

Update Dockerfile - fix missing dependencies

---

platform/core/src/classes/metadata/StudyMetadata.js
platform/core/src/utils/isDisplaySetReconstructable.js

Fix https://github.com/OHIF/Viewers/issues/2346
Data for testing: 
- http://localhost:3000/projects/idc-dev-etl/locations/us-central1/datasets/idc/dicomStores/v2/study/1.3.6.1.4.1.40744.29.20179378455677790749687821035665868086
other relevant issue https://github.com/OHIF/Viewers/issues/2259
Data for testing: 
- http://localhost:3000/projects/idc-dev-etl/locations/us-central1/datasets/idc/dicomStores/v2/study/1.3.6.1.4.1.14519.5.2.1.7695.1700.320115820687123759708360318530
- http://localhost:3000/projects/idc-dev-etl/locations/us-central1/datasets/idc_tcia_dev/dicomStores/idc_tcia/study/1.3.6.1.4.1.14519.5.2.1.8162.4009.498881901170332065029863238265

IDC2346: fix images sorting

---

platform/viewer/public/config/default.js

@igoroctaviano just noticed that the default.js was changed in https://github.com/OHIF/Viewers/commit/403688b18c52468fc1101166ec0c1734fb710039. Sorry did notice eralier since I tested also with my custom config.

clean back default config

---

extensions/default/src/DicomJSONDataSource/index.js
extensions/default/src/DicomLocalDataSource/index.js
extensions/default/src/DicomWebDataSource/index.js
extensions/default/src/getDataSourcesModule.js
platform/core/src/DataSources/IWebApiDataSource.js
platform/core/src/classes/MetadataProvider.js
platform/core/src/services/DicomMetadataStore/DicomMetadataStore.js
platform/core/src/services/DicomMetadataStore/createStudyMetadata.js
platform/ui/src/contextProviders/ViewportGridProvider.jsx
platform/viewer/package.json
platform/viewer/public/config/default.js
platform/viewer/public/html-templates/index.html
platform/viewer/src/components/ViewportGrid.jsx
platform/viewer/src/routes/Local/Local.jsx
platform/viewer/src/routes/Local/dicomFileLoader.js
platform/viewer/src/routes/Local/fileLoader.js
platform/viewer/src/routes/Local/fileLoaderService.js
platform/viewer/src/routes/Local/filesToStudies.js
platform/viewer/src/routes/Local/index.js
platform/viewer/src/routes/Local/pdfFileLoader.js
platform/viewer/src/routes/Mode/Mode.jsx
platform/viewer/src/routes/index.js
yarn.lock

OHIF-v3 - Support for local DICOM drag and drop

---

extensions/default/src/ViewerLayout/index.jsx
platform/core/src/utils/hotkeys/recordPlugin.js
platform/ui/src/components/HotkeyField/HotkeyField.jsx
platform/ui/src/components/HotkeysPreferences/HotkeysPreferences.jsx

fix: hotkeys editing in user preferences

---

extensions/default/src/DicomWebDataSource/index.js
modes/longitudinal/src/toolbarButtons.js
package.json
platform/ui/src/components/ThumbnailTracked/ThumbnailTracked.jsx
platform/viewer/package.json
platform/viewer/public/config/google.js

Fix: Google cloud config and tooltips

---

.vscode/launch.json
extensions/default/src/ViewerLayout/index.jsx
platform/docs/docs/platform/component-library/components/SidePanel.mdx
platform/docs/docs/platform/component-library/example-views/Viewer.mdx.todo
platform/ui/.webpack/webpack.prod.js
platform/ui/package.json
platform/ui/src/components/DateRange/DateRange.css
platform/ui/src/components/HotkeysPreferences/HotkeysPreferences.jsx
platform/ui/src/components/WindowLevelMenuItem/WindowLevelMenuItem.jsx
platform/ui/src/views/Viewer/Viewer.js
platform/ui/tailwind.config.js
platform/viewer/.webpack/webpack.pwa.js

fix(tailwind): Missed some changes when upgrading to tailwind 2.x

---

extensions/default/src/ViewerLayout/index.jsx
platform/core/src/classes/HotkeysManager.js
platform/core/src/classes/HotkeysManager.test.js
platform/core/src/utils/hotkeys/index.js
platform/core/src/utils/hotkeys/pausePlugin.js
platform/core/src/utils/hotkeys/recordPlugin.js
platform/docs/netlify.toml
platform/ui/src/components/HotkeyField/HotkeyField.jsx
platform/viewer/public/config/default.js
platform/viewer/public/config/netlify.js
platform/viewer/public/config/public_dicomweb.js
platform/viewer/src/routes/WorkList/WorkList.jsx

(v3) fix: setting hotkeys was broken

---

platform/docs/docusaurus.config.js
platform/docs/src/css/custom.css

feat: Add Algolia search for docs

---

platform/ui/src/components/AboutModal/AboutModal.jsx
platform/viewer/package.json

fix: About modal links

---

extensions/default/src/DicomWebDataSource/index.js

https://community.ohif.org/t/qido-wado-endpoints-handling-in-ohif-v3/24

fix: qido wrongly using wado config

---

platform/ui/src/components/studyBrowser/Thumbnail.js

fix: throttle thumbnail progress updates

---

platform/core/src/classes/MetadataProvider.js

fix: MetadataProvider number from string

---

extensions/cornerstone/package.json
extensions/dicom-sr/package.json
extensions/measurement-tracking/package.json
package.json
platform/core/package.json
platform/core/src/classes/MetadataProvider.js
platform/viewer/package.json
yarn.lock

fix: Address weird prefetching issues

---

platform/core/src/studies/services/qido/StaticWadoClient.js
platform/core/src/studies/services/qido/studies.js
platform/core/src/studies/services/wado/retrieveMetadataLoaderAsync.js
platform/viewer/public/config/local_static.js

Run against the static-wado for local access.
@swederik - who do you want looking at v2 changes?

Added the static wado client access to OHIF v2

---

.circleci/config.yml
extensions/dicom-tag-browser/src/components/DicomTagBrowser.js

Fix https://github.com/OHIF/Viewers/issues/2633

IDC Re #2633: fix slider min and max

---

extensions/cornerstone/src/commandsModule.js

Recreating a pull request to redeploy so it rebuilds.  Just removing some dead code.

fix(OHIFv3): Remove unused commands

---

platform/docs/docs/user-guide/index.md

fix(typo): `data` should be `date`

---

platform/core/src/classes/StudyLoadingListener.js

https://github.com/OHIF/Viewers/issues/2638

fix: DICOMFileLoadingListener typo in method name

---

platform/cli/src/commands/index.js
platform/cli/src/commands/listPlugins.js
platform/cli/src/index.js

feat: Add the list command to print extensions and modes

---

.circleci/config.yml
extensions/dicom-rt/src/components/RTPanel/RTPanel.js

Fix https://github.com/OHIF/Viewers/issues/2657
data for testing: https://viewer.imaging.datacommons.cancer.gov/viewer/1.3.6.1.4.1.14519.5.2.1.5168.1900.259520120774497994844579066293

IDC #2657: fix rt struct panel update

---

platform/cli/package.json
platform/cli/src/commands/index.js
platform/cli/src/commands/linkPackage.js
platform/cli/src/commands/unlinkPackage.js
platform/cli/src/commands/utils/addToConfig.js
platform/cli/src/commands/utils/index.js
platform/cli/src/commands/utils/installNPMPackage.js
platform/cli/src/commands/utils/uninstallNPMPackage.js
platform/cli/src/commands/utils/validateYarn.js
platform/cli/src/index.js

Fix/cli working directory and link local modes/extensions

---

platform/cli/src/commands/createExtension.js
platform/cli/src/commands/createMode.js

feat: add comment on ohif-cli linking for developemtn

---

extensions/cornerstone/src/commandsModule.js
package.json
platform/core/src/utils/StackManager.js
platform/docs/docs/configuration/configuration.md
platform/docs/docs/configuration/theme-configuration.md
platform/docs/docs/platform/services/config-point-service.md
platform/viewer/package.json
platform/viewer/public/theme/theme.json5
platform/viewer/src/appInit.js
yarn.lock

This change has just the config-point stuff in it, separated out from any use of it.
@sedghi as I said, I was going to split the stuff out.

feat(OHIFv3):Add theme/config-point capability and docs.

---

platform/docs/docs/resources.md
platform/docs/docs/training.md

https://deploy-preview-2654--ohif-platform-docs.netlify.app/training

feat: Add training section to docs

---

platform/docs/docs/resources.md
platform/ui/src/components/Icon/Icon.jsx
yarn.lock

fix: icon styling with className

---

extensions/default/src/DicomLocalDataSource/index.js

fix: dicomLocal dataSource metadata typo

---

extensions/cornerstone/package.json
extensions/dicom-html/package.json
extensions/dicom-rt/package.json
extensions/dicom-segmentation/package.json
extensions/dicom-tag-browser/package.json
extensions/vtk/package.json
platform/core/package.json
platform/viewer/package.json
yarn.lock

Fix https://github.com/OHIF/Viewers/issues/2733

IDC2733: update dcmjs to version 0.19.7

---

extensions/dicom-tag-browser/src/components/DicomTagBrowser.js
platform/core/src/classes/metadata/StudyMetadata.js
platform/core/src/utils/naturalizeSOPClassUID.js
platform/ui/src/components/studyBrowser/Thumbnail.styl
platform/viewer/public/config/default.js
platform/viewer/src/connectedComponents/ConnectedStudyBrowser.js
platform/viewer/src/connectedComponents/Viewer.js
platform/viewer/src/connectedComponents/ViewerMain.js

Fix https://github.com/OHIF/Viewers/issues/2762

Re IDC #2762: fix thumbnail series type for unsupported SOPClassUID 

---

platform/core/src/classes/metadata/StudyMetadata.js

IDC: Fix toolbar error in
https://viewer.imaging.datacommons.cancer.gov/viewer/1.3.6.1.4.1.14519.5.2.1.7695.2311.106039727348255984980483774237

IDC: Fix undefined return in getDerivedDatasets

---

extensions/cornerstone-dicom-sr/src/viewports/OHIFCornerstoneSRViewport.tsx
platform/viewer/cypress/integration/measurement-tracking/OHIFCornerstoneHotkeys.spec.js
platform/viewer/cypress/integration/measurement-tracking/OHIFCornerstoneToolbar.spec.js
platform/viewer/cypress/integration/measurement-tracking/OHIFStudyViewer.spec.js

fix: drag and drop SR into SR and tests

---

extensions/cornerstone-3d/src/commandsModule.js
extensions/cornerstone-3d/src/services/SyncGroupService/SyncGroupService.ts
extensions/cornerstone-3d/src/services/ViewportService/Cornerstone3DViewportService.ts
extensions/cornerstone-3d/src/services/ViewportService/Viewport.ts
extensions/cornerstone-3d/src/utils/JumpPresets.ts
extensions/cornerstone-3d/src/utils/getInterleavedFrames.js
extensions/cornerstone-dicom-sr/src/viewports/OHIFCornerstoneSRViewport.tsx
extensions/measurement-tracking/src/viewports/TrackedCornerstoneViewport.tsx
extensions/tmtv/src/getHangingProtocolModule.js

- Add JumpPreset to OHIF for hangingProtocol
- Some remaining comments from previous PR

fix: Jump presets cs3d

---

extensions/cornerstone/package.json
extensions/cornerstone/src/OHIFCornerstoneViewport.js
extensions/cornerstone/src/components/OHIFCornerstoneViewportOverlay.css
extensions/cornerstone/src/components/OHIFCornerstoneViewportOverlay.js
extensions/cornerstone/src/tools/DICOMSRDisplayTool.js
extensions/cornerstone/src/tools/constants/scoordTypes.js
package.json
platform/core/src/DICOMSR/SCOORD3D/constants/scoordTypes.js
platform/core/src/DICOMSR/SCOORD3D/parseSCOORD3D.js
platform/core/src/DICOMSR/SCOORD3D/utils/getCoordsFromSCOORDOrSCOORD3D.js
platform/core/src/DICOMSR/SCOORD3D/utils/getMeasurements.js
platform/core/src/DICOMSR/SCOORD3D/utils/getRenderableData.js
platform/core/src/DICOMSR/SCOORD3D/utils/processMeasurement.js
platform/core/src/DICOMSR/SCOORD3D/utils/processNonGeometricallyDefinedMeasurement.js
platform/core/src/DICOMSR/SCOORD3D/utils/processTID1410Measurement.js
yarn.lock

Implements https://github.com/OHIF/Viewers/issues/2797
https://user-images.githubusercontent.com/7985338/173571962-68557d9f-499b-4be9-82bc-05799e2f367e.mp4

feat IDC #2797: add support for SR qualitative annotation per instance

---

platform/core/src/DICOMSR/SCOORD3D/parseSCOORD3D.js

fix double parsing of SR qualitative annotations reported in https://github.com/OHIF/Viewers/issues/2797#issuecomment-1167820978

fix: Re IDC2797, fix double parsing of SR qualitative annotations

---

extensions/cornerstone/src/OHIFCornerstoneViewport.js
extensions/cornerstone/src/components/OHIFCornerstoneViewportOverlay.css
extensions/cornerstone/src/components/OHIFCornerstoneViewportOverlay.js
extensions/lesion-tracker/src/components/MeasurementComparisonTable.js
platform/core/src/DICOMSR/SCOORD3D/parseSCOORD3D.js
platform/core/src/DICOMSR/SCOORD3D/utils/addMeasurement.js
platform/core/src/measurements/tools/dicomSRDisplayTool.js
platform/ui/src/components/measurementTable/MeasurementTableItem.js
platform/ui/src/components/measurementTable/MeasurementTableItem.styl
platform/ui/src/components/tableList/TableListItem.js
platform/viewer/src/appExtensions/MeasurementsPanel/ConnectedMeasurementTable.js
platform/viewer/src/connectedComponents/Viewer.js

Re #2797 : improving UI for SR qualitative measurements and bug fixes
https://user-images.githubusercontent.com/7985338/176336239-aa96a951-b2b6-4409-b2b8-a9d1f46ba8bb.mp4

IDC2797: improving UI for SR qualitative measurements and bug fixes

---

platform/cli/src/index.js
platform/cli/templates/extension/dependencies.json

- Just cosmetic changes for ohif-cli: sorting, proper command name on help, ...

fix ohif-cli cosmetic changes for help description

---

platform/docs/docusaurus.config.js
platform/viewer/package.json

fix: package version number

---

extensions/cornerstone/src/initWADOImageLoader.js

fix: typo in accept headers

---

platform/viewer/package.json

fix: product versoin for v32

---

extensions/tmtv/src/Panels/PanelPetSUV.tsx
extensions/tmtv/src/getHangingProtocolModule.js
modes/tmtv/src/index.js
platform/core/src/services/HangingProtocolService/ProtocolEngine.js

TMTV hanging protocol relied on study description which sometimes is missing

fix: hanging protocol for the tmtv

---

platform/core/src/DICOMSR/SCOORD3D/parseSCOORD3D.js
platform/ui/src/components/measurementTable/MeasurementTableItem.js
platform/ui/src/components/tableList/TableList.styl

Fix https://github.com/OHIF/Viewers/issues/2852

Re #2852 IDC: fix parsing of qualitative slice annotation

---

extensions/cornerstone/package.json
extensions/dicom-html/package.json
extensions/dicom-rt/package.json
extensions/dicom-segmentation/package.json
extensions/dicom-tag-browser/package.json
extensions/vtk/package.json
platform/core/package.json
platform/viewer/package.json
yarn.lock

Update dcmjs (https://github.com/dcmjs-org/dcmjs/pull/304) to fix https://github.com/OHIF/Viewers/issues/2869

Re IDC #2869: update dcmjs for fixing eps in nearly equal condition

---

platform/core/src/DICOMSR/SCOORD3D/parseSCOORD3D.js
platform/core/src/classes/metadata/StudyMetadata.js
platform/core/src/studies/retrieveStudyMetadata.test.js
platform/core/src/studies/services/wado/studyInstanceHelpers.js
platform/viewer/src/connectedComponents/Viewer.js

https://github.com/OHIF/Viewers/issues/2849

Re IDC #2849: raise error if dicom request is not conforming with the UID (DICOM UI VR) character repertoire.

---

extensions/cornerstone/src/services/ViewportService/CornerstoneViewportService.ts
extensions/cornerstone/src/services/ViewportService/Viewport.ts
extensions/cornerstone/src/utils/interleaveCenterLoader.ts
extensions/cornerstone/src/utils/interleaveTopToBottom.ts
extensions/default/src/DicomWebDataSource/index.js
extensions/default/src/getHangingProtocolModule.js
extensions/tmtv/src/Panels/PanelPetSUV.tsx
extensions/tmtv/src/commandsModule.js
jest.config.base.js
modes/tmtv/src/index.js
platform/core/src/services/DicomMetadataStore/DicomMetadataStore.js
platform/core/src/services/DicomMetadataStore/StudyMetadata.ts
platform/core/src/services/DicomMetadataStore/createStudyMetadata.js
platform/core/src/services/DisplaySetService/DisplaySet.ts
platform/core/src/services/DisplaySetService/DisplaySetService.js
platform/core/src/services/DisplaySetService/IDisplaySet.ts
platform/core/src/services/HangingProtocolService/HPMatcher.js
platform/core/src/services/HangingProtocolService/HangingProtocolService.test.js
platform/core/src/services/HangingProtocolService/HangingProtocolService.ts
platform/core/src/services/HangingProtocolService/ProtocolEngine.js
platform/core/src/services/HangingProtocolService/lib/validator.js
platform/core/src/services/HangingProtocolService/lib/validator.test.js
platform/docs/docs/platform/services/data/DisplaySetService.md
platform/docs/versioned_docs/version-3.0/platform/services/data/DisplaySetService.md
platform/docs/versioned_docs/version-3.0/platform/services/data/HangingProtocolService.md
platform/docs/versioned_docs/version-3.0/platform/services/pubsub.md
platform/viewer/src/components/ViewportGrid.tsx
platform/viewer/src/routes/Mode/Mode.tsx

Fixes numerous issues causing real hanging protocols to not be definable or not work as expected, or work intermittently.

feat: make hanging protocol work on displaySets instead of series

---

extensions/cornerstone-dicom-sr/package.json
extensions/cornerstone/package.json
extensions/measurement-tracking/package.json
yarn.lock

https://github.com/OHIF/Viewers/issues/2914

fix: bump packages for crosshairs to get fixed

---

extensions/cornerstone/src/Viewport/Overlays/ViewportImageScrollbar.tsx

https://github.com/OHIF/Viewers/issues/2904

fix: imagScrollbar should not stop cine if not playing

---

extensions/tmtv/src/Panels/PanelPetSUV.tsx

fix: total dose unit

---

extensions/cornerstone-dicom-sr/package.json
extensions/cornerstone/package.json
extensions/cornerstone/src/commandsModule.js
extensions/cornerstone/src/index.tsx
extensions/cornerstone/src/services/ViewportService/Viewport.ts
extensions/cornerstone/src/utils/getCornerstoneOrientation.ts
extensions/dicom-pdf/src/index.tsx
extensions/dicom-video/src/index.tsx
extensions/measurement-tracking/package.json
extensions/measurement-tracking/src/index.tsx
platform/core/src/defaults/hotkeyBindings.js
platform/docs/docs/platform/extensions/modules/utility.md
platform/viewer/public/config/aws.js
platform/viewer/public/config/default.js
platform/viewer/public/config/demo.js
platform/viewer/public/config/dicomweb_relative.js
platform/viewer/public/config/e2e.js
platform/viewer/public/config/local_static.js
platform/viewer/public/config/netlify.js
platform/viewer/public/config/public_dicomweb.js
yarn.lock

fix: left right hotkeys and remove non working ones

---

extensions/cornerstone/src/Viewport/OHIFCornerstoneViewport.tsx
modes/longitudinal/src/index.js
platform/ui/src/Types.ts
platform/ui/src/components/StudyBrowser/StudyBrowser.tsx
platform/ui/src/components/Thumbnail/Thumbnail.tsx
platform/ui/src/components/ThumbnailList/ThumbnailList.tsx
platform/ui/src/components/ThumbnailTracked/ThumbnailTracked.tsx
platform/ui/src/components/ViewportActionBar/ViewportActionBar.tsx
platform/ui/src/index.js
platform/viewer/src/components/ViewportGrid.tsx

Fix a number of warnings and add some error messages on extension/mode load failure.
Also tweak the config files to make them consistent with other branches.

fix: various type issues and error handlings

---

platform/core/src/classes/HotkeysManager.js
platform/core/src/utils/loadAndCacheDerivedDisplaySets.js
platform/viewer/src/connectedComponents/ConnectedStudyBrowser.js
platform/viewer/src/connectedComponents/ViewerMain.js

Fix https://github.com/OHIF/Viewers/issues/2919

Re IDC #2919: fix popup notifications behavior

---

extensions/dicom-segmentation/src/index.js
platform/core/src/DICOMSR/SCOORD3D/utils/getReferencedImagesList.js
platform/core/src/DICOMSR/parseDicomStructuredReport.js

Fix https://github.com/OHIF/Viewers/issues/2935

Re IDC #2935: fix parsing of Instance-level qualitative annotations

---

extensions/default/src/Toolbar/ToolbarLayoutSelector.tsx
modes/longitudinal/src/toolbarButtons.js
platform/ui/src/components/LayoutSelector/LayoutSelector.tsx

Adds height/width props to the Layout Selector. Defaults to 3x3
@sedghi 

feat: added row and column props to LayoutSelector

---

Dockerfile

fix: dockerfile to include preinstall

---

Dockerfile

fix: dockerfile typo

---

extensions/default/src/ViewerLayout/index.tsx

Allows for viewer layout to accept a default closed option rather than the first sidebar in array.

feat: added default close option to viewer layout for sidebar ui

---

extensions/measurement-tracking/src/viewports/TrackedCornerstoneViewport.tsx

https://github.com/OHIF/Viewers/issues/2966

fix: cine scrolling was broken when navigating back to studylist

---

extensions/default/src/DicomWebDataSource/index.js
extensions/default/src/Panels/PanelStudyBrowser.tsx
extensions/measurement-tracking/src/panels/PanelStudyBrowserTracking/PanelStudyBrowserTracking.tsx

The wrong call was being made to fetch the study instance uids, so it wasn't possible to fetch two or more instances at once.

fix(OHIFv3):Allow multiple study UIDs in the path.

---

extensions/cornerstone/src/init.js

feat: added useCursors and maxCacheSizeConfig as config params

---

platform/core/src/types/IPubSub.ts

platform\core\src\types\IPubSub.ts 
import 语法错误修复

fixed import error syntax

---

platform/core/src/extensions/ExtensionManager.js
platform/core/src/types/IPubSub.ts
platform/viewer/src/App.tsx
platform/viewer/src/index.js

platform/core/src/extensions/ExtensionManager.js 
line:368

fixed the deprecated syntax:  [lower.substr  --->   lower.substring]

---

extensions/cornerstone/src/Viewport/Overlays/ViewportOrientationMarkers.css
extensions/cornerstone/src/Viewport/Overlays/ViewportOrientationMarkers.tsx
extensions/cornerstone/src/Viewport/Overlays/ViewportOverlay.tsx
extensions/cornerstone/src/init.tsx
extensions/default/src/Toolbar/ToolbarDivider.tsx
platform/ui/package.json
platform/ui/src/assets/icons/notifications-error.svg
platform/ui/src/assets/icons/notifications-info.svg
platform/ui/src/assets/icons/notifications-success.svg
platform/ui/src/assets/icons/notifications-warning.svg
platform/ui/src/components/Icon/getIcon.js
platform/ui/src/components/Snackbar/Snackbar.css
platform/ui/src/components/Snackbar/SnackbarContainer.tsx
platform/ui/src/components/Snackbar/SnackbarItem.tsx
platform/ui/src/components/SplitButton/SplitButton.tsx
platform/ui/src/components/ViewportOverlay/ViewportOverlay.tsx
platform/viewer/package.json
yarn.lock

Upgrade tailwind css
Enhanced hover states for toolbar 
Enhanced notifications 
CC: Thanks to @dan-rukas

Fix/more UI fixes

---

platform/ui/src/components/Button/Button.tsx
platform/ui/src/components/StudyBrowser/StudyBrowser.tsx

This changes the text color to the actual specified text color, and specifies the color as black for the active tab, making the text visible more consistently.

Fix the button text colour to be more readable

---

extensions/cornerstone-dicom-sr/package.json
extensions/cornerstone/package.json
extensions/cornerstone/src/services/ViewportService/CornerstoneViewportService.ts
extensions/measurement-tracking/package.json
platform/docs/docs/configuration/url.md

fix sr module and add docs

---

.docker/Viewer-v3.x/default.conf.template
extensions/cornerstone-dicom-sr/package.json
extensions/cornerstone/package.json
extensions/cornerstone/src/init.tsx
extensions/measurement-tracking/package.json
extensions/measurement-tracking/src/viewports/TrackedCornerstoneViewport.tsx
modes/tmtv/src/utils/setFusionActiveVolume.js
platform/core/src/utils/metadataProvider/fetchPaletteColorLookupTableData.js
platform/ui/src/components/Button/Button.tsx
platform/ui/src/components/StudyListPagination/StudyListPagination.tsx
platform/viewer/src/routes/Debug.tsx
platform/viewer/src/routes/index.tsx
yarn.lock

Bugs fixed
- https://github.com/OHIF/Viewers/issues/3050
- https://github.com/OHIF/Viewers/issues/3039
- https://github.com/OHIF/Viewers/issues/3043
- https://github.com/OHIF/Viewers/issues/3024
Add /debug to add additional info for debugging (currently limited info)
- https://github.com/OHIF/Viewers/issues/3049

fix: various bugs with v33 re cine and colors

---

extensions/cornerstone/package.json
extensions/dicom-html/package.json
extensions/dicom-rt/package.json
extensions/dicom-segmentation/package.json
extensions/dicom-tag-browser/package.json
extensions/vtk/package.json
platform/core/package.json
platform/viewer/package.json
yarn.lock

Update dcmjs (https://github.com/dcmjs-org/dcmjs/pull/332) to fix https://github.com/OHIF/Viewers/issues/3047

Re IDC #3047: update variable name for frame index

---

extensions/cornerstone/src/getHangingProtocolModule.ts
extensions/cornerstone/src/init.tsx
extensions/cornerstone/src/services/ViewportService/CornerstoneViewportService.ts
extensions/cornerstone/src/utils/getNthFrames.js
extensions/cornerstone/src/utils/interleave.js
extensions/cornerstone/src/utils/nthLoader.ts
platform/docs/docs/deployment/index.md
platform/docs/docs/platform/extensions/modules/hpModule.md

Add an nth image loader, making the appearance of volumes much nicer when they are large by creating some detail everywhere immediately.

feat(imageLoader):Add an nth image loader strategy (#10)

---

extensions/cornerstone/src/utils/mpr/toggleMPRHangingProtocol.ts
extensions/default/src/Toolbar/Toolbar.tsx
extensions/default/src/Toolbar/ToolbarLayoutSelector.tsx
extensions/default/src/getToolbarModule.tsx
modes/longitudinal/src/index.js
modes/longitudinal/src/toolbarButtons.js
platform/core/src/services/ToolBarService/ToolBarService.ts
platform/docs/docs/platform/extensions/modules/toolbar.md
platform/ui/src/components/IconButton/IconButton.tsx
platform/ui/src/components/SplitButton/SplitButton.tsx
platform/ui/src/components/ToolbarButton/ToolbarButton.tsx

The primary button will always be the layout grid selector and the MPR toggle is in the drop down menu. This is the first step to later adding other (e.g. 3D) layout HPs to the menu.
Summary of changes/fixes:
- SplitButton now allows for its primary button to be any button component specified by a UI type.
- SplitButton passes a className to its primary button component to dictate how it should be rendered based on its active/toggle status, hovering, menu visibility etc.
- The default menu item renderer for the SplitButton, renders acitve toggle items correctly.
- Items/buttons in the toolbar are now all the correct and same size.
- Added ToolbarService.getButtonComponentForUIType to fetch a button component for a given UI type.
- Spacing between toolbar items is now done at the Toolbar …

fix: rework inconsistencies in split button implementation

---

extensions/cornerstone-dicom-sr/package.json
extensions/cornerstone/package.json
extensions/cornerstone/src/init.tsx
extensions/cornerstone/src/services/CornerstoneCacheService/CornerstoneCacheService.ts
extensions/measurement-tracking/package.json
platform/core/src/classes/MetadataProvider.js
platform/docs/docs/configuration/dataSources/static-files.md
yarn.lock

feat: use wadors instead of streaming wadors for volume loading

---

extensions/cornerstone-dicom-sr/package.json
extensions/cornerstone/package.json
extensions/measurement-tracking/package.json
platform/viewer/src/routes/index.tsx

github issue #3051
Remove default route from baked in routes if showStudyList is false.
Links
fixes https://github.com/OHIF/Viewers/issues/3051

fix: app-config settings are ignored in OHIF v3

---

extensions/cornerstone/src/initMeasurementService.js
extensions/cornerstone/src/utils/measurementServiceMappings/Bidirectional.js
extensions/cornerstone/src/utils/measurementServiceMappings/EllipticalROI.js
extensions/cornerstone/src/utils/measurementServiceMappings/Length.js
extensions/default/src/Panels/PanelMeasurementTable.tsx
extensions/measurement-tracking/src/panels/PanelMeasurementTableTracking/index.tsx
platform/core/src/services/MeasurementService/MeasurementService.js
platform/core/src/services/MeasurementService/MeasurementService.test.js

Added selected flag to each OHIF measurement.
Listening to CS3D ANNOTATION_SELECTION_CHANGE to keep the selected flag in sync.

fix: Clicking on measurement should highlight the measurement row in the measurement panel OHIF-433

---

platform/core/src/services/HangingProtocolService/HangingProtocolService.test.js
platform/core/src/services/HangingProtocolService/HangingProtocolService.ts
platform/core/src/types/HangingProtocol.ts
platform/docs/docs/platform/services/data/HangingProtocolService.md
yarn.lock

In early versions of OHIF v3, there used to be what was called hanging protocol generators, but there were removed when the team worked on MPR. 
This PR aims to add generators back.
Handle in HangingProtocolService the fact a protocol module can be a function that is called to return a protocol.
- Unit tests were added
- Create a custom HP in a mode and run it
etc.)

feat(HangingProtocol): add protocol generator back

---

platform/core/src/classes/MetadataProvider.js

Adds voiLUTFunction to the MetadataProvider VOI_LUT_MODULE

feat(metadata): added voiLUTFunction to MetadataProvider

---

extensions/cornerstone-dicom-sr/package.json
extensions/cornerstone/package.json
extensions/measurement-tracking/package.json
modes/basic-test-mode/.webpack/webpack.dev.js
modes/basic-test-mode/.webpack/webpack.prod.js
modes/basic-test-mode/LICENSE
modes/basic-test-mode/README.md
modes/basic-test-mode/babel.config.js
modes/basic-test-mode/package.json
modes/basic-test-mode/src/id.js
modes/basic-test-mode/src/index.js
modes/basic-test-mode/src/initToolGroups.js
modes/basic-test-mode/src/toolbarButtons.js
modes/longitudinal/src/initToolGroups.js
package.json
platform/viewer/netlify.toml
platform/viewer/public/config/default.js
yarn.lock

It bump packages to fix seg rendering
+ it adds a test mode which later will get used in cypress to test hanging protocols + other features inside a mode
+ Changing the numberOfWorkers from 4 to 3 since some windows systems have issues with more than 3 web workers
+ Add ReferenceLines to basic mode

fix(Segmentation): bump packages to fix segmentation rendering

---

platform/viewer/public/config/default.js
tsconfig.json

fix(typo): whiteLabelling to whiteLabeling

---

platform/core/src/classes/Hotkey.ts
platform/core/src/classes/HotkeysManager.ts
platform/core/src/extensions/ExtensionManager.test.js
platform/core/src/extensions/ExtensionManager.ts
platform/core/src/extensions/index.js
platform/core/src/types/AppConfig.ts
platform/core/src/types/Command.ts
platform/core/src/types/Consumer.ts
platform/core/src/types/Services.ts
platform/core/src/types/StudyMetadata.ts
platform/core/src/types/index.ts

Make the hotkey manager not save the default values.
Also, convert it to typescript and export some of the types for the hotkeys.

fix(hotkeys): fix the hotkey manager to not save the defaults

---

extensions/cornerstone/src/commandsModule.ts
extensions/cornerstone/src/init.tsx
extensions/cornerstone/src/initWADOImageLoader.js
extensions/cornerstone/src/services/CornerstoneCacheService/CornerstoneCacheService.ts
extensions/default/src/DicomWebDataSource/index.js
extensions/default/src/commandsModule.js
platform/core/src/extensions/ExtensionManager.ts
platform/core/src/types/Services.ts
platform/viewer/src/App.tsx
platform/viewer/src/routes/index.tsx
platform/viewer/src/utils/OpenIdConnectRoutes.tsx

Missed renaming UIModalService and UserAuthenticationService on the first round of renames.

fix(typescript): Missed renames UIModalService and UserAuthenticationService

---

platform/core/src/services/_shared/pubSubServiceInterface.js

When running jest on my extension, an error appears inside one of the OHIF v3-stable files:
`Cannot find module '../../Types' from 'external/ohif/platform/core/src/services/_shared/pubSubServiceInterface.js'`
The correct path should be `../../types`, however this PR simply removes that import, since it is not used anywhere in the file.
Import is removed, no more import error in the file, extension tests now pass.
- Inside an extension, have a test that imports DicomMetadataStore
`import { DicomMetadataStore } from '@ohif/core';` 
- Run test using jest
- Test should pass, no import error coming from `pubSubServiceInterface.js`
etc.)
[script]: …

Fix(import error): Remove unused Types import from pubSubServiceInterface

---

README.md

add acknowledgment for BrowserStack Percy framework

docs: add percy acknowledgment

---

platform/i18n/src/locales/en-US/AboutModal.json
platform/i18n/src/locales/en-US/SidePanel.json
platform/i18n/src/locales/en-US/StudyBrowser.json
platform/i18n/src/locales/en-US/StudyList.json
platform/i18n/src/locales/en-US/index.js
platform/i18n/src/locales/es/AboutModal.json
platform/i18n/src/locales/es/DatePicker.json
platform/i18n/src/locales/es/SidePanel.json
platform/i18n/src/locales/es/StudyBrowser.json
platform/i18n/src/locales/es/StudyList.json
platform/i18n/src/locales/es/ViewportDownloadForm.json
platform/i18n/src/locales/es/index.js
platform/ui/src/components/SidePanel/SidePanel.tsx
platform/ui/src/components/StudyListFilter/StudyListFilter.tsx
platform/ui/src/components/StudyListPagination/StudyListPagination.tsx
platform/viewer/src/routes/WorkList/filtersMeta.js

There are some translations errors in StudyList and StudyBrowser, I have detected when set the viewer in Spanish translations. There are some errors in spanish translations. #3169 
etc.)

fix(translation): errors in StudyList and StudyBrowser for es

---

extensions/cornerstone-dicom-sr/package.json
extensions/cornerstone-dicom-sr/src/tools/DICOMSRDisplayTool.ts
extensions/cornerstone-dicom-sr/src/utils/addMeasurement.ts
extensions/cornerstone-dicom-sr/src/utils/getFilteredCornerstoneToolState.ts
extensions/cornerstone/package.json
extensions/cornerstone/src/initMeasurementService.js
extensions/cornerstone/src/services/ViewportService/CornerstoneViewportService.ts
extensions/cornerstone/src/utils/measurementServiceMappings/utils/selection.ts
extensions/measurement-tracking/package.json
extensions/tmtv/src/commandsModule.js
platform/viewer/cypress/integration/volume/MPR.spec.js
yarn.lock

etc.)
- [] "OS: 
- [] "Browser:

feat(measurementService): use the new api for annotation manager in cs3d

---

platform/ui/src/components/StudyListFilter/StudyListFilter.tsx
platform/viewer/src/routes/WorkList/WorkList.tsx

Worklist had a layout shift
- Fixed the layout shift when the table is interacted with 
- Have the worklist appear but don't zoom out a lot, make is so that an open of a table row makes it go scroll
- Notice the layout shift in the old version but not this PR
etc.)

fix(ui): worklist had layout shift

---

extensions/tmtv/src/Panels/PanelROIThresholdSegmentation/PanelROIThresholdSegmentation.tsx
extensions/tmtv/src/Panels/PanelROIThresholdSegmentation/ROIThresholdConfiguration.tsx
extensions/tmtv/src/commandsModule.js
extensions/tmtv/src/utils/getThresholdValue.ts
platform/viewer/netlify.toml

Adds CT ranges to be used for thresholding
in the ROI threshold configuration it adds the CT lower and upper ranges to be used for thresholding
- Open TMTV
- Open configuration panel 
- Select the Range
- See CT is added
etc.)

feat(tmtv): add ct ranges for thresholding

---

extensions/tmtv/src/Panels/PanelROIThresholdSegmentation/PanelROIThresholdSegmentation.tsx
extensions/tmtv/src/utils/getThresholdValue.ts

fix(tmtv): there should be no CT range for max suv settings

---

platform/docs/docs/platform/extensions/modules/sop-class-handler.md

i don't know if it was intentional but should their be a closing square brackets for sopClassUids
etc.)
- [] "OS: 
- [] "Browser:

docs: Update sop-class-handler md

---

package.json
yarn.lock

- Prototype Pollution in minimist #219

dependabot security updates

---

docs/latest/package.json
docs/latest/yarn.lock
package.json
yarn.lock

https://github.com/OHIF/Viewers/security/dependabot/222[Critical](https://github.com/OHIF/Viewers/security/dependabot?q=is%3Aopen+severity%3Acritical)
#222 opened 10 minutes ago • Detected in minimist (npm) • docs/latest/yarn.lock
https://github.com/OHIF/Viewers/security/dependabot/218[Critical](https://github.com/OHIF/Viewers/security/dependabot?q=is%3Aopen+severity%3Acritical)
#218 opened 3 weeks ago • Detected in minimist (npm) • docs/latest/yarn.lock
https://github.com/OHIF/Viewers/security/dependabot/210[Critical](https://github.com/OHIF/Viewers/security/dependabot?q=is%3Aopen+severity%3Acritical)
#210 opened 3 months ago • Detected in flat (npm) • yarn.lock
https://github.com/OHIF/Viewers/security/dependabot/199[Critical](https://github.com/OHIF/Viewers/security/dependabot?q=is%3Aope …

Bump libs version to address dependabot [critical] security alerts

---

extensions/default/src/Panels/PanelStudyBrowser.tsx
extensions/default/src/commandsModule.ts
package.json
platform/ui/package.json
platform/ui/src/contextProviders/getPresentationIds.ts
yarn.lock

tmtv mode was not displaying after the HP changes.
A meaningless message was shown on drag and drop and on initial HP apply
Fixed a wrong variable name in the getPresentationIds causing an issue during TMTV apply.
Removed the error text from the double click/drag and drop display set messages, as well as from toggle handing protocol.
See the message when trying to turn on MPR on a display set not supporting it (note, the message is not the original one,
which was wrong half the time, and required custom toggle logic)
View a study in TMTV mode
See the messasge when dragging a DS into the MPR mode that isn't MPRable.
- [] My code has been well-documented (function documentation, …

fix(tmtv): hanging protocol state sync

---

extensions/cornerstone/package.json
extensions/default/src/CustomizeableContextMenu/ContextMenuItemsBuilder.ts
extensions/default/src/CustomizeableContextMenu/types.ts
extensions/default/src/commandsModule.ts
extensions/default/src/getCustomizationModule.tsx
extensions/test-extension/src/custom-context-menu/contextMenuCodeItem.ts
extensions/test-extension/src/custom-context-menu/findingsContextMenu.ts
platform/core/package.json
platform/docs/docs/platform/services/ui/customization-service.md
platform/ui/src/assets/icons/chevron-menu.svg
platform/ui/src/components/ContextMenu/ContextMenu.tsx
platform/ui/src/components/Icon/getIcon.js
platform/ui/src/types/ContextMenuItem.ts
platform/viewer/package.json
yarn.lock

Messed up a PR push with mostly documentation, plus a small UI change, just including the final PR docs changes and the GUI change.
etc.)
- [] "OS: 
- [] "Browser:

fix(contextMenu): fixes for context menu icon

---

modes/basic-test-mode/src/index.js
platform/core/src/classes/HotkeysManager.ts
platform/docs/docs/platform/modes/index.md
platform/viewer/src/routes/Mode/Mode.tsx

Hotkeys are stored incorrectly on a lot of people's machines.  This PR adds the ability
to use named hotkeys, as specified by hotkeyName in the mode object.
That also allows different modes to use different hotkey sets.
Finally, to allow updating of hotkeys without needing to manually clear them, the
default name has been changed to add a version number to it.
Using the basic test mode, set a custom hotkey
Test your change
View the default longitudinal mode, test that the hotkey change is NOT effective
Go back into basic test mode, check that the hotkey is effective.
etc.)
- [] The documentation page has …

fix: Store hotkeys to specified name

---

extensions/default/src/DicomWebDataSource/index.js
extensions/default/src/DicomWebDataSource/utils/StaticWadoClient.ts
extensions/default/src/getHangingProtocolModule.js
modes/basic-test-mode/src/index.js
platform/core/src/classes/ImageSet.js
platform/core/src/services/HangingProtocolService/HangingProtocolService.ts
platform/core/src/services/HangingProtocolService/isDisplaySetFromUrl.ts
platform/core/src/types/HangingProtocol.ts
platform/core/src/utils/index.js
platform/core/src/utils/index.test.js
platform/core/src/utils/splitComma.ts
platform/docs/docs/configuration/url.md
platform/docs/docs/platform/services/data/HangingProtocolService.md
platform/viewer/cypress/integration/customization/HangingProtocol.spec.js
platform/viewer/src/components/ViewportGrid.tsx
platform/viewer/src/routes/Mode/Mode.tsx

In OHIF v2, it was possible to navigate to a specific series or SOP UID by providing URL parameters.  This is misisng in
v3 till now - this change adds it.
A URL like: 
http://localhost:3000/basic-test?StudyInstanceUIDs=1.3.6.1.4.1.25403.345050719074.3824.20170125113417.1&displaySet.SeriesInstanceUID=1.3.6.1.4.1.25403.345050719074.3824.20170125113545.4&displaySet.SOPInstanceUID=1.3.6.1.4.1.25403.345050719074.3824.20170125113558.2
can be used to navigate to the 101's instance in the third series.
Use the above URL to navigate to the given position.  Try without the SOP instance or without the series to navigate to specified locations. (identical without series, image 1 without SOP)
- …

feat(URL): add param for initial series and sop uids to display

---

extensions/cornerstone/src/initMeasurementService.js
extensions/cornerstone/src/services/CornerstoneCacheService/CornerstoneCacheService.ts

Suppress console error in the case the annotation is a Crosshair

fix(crosshairs): suppressed error for crosshair

---

platform/viewer/src/appInit.js

Supporting the async function in the config enables backend implementation to return OHIF config; this makes it simpler to integrate with a custom backend that will provide data to OHIF. This is a simple change, yet it enables new use cases.
Straightforward change to support the async load of config
I tested it by changing the e2e configuration config to look like the following and test the features.
```javascript
window.config = () => Promise.resolve({
routerBasename: '/',
extensions: [],
modes: ['@ohif/mode-test'],
showStudyList: true,
// below flag is for performance reasons, but it might not work for all servers
omitQuotationForMultipartRequest: true,
maxNumberOfWebWorkers: 3,
showWarningMessageForCrossOrigin: false,
showCPUFallbackMessage: false,
strictZSpacingForVolumeViewport: …
```

feat(App): support async config function

---

extensions/tmtv/src/Panels/PanelROIThresholdSegmentation/ROIThresholdConfiguration.tsx

When value under "Percentage of Max SUV" is updated, update does not go through causing any attempts to run ROI Threshold tool to result in the entire area being segmented.
Root cause due to format of payload in dispatch for setWeight update.
Fixes #3246 
ROIThresholdConfiguration.tsx fixed payload to expected format (encapsulate value within {weight: value}.
1. Open image set with CT+PT in TMTV mode
2. Click "New Label" button on right panel
3. Select Rectangle ROI Threshold Tool, create box within axial PT
4. Hit Run
-> Should threshold properly
5. Open ROI Threshold Configuration
6. Change value under "Percentage of Max SUV"
7. Should update segmented region under ROI
- [] My …

fix(ROIThreshold): fix setWeight not updating properly for ROIThreshold panel

---

platform/ui/src/components/Input/Input.tsx
platform/ui/src/components/Input/__stories__/input.stories.mdx
platform/ui/src/components/InputNumber/InputNumber.css
platform/ui/src/components/InputNumber/InputNumber.tsx
platform/ui/src/components/InputText/InputText.tsx
platform/ui/tailwind.config.js
platform/viewer/tailwind.config.js

Update the border colors of input fields to the corresponding values according to the OHIF color scheme.
Modified the primary color values used by text input components and restructured the classes used for inputNumber.
Changes can be tested through storybook.
etc.)

fix(ui): updated input fields to match new color scheme

---

nx.json

chore(lerna): add lerna caching to build and tests

---

extensions/cornerstone/src/services/ViewportService/Viewport.ts

After loading SEG, measurements cannot be jumped to or edited from the side panel.
Simple addition of a missed reference to a field in the code.
1. Load a study with segmentation.
2. Add a markup to the series referenced by the segmentation.
3. Load the segmentation.
4. Edit the markup or jump to it from the side, measurements' panel.
etc.)

fix(Measurements): edit measurement while SEG loaded

---

platform/ui/src/components/Snackbar/SnackbarItem.tsx

In the `SnackbarItem` component...
- made the close button part of its parent flex layout
- changed the close button's positioning to `relative`
- added appropriate margins and padding
And voila...
Perform various operations that would show the popup notification:
- start MPR with a non-reconstructable series
- save a Measurement tracking report
- ...
etc.)

fix(UI) - fixed the spacing and positioning of the close button in the SnackbarItem component

---

platform/ui/src/components/Select/Select.css
platform/ui/src/components/Select/Select.tsx
platform/ui/src/components/StudyListPagination/StudyListPagination.tsx
platform/viewer/src/routes/WorkList/WorkList.tsx

The results per page select menu on the worklist page was truncated/clipped and had incorrect look-and-feel. In particular the background and foreground colours were not correct.
Placed the results per page component in a flex column layout and let it grow. This gives space for it to open down if the space is available.
Changed the css for the OHIF `Select` component to be more general. Now all `Select` components should look similar.
Try using the results per page component and ensure it is not clipped - before and after opening. Its look-and-feel should match other `Select` components (e.g. the Modality search list filter select widget).
etc.) …

fix(UI): fixed results per page select menu

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/feature-request.yml

etc.)
- [] "OS: 
- [] "Browser:

chore(github): styling for issues forms

---

modes/longitudinal/src/index.js
platform/core/src/utils/metadataProvider/fetchPaletteColorLookupTableData.js
platform/docs/docs/configuration/url.md

etc.)
- [] "OS: 
- [] "Browser:

fix(thumbnail): it was commented out by mistake

---

extensions/dicom-microscopy/src/utils/cleanDenaturalizedDataset.ts
platform/viewer/public/config/demo.js
platform/viewer/public/config/e2e.js
platform/viewer/public/config/multiple.js
platform/viewer/public/config/netlify.js
platform/viewer/public/config/public_dicomweb.js

etc.)
- [] "OS: 
- [] "Browser:

chore(demo): update demo data

---

.circleci/config.yml
increaseEventEmitterLimit.mjs
platform/docs/docs/migration-guide.md
publish.mjs
version.mjs

separate version from build

---

.circleci/config.yml

chore(build): call script from current directory

---

.circleci/config.yml
package.json

chore(build): try to reduce parallel builds

---

.circleci/config.yml
increaseEventEmitterLimit.mjs

chore(build): try to buld docker files

---

.circleci/config.yml
extensions/cornerstone-dicom-rt/package.json
extensions/cornerstone-dicom-seg/package.json
extensions/cornerstone-dicom-sr/package.json
extensions/cornerstone/package.json
extensions/default/package.json
extensions/dicom-microscopy/package.json
extensions/dicom-pdf/package.json
extensions/dicom-video/package.json
extensions/measurement-tracking/package.json
extensions/test-extension/package.json
modes/microscopy/package.json
package.json

chore(build): separate half and half for publish

---

.circleci/config.yml
.npmrc
publish-package.mjs
publish-version.mjs
version.mjs

chore(build): separate version from build

---

.circleci/config.yml

chore(build): persiste the workspace

---

.circleci/config.yml

chore(build): attach to workspace

---

extensions/cornerstone/src/services/SegmentationService/SegmentationService.ts

chore(build): update the beta version [BUMP BETA]

---

README.md
platform/docs/docs/README.md

docs(readme): correct the docs images

---

modes/tmtv/src/initToolGroups.js

fix jumpToClick Tool for TMTV mode

---

platform/cli/templates/extension/babel.config.js
platform/cli/templates/extension/dependencies.json

Made some changes to extension template for CLI to fix babel version conflicts.

fix cli extension template

---

README.md

fixes a typo in the readme file

fixes a README.md typo

---

package.json
yarn.lock

chore(prettier): update prettier to fix publish

---

extensions/default/src/ViewerLayout/ViewerHeader.tsx
extensions/default/src/ViewerLayout/index.tsx
platform/app/src/routes/Mode/Mode.tsx
platform/app/src/routes/WorkList/WorkList.tsx

fixes #3598 
Hotkeys were not getting restored after refresh. 
There were too many re-renderings happening because of modals and useTranslation
Fixes the re-renderings as shown below by refactoring and not changing language if the same
Current behaviour 
https://github.com/OHIF/Viewers/assets/7490180/864562db-997d-4178-9a08-dd657a976edd
After this PR
- No re-rendering -> No `search for studies` 
- Changed hotkeys in the user preferences should be preserved after refresh
- the app should feel faster after save preferences (since there is no re-renderings)
etc.)
- [] The documentation page has been updated …

fix(hotkeys): preserve hotkeys if changed, and reduce re-rendering

---

.prettierrc

chore(prettier): fix end-of-line warnings

---

extensions/default/package.json
yarn.lock

See #3587. A zero patient weight should be treated just like a non-existent or blank patient weight and in turn the SUV calculation should NOT per performed.
Updated cornerstone calculate-suv library.
Test using the steps and information in #3587.
etc.)

fix(suv): import calculate-suv library version that prevents SUV calculation for a zero PatientWeight

---

platform/core/src/services/HangingProtocolService/HangingProtocolService.ts

Fixes #3665 
Return the original/raw hanging protocol when fetching and preserving the current active protocol.
See #3665
etc.)

fix(mpr): Return the original/raw hanging protocol when fetching and preserving the current active protocol.

---

modes/segmentation/package.json
platform/app/cypress/integration/measurement-tracking/OHIFContextMenuCustomization.spec.js
platform/app/cypress/integration/measurement-tracking/OHIFMeasurementPanel.spec.js

chore(build): try to publish to npm again

---

README.md
extensions/cornerstone/src/services/SegmentationService/SegmentationService.ts

- chore(build): try to build demo and docs
- feat(app): change ohif viewer to ohif app (#3451)
- chore(version): version.json [skip ci]
- chore(version): Update package versions [skip ci]
- chore(version): version.json [skip ci]
- chore(version): Update package versions [skip ci]
- dont use shared array buffer in not secure
etc.)
- [] OS: 
- [] Browser:
[script]: …

fix(segmentation): do not use SAB if not specified

---

platform/i18n/src/locales/en-US/Messages.json
platform/ui/src/components/DisplaySetMessageListTooltip/DisplaySetMessageListTooltip.tsx

fix(i18n): display set(s) are two words for English messages

---

extensions/default/src/getDisplaySetMessages.ts

fix(display messages): broken after timings

---

package.json

fix(recipes): package.json script orthanc:up docker-compose path

---

platform/core/src/services/MeasurementService/MeasurementService.test.js
platform/core/src/services/MeasurementService/MeasurementService.ts

Fixes #3014 
Fixed logic error.
Unit test added.
etc.)

fix(measurement service): Implemented correct check of schema keys in _isValidMeasurment.

---

extensions/cornerstone/src/init.tsx

Run core error handler for failed image requests since image loader requests are made outside dicomweb-client.
Failed Image requests were not triggering the config error handler.
etc.)
- [N/A] The documentation page has been updated as necessary for any public API

fix: 🐛 Run error handler for failed image requests

---

platform/docs/docs/development/continuous-integration.md
platform/docs/docs/development/contributing.md
platform/docs/docs/development/link.md
platform/docs/docs/development/ohif-cli.md
platform/docs/docs/development/our-process.md
platform/docs/docs/development/testing.md
platform/docs/docs/development/video-tutorials.md

Added training videos for creating, linking, publishing and adding published modes and extensions with the OHIF CLI tool.
Review the docs added.
etc.)

feat(docs): Added various training videos to support the OHIF CLI tools

---

platform/core/src/services/DicomMetadataStore/DicomMetadataStore.ts

Allowing broadcast listeners from event SERIES_ADDED from the DicomMetadataStore to have information about the series they just added. This information can be useful in some cases.
No visible changes.
Tested manually.
etc.)

feat(events): broadcast series summary metadata

---

platform/core/src/services/CineService/CineService.ts

Addresses OHIF issue #3800
When a mode exits, set cine disabled.
See #3800
etc.)

fix(cine): Set cine disabled on mode exit.

---

extensions/cornerstone-dicom-sr/src/commandsModule.js
extensions/cornerstone-dicom-sr/src/getSopClassHandlerModule.ts
extensions/cornerstone-dicom-sr/src/tools/DICOMSRDisplayTool.ts
extensions/cornerstone-dicom-sr/src/utils/addMeasurement.ts
extensions/cornerstone-dicom-sr/src/utils/hydrateStructuredReport.js
extensions/cornerstone/src/utils/measurementServiceMappings/Angle.ts
extensions/cornerstone/src/utils/measurementServiceMappings/ArrowAnnotate.ts
extensions/cornerstone/src/utils/measurementServiceMappings/Bidirectional.ts
extensions/cornerstone/src/utils/measurementServiceMappings/CircleROI.ts
extensions/cornerstone/src/utils/measurementServiceMappings/CobbAngle.ts
extensions/cornerstone/src/utils/measurementServiceMappings/EllipticalROI.ts
extensions/cornerstone/src/utils/measurementServiceMappings/Length.ts
extensions/cornerstone/src/utils/measurementServiceMappings/PlanarFreehandROI.ts
extensions/cornerstone/src/utils/measurementServiceMappings/RectangleROI.ts
extensions/default/src/DicomWebDataSource/index.js
extensions/default/src/DicomWebProxyDataSource/index.js
extensions/default/src/MergeDataSource/index.ts
platform/core/src/extensions/ExtensionManager.ts
platform/core/src/services/MeasurementService/MeasurementService.ts

In an effort to save and load measurement textBoxes for a customer I realized there's no seamless way of saving and loading private tags of SRs with OHIF as of now. This PR enables that by making use of the customizationService.
There are no behavior or visual changes, except if you implement a customization.
Manual and functional testing.
etc.)

feat(customizationService): Enable saving and loading of private tags in SRs 

---

modes/tmtv/src/initToolGroups.js

should fix : https://github.com/OHIF/Viewers/issues/3874
etc.)
- [] OS: 
- [] Browser:

fix: convert radian to degree value for mip rotation

---

platform/docs/docs/deployment/user-account-control.md

Updated the path to the correct OpenResty-Orthanc-Keycloak directory
etc.)
- [] OS: 
- [] Browser:

docs: Update user-account-control.md

---

platform/docs/docs/development/architecture.md

Changed the 'viewer' element in the project structure tree to 'app'
etc.)
- [] OS: 
- [] Browser:

docs: Update architecture.md

---

platform/docs/docs/configuration/dataSources/introduction.md

minor uppercase typo
Small typo in the doc
Fix the typo
N/A
docs(Readme): fix the typo
etc.)
N/A

docs: Typo

---

modes/longitudinal/src/index.js
platform/cli/templates/mode/src/index.tsx

A previous toolbar refactoring moved a couple tools from toolbars.ts to a separate file moreTools.ts But that new file was not exported and therefore that change broke the CLI template for mode creation
As stated in #3876, the steps to reproduce are:
- `yarn run cli create-mode`
- `yarn run cli link-mode <path to the mode you just created>`
- `yarn run dev`
- view the new mode
etc.)

fix(cli): mode creation template (#3876)

---

platform/app/.recipes/OpenResty-Orthanc/docker-compose.yml
platform/docs/docs/deployment/nginx--image-archive.md

Within the `OpenResty-Orthanc` recipe, I enabled Orthanc's DIMSE port for easier loading of DICOM studies.
Small change in `docker-compose.yml`
etc.)

docker: Enabled Orthanc's DIMSE port for easier loading of DICOM studies in OpenResty-Orthanc Recipe

---

extensions/cornerstone/src/utils/getCornerstoneBlendMode.ts

These blend modes are missing and have support from cornerstones js; one may want to compare MIP and MINIP reports in a single HP, and today, if you try to add an HP with MINIP, you get an error.
This is a small change where we proxy the values to cornerstone types and fix our needs.
E.g:  in the next hanging protocol, I show 3 viewports, each one with a different blend mode
```javascript
export const mipMinIp = {
id: 'mipMinIp',
locked: true,
name: 'Mip MinIp',
icon: 'layout-advanced-axial-primary',
isPreset: true,
availableTo: {},
editableBy: {},
protocolMatchingRules: [],
imageLoadStrategy: 'interleaveCenter',
displaySetSelectors: {
mprDisplaySet: {
seriesMatchingRules: [
{
weight: 1,
attribute: 'isReconstructable',
constraint: {
equals: {
value: true,
},
},
required: true,
},
],
},
}, …
```

fix(vewport): Add missing blendmodes from cornerstonejs

---

README.md
platform/docs/docusaurus.config.js

chore(version): move to the next beta version [BUMP BETA]

---

platform/ui/src/components/ListMenu/ListMenu.tsx

List menu was not responsive to lower screen height values. The user could not see all tools. This change updates the component so it overflows using scroll.
etc.)
N/A

fix: 🐛 Overflow scroll list menu based on screen hight

---

.circleci/config.yml
version.mjs

chore: Update CircleCI workflow to include approval step before NPM publish for release branches

---

extensions/cornerstone/src/services/CornerstoneCacheService/CornerstoneCacheService.ts
extensions/default/src/getPTImageIdInstanceMetadata.ts

The stack invalidation was incorrect; we never truly attempted it. This pull request will resolve the stack invalidation issue.
I tested the volume invalidation to check if the SUV changes, and it worked as expected. However, I'm unsure about the necessary steps for tmtv. https://github.com/OHIF/Viewers/issues/3805
Here are the recordings.
**For Stack**
https://github.com/OHIF/Viewers/assets/7490180/7e9c9531-1c70-4c45-b9c7-f9b37b823059
**For Volume**
https://github.com/OHIF/Viewers/assets/7490180/ddacdd03-776a-4eac-8599-7829f1d52bdd
etc.)
- [] The documentation page has been updated as necessary for any …

fix(stack-invalidation): Resolve stack invalidation if metadata invalidated

---

extensions/cornerstone/src/init.tsx

set renderFill to false for contour

fix(contour): set renderFill to false for contour

---

platform/app/src/routes/DataSourceWrapper.tsx
platform/app/src/routes/WorkList/WorkList.tsx

Fixes issue https://github.com/OHIF/Viewers/issues/4176

fix(queryparam): set all query params to lowercase by default

---

extensions/cornerstone-dicom-seg/src/commandsModule.ts
extensions/cornerstone-dicom-seg/src/utils/hydrationUtils.ts
extensions/default/src/getHangingProtocolModule.js

fix: segmentation creation and segmentation mode viewport rendering

---

extensions/cornerstone/src/index.tsx

Adding extra exports to the cornerstone extensions that might be useful in other extensions.
etc.)
- [] OS: 
- [] Browser:

chore: add extra exports to cornerstone ext

---

platform/docs/docs/configuration/dataSources/dicom-json.md

Fixes a broken link on the documentation website.
Fixed the broken link.
* Go to documentation page
* navigate to "Configuration" -> "Data Sources" -> "DICOM JSON"
* click the link to the specification of the minimum required fields
* link should show the correct FAQ page
etc.)
- [] OS: 
- [] Browser:

docs: broken link to DICOM JSON minimum requirements on DICOM JSON documentation page

---

extensions/cornerstone-dicom-sr/src/viewports/OHIFCornerstoneSRViewport.tsx

Fix the following issue.
https://github.com/OHIF/Viewers/issues/4205
loadSR should run at least one time, before updateSR is running.

fix(sr): rendering issue by running loadSR before updateSR

---

extensions/default/src/getHangingProtocolModule.js
extensions/default/src/hangingprotocols/hpScale.ts
modes/segmentation/src/index.tsx

Re-enable the ohif scale hanging protocol while not breaking segmentation mode.
Display a study, add segmentaiton, make sure it still displays
Display one of the TG18 test patterns - eg:
http://localhost:4000/basic-test?StudyInstanceUIDs=2.16.124.113543.6004.101.103.20021117.190619.1&hangingProtocolId=@ohif/hpScale
Take a look at the vertical and horizontal striped single pixel lines
You should be able to see the striping, without moire patterns.  On a high res monitor, you may need a loupe to see individual pixels, or you can capture a screen shot and magnify the image in a tool such as gimp which allows pixel replication scaling to see individual pixels.
- [] My code has been …

fix: Re-enable hpScale module

---

extensions/default/src/Panels/PanelStudyBrowser.tsx
extensions/measurement-tracking/src/panels/PanelStudyBrowserTracking/PanelStudyBrowserTracking.tsx
platform/core/src/utils/createStudyBrowserTabs.ts
platform/core/src/utils/index.ts
yarn.lock

Addresses this https://github.com/OHIF/Viewers/pull/4085
Thanks @salimkanoun for the initial code

fix(studybrowser): Differentiate recent and all in study panel based on a provided time period

---

platform/app/public/config/default.js
platform/core/src/utils/createStudyBrowserTabs.ts

Just removing a console log that was left in

fix(code): remove console log

---

package.json
platform/cli/package.json
yarn.lock

chore(build): move exaca to dependencies

---

platform/cli/src/commands/listPlugins.js
platform/cli/src/commands/searchPlugins.js
platform/cli/src/commands/unlinkPackage.js
platform/docs/docs/development/playwright-testing.md
tests/MPR.spec.ts

reset .js extension in import

---

platform/cli/src/commands/linkPackage.js

fix(cli): missing js

---

platform/app/public/html-templates/index.html
platform/app/public/html-templates/rollbar.html
platform/docs/docs/platform/browser-support.md
platform/docs/versioned_docs/version-2.0-deprecated/faq/browser-support.md

chore: remove polyfill io

---

platform/docs/docs/migration-guide/from-3p7-to-3p8.md

docs(tools): add listener helpful tip for migration

---

platform/docs/docs/resources.md

2024-related activity is shown in the 2023 section. This PR updates the documentation by adding the new 2024 header and moving the 2024-related participation there.
A new section with 2024 and 2024-related participation is moved there.
N/A
N/A
etc.)
N/A
- [] OS: 
- [] Browser:

docs(resources) Update resources.md in Docs

---

package.json

There is a high severity vulnerability which has no fix in the ip package, so we need to change which package is used.
etc.)
- [] OS: 
- [] Browser:

fix: ip SSRF improper categorization

---

extensions/default/src/DicomWebDataSource/retrieveStudyMetadata.js
extensions/default/src/DicomWebDataSource/utils/retrieveMetadataFiltered.js
extensions/default/src/DicomWebDataSource/wado/retrieveMetadata.js

Series filtering query param was not being propagated correctly
etc.)
- [] OS: 
- [] Browser:

fix(url): series query param filtering

---

extensions/default/src/DicomWebProxyDataSource/index.ts
platform/app/public/config/kheops.js

The KHEOPS url= integration got broken due to a change int he API.  This PR just adds it back in.
Add a dicomwebproxy example integration called kheops.js, and fix the URL call so it works.
etc.)
- [] OS: 
- [] Browser:

fix: Add kheops integration into OHIF v3 again

---

platform/ui-next/src/components/Accordion/Accordion.tsx

This is a small update to the `Accordion` component in ui-next. Chevrons now give the correct feedback for open and closed states.
- Simple update to rotate the chevron in the `Accordion` component to match original design.
- See screenshot Before/After above
- Tested locally in Chrome using `ExperimentalUI` 
- [✅ ] My Pull Request title is descriptive, accurate and follows the
- [✅ ] My code has been well-documented (function documentation, inline comments,
etc.)
- [n/a] The documentation page has been updated as necessary for any public API
- [✅] OS: macOS Sonoma 14.6.1 (23G93)
- [✅] Node version: 20.15.1
- [✅] Browser: Chrome 128.0.6613.138 (Official Build)
[blog]: …

fix(ui): Fixed study component open and closed feedback in Studies panel

---

platform/ui-next/src/components/DateRange/DateRange.tsx
platform/ui-next/src/components/SidePanel/SidePanel.tsx
platform/ui-next/src/components/StudyBrowser/StudyBrowser.tsx
platform/ui-next/src/components/StudyItem/StudyItem.tsx
platform/ui-next/src/components/Toolbox/Toolbox.tsx
platform/ui/src/components/StudyBrowser/StudyBrowser.tsx

Address import issues
etc.)
- [] OS: 
- [] Browser:

fix: 🐛 Fix imports for ui-next

---

package.json
yarn.lock

Fixing all hihg-priority vulnerabilities.
etc.)
- [] OS: 
- [] Browser:

fix(dependent): high priority vulnerabilities

---

README.md

Updates the fossa integration to correctly work with OHIF.

fix(fossa): update fossa to track licenses correctly

---

platform/ui/src/components/CinePlayer/CinePlayer.tsx

To make it easier to support e2e testing with Playwright, I have added the `data-cy` test ids to the Cine Players for controls (play/pause, left, right, close)
No tests updates are required as I am only add data-cy ids to 4 divs
etc.)

chore(ui): Added Data Test Ids to Cine controls for e2e Testing

---

extensions/cornerstone/src/hps/fourUp.ts

small typo in the preset displayset

fix(typo): type in fourup preset

---

package.json
yarn.lock

Hot fixing high and critical vulnerabilities for stable release 3.8.3
etc.)
- [] OS: 
- [] Browser:

fix(dependent): high priority vulnerabilities (#4396)

---

extensions/cornerstone/src/services/CornerstoneCacheService/CornerstoneCacheService.ts

A couple of places were missing from [last update](https://github.com/OHIF/Viewers/pull/4433).
etc.)
- [] OS: 
- [] Browser:

fix(ui): show ui notification on displaySet load error

---

platform/ui-next/src/components/DisplaySetMessageListTooltip/DisplaySetMessageListTooltip.tsx
platform/ui-next/src/components/Thumbnail/Thumbnail.tsx

Small design fixes for Study Thumbnails and Display set tooltip.
- Text in thumbnails aligns better 
- Padding changes to the display set tooltip.
etc.)
- [] OS: 
- [] Browser:

fix(ui) Study Browser small spacing changes

---

.scripts/dicom-json-generator.js

Fixes #4440 
update comments and script usage instruction.
Generate JSON DICOM for directory with bunch of DICOM files
etc.)
- [] Node version: 20.12.0 
- [] Browser: NA

fix(JSONScript) update name of the script in the comments to follow renaming

---

README.md

publish version 3.9

---

platform/ui-next/src/components/StudyBrowser/StudyBrowser.tsx
platform/ui-next/src/components/StudyItem/StudyItem.tsx
platform/ui-next/src/components/Thumbnail/Thumbnail.tsx

This PR fixes a scrolling issue with accordion content in the Study Panel as well as small inconsistent display fixes for design elements.
Fixes behaviors for accordions and content in the study panel
etc.)
- [] OS: 
- [] Browser:

fix(ui) Scrolling and display fixes for study panel

---

.github/workflows/playwright.yml

fixes the error that was occurring in playwright merge report workflow step

[OHI-1333] fix(workflows): address error in merge report step of the playwright workflow

---

.github/workflows/playwright.yml
platform/app/cypress/support/commands.js
platform/ui-next/src/components/Errorboundary/ErrorBoundary.tsx

fix(error-boundray): prevent stack trace from overflowing and make it scrollable

---

extensions/cornerstone/src/panels/PanelSegmentation.tsx
extensions/default/src/commandsModule.ts
modes/longitudinal/src/customizations.tsx
platform/ui-next/src/components/SegmentationTable/SegmentationExpanded.tsx
platform/ui-next/src/components/SegmentationTable/SegmentationHeader.tsx
platform/ui-next/src/components/SegmentationTable/SegmentationSelectorHeader.tsx

This pull request introduces significant changes to the `PanelSegmentation` component and related files to enhance the customization and functionality of the segmentation dropdown menu. The most important changes include importing additional components from `@ohif/ui-next`, creating a custom dropdown menu content component, and updating the segmentation table headers to use this new component.
* [`extensions/cornerstone/src/panels/PanelSegmentation.tsx`](diffhunk://#diff-13140ddde8642a8a9e11b5c1849099e430f16a9a7a48e5b780ea68165243d38cL2-R13): Imported additional components from `@ohif/ui-next` and implemented a custom dropdown menu content component for segmentation actions, such as adding, editing, and exporting segmentations. The custom dropdown menu content is integrated into both …

feat(segmentation): Enhance dropdown menu functionality in SegmentationTable

---

platform/ui/src/components/Header/Header.tsx

Fix breaking change in Header legacy, <svg> component was not imported (Cecilia and Salim)

fix ohif icons in Header

---

platform/core/src/classes/MetadataProvider.ts
platform/ui-next/src/components/Icons/Icons.tsx
platform/ui-next/src/components/Icons/Sources/Clipboard.tsx

fixes https://github.com/OHIF/Viewers/issues/4343

feat(icons): Add Clipboard icon and update MetadataProvider for null checks

---

extensions/cornerstone/src/commandsModule.ts
extensions/cornerstone/src/services/SegmentationService/SegmentationService.ts
extensions/tmtv/src/commandsModule.ts

A translation option for the term 'segment' has been incorporated by [FlyWheel.io](https://flywheel.io/).
The term 'segment' can be adapted to alternative terminology. The react i18n library facilitates this translation. It is used for the set segment labels in both segmentation and TMTV modes.
etc.)
Chrome 120.0.6099.71

feat/Added translation option for text 'segment'

---

Dockerfile

fix(docker): make multiarch work

---

Dockerfile

fix(Dockerfile): Clear bun package manager cache before installation

---

.circleci/config.yml

fix(circleci): Update workflow dependencies for Docker publishing stages

---

platform/core/src/services/DicomMetadataStore/DicomMetadataStore.ts

Hi there, currently to access a series in the DicomMetadataStore we need to know StudyInstanceUID and SeriesInstanceUID.
As SeriesInstanceUID is unique, StudyInstanceUID shouldn't be required to retrieve a Series Metadata, it should be possible to retrieve a Series by only it's SeriesInstanceUID.
I will need this because I need to access metadata in a custom rendering annotation callback, the annotations only stores SeriesInstanceUID and not StudyInstanceUID (this is ok in my opinion, we don't need StudyInstanceUID for an annotation that references a SeriesInstanceUID).
In this PR I made StudyInstanceUID possibly null, I was about to make a sperate API with only SeriesInstanceUID but I can't find another name for the new API.
Can you tell me what is the preffered implementation of a API …

Make StudyInstanceUID optional to retrieve a Series from DicomMetadataStore 

---

extensions/cornerstone-dicom-sr/src/commandsModule.ts

There were multiple unused variables in this file, as well as access to functions that did not exist. I'm fixing it so that only variables/functions that exist are accessed/called and removing the unnecessary variables:
etc.)
- [] OS: 
- [] Browser:

fix: cs dicom sr commands module

---

extensions/default/src/CustomizableContextMenu/ContextMenuItemsBuilder.ts
platform/ui-next/src/components/Icons/Icons.tsx
platform/ui/src/components/ContextMenu/ContextMenu.tsx

Fixing the icon which didn't exist and the color that would make it almost invisble.
Before (notice the black "missing icon" text):
After:
etc.)
- [] OS: 
- [] Browser:

fix: context menu icon

---

platform/app/public/config/e2e.js
platform/docs/versioned_docs/version-3.9/configuration/configurationFiles.md

Several people have asked about how to set default search criteria.  This PR just adds an example in the test:e2e:serve for default to searching for "today" when the search criteria is `?today`
etc.)
- [] OS: 
- [] Browser:

docs: Documentation on how to set default configuration to search for today

---

extensions/default/src/ViewerLayout/ResizablePanelsHook.tsx
extensions/default/src/ViewerLayout/constants/panels.ts
modes/basic-dev-mode/src/index.ts
modes/basic-test-mode/src/index.ts
modes/microscopy/src/index.tsx
modes/preclinical-4d/src/index.tsx
modes/segmentation/src/index.tsx
modes/tmtv/src/index.ts
platform/app/cypress/integration/OHIFVideoDisplay.spec.js
platform/ui-next/src/components/StudyBrowser/StudyBrowser.tsx
platform/ui-next/src/components/StudyBrowserSort/StudyBrowserSort.tsx
platform/ui-next/src/components/StudyBrowserViewOptions/StudyBrowserViewOptions.tsx
platform/ui-next/src/components/StudyItem/StudyItem.tsx
platform/ui-next/src/components/Thumbnail/Thumbnail.tsx
platform/ui-next/src/components/ThumbnailList/ThumbnailList.tsx

Building on top of @jbocce Joe's PR to make thumbnails respond to panel resizing
https://github.com/user-attachments/assets/bcbbb292-ba83-4070-a500-0464214fa580
https://github.com/user-attachments/assets/096bcc61-0e5b-435d-83cb-21fbdd8066c5
https://github.com/user-attachments/assets/f8511de6-10fe-4cf6-9307-1a792d64ad20

feat(panels): responsive thumbnails based on panel size 

---

platform/docs/docs/platform/services/customization-service/sampleCustomizations.tsx

fix(docs): image in customization

---

README.md

Fixes: https://github.com/OHIF/Viewers/issues/4750
etc.)
- [] OS: 
- [] Browser:

docs: fix yarn version

---

modes/basic-dev-mode/src/index.ts
modes/microscopy/src/index.tsx
modes/preclinical-4d/src/index.tsx
modes/segmentation/src/index.tsx
platform/cli/templates/mode/src/index.tsx

Fixes: https://github.com/OHIF/Viewers/issues/4787
Also removing the deprecated code from other places.
etc.)
- [] OS: 
- [] Browser:

fix: right panel for the create mode cli command

---

bun.lock
package.json
yarn.lock

fix: depandabot

---

platform/ui/src/components/StudyItem/StudyItem.tsx

"Icon" is not defined in this file and this is crashing the application.
etc.)
- [] OS: 
- [] Browser:

fix: icon is not defined

---

platform/core/src/utils/combineFrameInstance.ts

Currently this is crashing because of a missing ImageOrientationPatient tag:
https://viewer.ohif.org/viewer?StudyInstanceUIDs=1.2.276.0.7230010.3.1.2.447481088.1.1669202398.851612
I'm solving the problem and doing some refactoring to improve the code readability.
etc.)
- [] OS: 
- [] Browser:

fix: combine frame instance

---

extensions/cornerstone/src/services/SegmentationService/SegmentationService.ts
extensions/cornerstone/src/utils/transitions.ts

fix(rt): jump to segment discards the configured width

---

extensions/default/src/Panels/StudyBrowser/PanelStudyBrowser.tsx

The study browser performance needs the same fix as the study browser tracking
etc.)
- [] OS: 
- [] Browser:

fix: Performance of panel study browser

---

extensions/tmtv/src/utils/measurementServiceMappings/constants/supportedTools.js

The CircleROIStartEndThreshold was missing in the supported tools array so the MeasurementService mapping was ignoring it.
- Added the CircleROIStartEndThreshold to the array of supported tools
etc.)
- [] OS: 
- [] Browser:

fix(tmtv tools): add CircleROIStartEndThreshold to supported tools in TMTV extension

---

.github/.dependabot.yaml

chore: run dependabot

---

extensions/default/src/DicomTagBrowser/DicomTagBrowser.tsx

This PR resolves an issue where inspecting extra-large DICOM tag structures (such as certain SEG series studies) would exceed the maximum call stack size and crash the application.
The original implementation used a recursive function to process DICOM tag content. With very large or deeply nested data sets, this recursion led to an overflow of the call stack, causing the application to crash when users attempted to browse such studies.
I refactored the algorithm. Now the recursive approach has been replaced with an iterative solution that uses standard loops. This new method avoids deep recursive calls, thereby eliminating the risk of hitting the call stack limit even with complex, large datasets.
Before:
This study's SEG series would crash the application when inspectioned with the Dicom …

fix: max call stack exceeded for dicom tag browser

---

platform/app/src/routes/Local/Local.tsx

This PR updates the `Local` component to align more closely with the new design system and revises the UI copy to emphasize local data loading.
- Replaced legacy Button component from `@ohif/ui` with the new Button from `@ohif/ui-next`
- UI Copy: Improved readability and user reassurance (see before and after screens)
- Updated button styling to match the new design language
- Updated colors and other design spacing to better fit the Viewer's design language
- Improved UI layout positioning the "Load files" and "Load folders" buttons together
Tested in Chrome (macOS)
etc.) …

ui(migrate) Migrate local view to new ui-next components

---

platform/core/src/classes/MetadataProvider.ts

This matches the 3D Slicer defaults

fix(metadata): change the default values for cosines

---

platform/core/src/utils/sortStudy.ts

Fixing date time comparison
etc.)
- [] OS: 
- [] Browser:

fix: compare series date time

---

platform/core/src/classes/MetadataProvider.ts

fix orthanc seg

---

.github/.dependabot.yaml

chore: update dependabot

---

platform/docs/src/css/custom.css
platform/docs/tailwind.config.js
platform/ui-next/src/components/ScrollArea/ScrollArea.tsx
platform/ui-next/src/components/Viewport/ImageScrollbar.module.css
platform/ui-next/src/tailwind.css
platform/ui-next/tailwind.config.js
platform/ui/src/tailwind.css

(currently updating...)
Adds neutral color variable, updated scrollbars
etc.)
- [] OS: 
- [] Browser:

ui(colors): Adds neutral color variable and updates scrollbars 

---

platform/docs/src/pages/components-list.tsx
platform/docs/src/pages/components/AllinOneMenuShowcase.tsx
platform/docs/src/pages/components/CinePlayerShowcase.tsx
platform/docs/src/pages/components/DropdownMenuShowcase.tsx
platform/docs/src/pages/components/TooltipShowcase.tsx
platform/docs/src/pages/patterns/index.tsx

Fixes design documentation build errors
1. **Dynamically Import Browser-Only Components**  
- Removed direct imports of `ui-next` components that rely on browser APIs.  
- Used `useIsBrowser` to conditionally require components only on the client side.  
- Ensures no SSR errors when building the static site.
2. **Removed `<BrowserOnly>` Usage**  
- Replaced `<BrowserOnly>` with `useIsBrowser` in `CinePlayerShowcase` and `AllinOneMenuShowcase`.  
- Prevented parser errors (`Unexpected token BrowserOnly`) in `.tsx` files.
3. **Fixed Nested `<button>` Issue**  
- Used `asChild` on `<DropdownMenuTrigger>` to avoid nested `<button>` elements.  
- Eliminates related minification warnings.
4. **Corrected Mismatched HTML Tags**  
- Wrapped heading and button elements properly in …

fix(docs): Fix SSR build errors by dynamically importing UI components and resolving other issues

---

extensions/default/src/ViewerLayout/ViewerHeader.tsx
platform/app/src/routes/WorkList/WorkList.tsx
platform/core/src/services/CustomizationService/types.ts

Adding the ability of customizing modal title and other aspects of customizable menu components.
etc.)
- [] OS: 
- [] Browser:

feat: improve menu modals customizations

---

extensions/default/src/Toolbar/ToolbarLayoutSelector.tsx
platform/ui-next/src/components/index.ts

Added a missing export for LayoutSelector in the ui-next library and fixed a relative import.
- Added export for LayoutSelector
- Changed relative import with '@ohif/ui-next'
etc.)
- [] OS: 
- [] Browser:

fix: Added missing export for LayoutSelector in ui-next

---

extensions/cornerstone-dynamic-volume/src/getPanelModule.tsx
extensions/cornerstone/src/components/ViewportDataOverlaySettingMenu/ViewportDataOverlayMenu.tsx
extensions/cornerstone/src/getPanelModule.tsx
extensions/cornerstone/src/hooks/useMeasurements.ts
extensions/cornerstone/src/hooks/useViewportDisplaySets.ts
extensions/tmtv/src/getPanelModule.tsx
modes/basic-dev-mode/src/index.ts
modes/basic-dev-mode/src/toolbarButtons.ts
modes/basic-test-mode/src/index.ts
modes/basic-test-mode/src/toolbarButtons.ts
modes/longitudinal/src/index.ts
modes/longitudinal/src/toolbarButtons.ts
modes/microscopy/src/index.tsx
modes/microscopy/src/toolbarButtons.ts
modes/preclinical-4d/src/getWorkflowSettings.ts
modes/preclinical-4d/src/index.tsx
modes/preclinical-4d/src/toolbarButtons.tsx
modes/segmentation/src/index.tsx
modes/segmentation/src/toolbarButtons.ts
modes/tmtv/src/index.ts
modes/tmtv/src/toolbarButtons.ts
platform/app/cypress/integration/ImageConsistency.spec.js
platform/cli/templates/mode/src/index.tsx
platform/core/src/services/ToolBarService/ToolbarService.ts
platform/core/src/services/ToolBarService/types.ts
platform/core/src/services/WorkflowStepsService/WorkflowStepsService.ts
platform/docs/docs/migration-guide/3p10-to-3p11/toolbarService.md

This pull request introduces a series of updates to standardize and improve the handling of toolbar sections and button configurations across multiple components and modes. The changes primarily focus on replacing hardcoded section identifiers with dynamic references to `toolbarService`, ensuring consistency and flexibility in toolbar management. Additionally, minor improvements were made to hooks and utility functions for better default handling and readability.
* Updated `buttonSectionId` in panel modules across multiple extensions (e.g., `cornerstone-dynamic-volume`, `tmtv`) to dynamically reference `toolbarService.sections` instead of hardcoded strings. [[1]](diffhunk://#diff-8802fc8746db1d22999b9d759a7250eac0781f9d5f8bcc737479b74f607a29cfR8-R9) …

fix: backward compatibility with toolbar service

---

.github/workflows/playwright.yml

fix: e2e playwright tests runnigns

---

bun.lock
extensions/cornerstone/src/customizations/viewportToolsCustomization.ts
modes/basic-dev-mode/src/index.ts
modes/basic-test-mode/src/initToolGroups.ts
modes/longitudinal/src/initToolGroups.js
modes/preclinical-4d/src/initToolGroups.tsx
modes/segmentation/src/initToolGroups.ts
modes/tmtv/src/initToolGroups.js
platform/app/public/html-templates/index.html
platform/app/public/html-templates/rollbar.html

Pinch zoom and muti-touch causes the entire OHIF application to zoom.
Prevent the browser page scaling for OHIF.
Add multi-touch bindings for zoom and scroll in the default tool group in the longitudinal mode.
1. pinch zoom for a viewport should work
2. three finger scroll for a viewport should work
etc.)

fix(touch): Allow for multi-touch in OHIF

---

bun.lock
platform/app/src/App.css
platform/app/src/App.tsx

The default browser behaviour to drag/pull down to refresh the browser should be surpressed.
Added some css to prevent the drag to refresh behaviour. We use css because doing a `preventDefault` on the touch event would also prevent scrolling in scrollable areas.
On various touch devices, run OHIF. A touch drag should NEVER refresh the OHIF page.
etc.)

fix(touch): Prevent touch drag to refresh the browser page.

---

bun.lock
extensions/cornerstone/src/Viewport/OHIFCornerstoneViewport.tsx
extensions/cornerstone/src/hooks/useViewportHover.ts
platform/docs/docs/migration-guide/3p10-to-3p11/other.md
platform/docs/docs/platform/hooks/useViewportHover.md

Renamed a testing data id from data-viewportId to data-viewportid to prevent an exception complaining about illegal naming.
etc.)
- [] OS: 
- [] Browser:

fix: data-viewportId name is illegal, renamed to data-viewportid

---

extensions/default/src/init.ts
platform/core/src/classes/HotkeysManager.ts

Subscribe the toolbar to the hotkey presses so it can update it's state correctly, add events to hotkeys manager class

feat(toolbar/hokeys): add pub sub events to hotkeys manager class, subscribe toolbar to hotkeys pressed event

---

extensions/tmtv/src/Panels/PanelROIThresholdSegmentation/PanelROIThresholdExport.tsx
extensions/tmtv/src/commandsModule.ts
extensions/tmtv/src/utils/createAndDownloadTMTVReport.js
platform/ui-next/src/components/SegmentationTable/AddSegmentationRow.tsx
tests/MPRThenRTOverlayNoHydration.spec.ts
tests/MPRThenSEGOverlayNoHydration.spec.ts
tests/TMTVCSVReport.spec.ts
tests/utils/download.ts
tests/utils/locators.ts

See #5205 .
Corrected the filename for the TMTV CSV report download.
Corrected the output of values to the TMTV CSV report by accounting for type correctly. Added Playwright tests.
See #5205. OHIF should download the TMTV CSV file with correct name and contents.
etc.)

fix(TMTV): The TMTV CSV file now has the correct name and contents

---

extensions/default/src/init.ts

fix(viewportgrid): don't subscribe to duplicate event listeners

---

extensions/cornerstone/src/customizations/CustomDropdownMenuContent.tsx
extensions/cornerstone/src/panels/PanelSegmentation.tsx

Fixes #4926 
https://github.com/user-attachments/assets/df0e8c91-0d71-4021-89b5-5b9f01f36103
Try to download or export a segmentation, then make a drawing and try again.
etc.)

fix: disable seg download/export buttons until a user has drawn something

---

platform/ui-next/src/components/Tooltip/Tooltip.tsx

Uses portals for tooltips to avoid z-index issues

fix(tooltips): tool tips should be portals

---

platform/core/src/services/HangingProtocolService/lib/validator.js

Adds containsAll validator

---

.circleci/config.yml

chore: remove manual approve

---

extensions/cornerstone/src/Viewport/Overlays/ViewportOrientationMarkers.tsx

A simplified orientation markers version that does not need to check if the series is flipped or rotated because it gets the row/column cosines vectors directly from the viewport.

feat(orientationMarkers): improved the orientation markers with a simplified version

---

extensions/cornerstone/src/panels/PanelSegmentation.tsx
extensions/cornerstone/src/utils/segmentationHandlers.ts
extensions/cornerstone/src/utils/setUpSegmentationEventHandlers.test.ts
extensions/cornerstone/src/utils/setUpSegmentationEventHandlers.ts
extensions/default/src/utils/Toolbox.tsx

Before...
After...
1. Visit the temporary deploy https://multi-tab-seg.netlify.app/segmentation?StudyInstanceUIDs=1.2.840.113619.2.290.3.3767434740.226.1600859119.501
2. Open the label map segmentation tab.
3. The tools should flow and align nicely.
etc.)

fix(toolbar): Wrap toolbar buttons properly using a flex layout.
