- README.md
It took a lot of time, googling and luck to figure out the default username/password for the docker image. Adding it to the README would probably be a good idea.
> Add default user/pass to readme

- Packages/ohif-core/client/components/base/mixins/dropdown.js
- Packages/ohif-viewerbase/client/components/viewer/toolContextMenu/toolContextMenu.js
- Packages/ohif-viewerbase/client/lib/toolManager.js
- Packages/ohif-viewerbase/package.js
Image measurements shall be removable through a dialog toggled by 
1 - Right-clicking on the measurement;
2 - Long-pressing on the measurement on a touch-capable device;
There were a few edge cases to take care of. First of all is how cornerstone name their tools and how it names its manager, there are mismatches for `simpleAngle`, which uses the toolManager `angle`, and `arrowAnnotate` which uses `annotate`.
The second catch was the `arrowAnnotate` which already had a solution for removing the annotation for mobile. When you do a long touch you can edit the annotation and there is a button to remove it. So I decided to keep that behavior and to not add the context-menu for that.
Example for desktop:
Example for mobile:
> OHIF-110: context-menu for measurements in the viewport

- Packages/ohif-viewerbase/client/lib/toolManager.js
Switching tools while one of the viewports are loading throws an uncaught error. This is a bug in the toolManager, in which we need to add a better handler to this kind of situation.
Before doing any kind of activation through cornerstone I added a check for all elements we want to activate the tool. I added this snippet before all the logic because I wanted to avoid to do any kind of action if any of the elements was yet not enabled. This would prevent to execute any undo action and more complex logic to restore the last state.
> OHIF-113: added element verification before tool activation.

- Packages/ohif-study-list/server/services/qido/studies.js
We were referring the accession number as a number and not as a string as the documentation says: http://dicom.nema.org/dicom/2013/output/chtml/part06/chapter_6.html
It was right for the DIMSE server, we were only doing it wrong with the QIDO implementation
This addresses #109
> OHIF-170: using getString to get accession number for QIDO calls

- LesionTracker/client/components/toolbarSection/toolbarSection.html
- LesionTracker/client/components/toolbarSection/toolbarSection.js
- LesionTracker/client/components/toolbarSection/toolbarSection.styl
- Packages/ohif-measurements/client/lib/syncMeasurementAndToolData.js
Save button not appearing and saved measurements not getting drawn in canvas
- Come back with Save button that was removed from caseProgress component. 
- Added the Save button in the Lesiontracker toolBarSession component
- Fixed a small issue to draw saved measurements into the canvas
> bugFix(issue163) 

- Packages/ohif-study-list/client/lib/importStudies.js
- During uploading DICOMs the first time the function is called with
no parameter -> this leads to the whole upload to be crashing
> fix: first time uploadMessage called with undefined as parameter

- Packages/ohif-viewerbase/client/components/viewer/toolbarSectionButton/toolbarSectionButton.html
- Packages/ohif-viewerbase/client/components/viewer/toolbarSectionButton/toolbarSectionButton.js
Changing toolBarSection to accept custom template subtools. 
I.e. coder could pass his own template as part of subtools for specific tool button.
> feature(custom subtools into toolbar) colormap-custom subtools 

- Packages/ohif-study-list/client/components/studylist/studylistResult/studylistResult.styl
- Packages/ohif-study-list/client/components/studylist/studylistStudy/studylistStudy.html
- If patientName is undefined we display a string "(empty)" with different style to make the study more visible in the list. 
Closes #161
> fix(issue#161) Add text empty for patiente name on Anonymized Cases

- Packages/ohif-study-list/client/lib/importStudies.js
If an import happens to fail the dialog promise never resolves. 
This is because `numberOfStudiesFailed` is incremented on error but `numberOfStudiesImported` is not, so the branch  to resolve or reject is never taken.
> Fix importStudies dialog when import fails

- docs/README.md
- docs/package.json
- generateStaticSite.sh
- package.json
Add /viewer/?url=https://raw.githubusercontent.com/galelis/testData/master/studyWithMeasurements.json
to the Netlify deploy preview URL.
Example: https://deploy-preview-232--ohif.netlify.com/viewer/?url=https://raw.githubusercontent.com/galelis/testData/master/studyWithMeasurements.json
TODO:
- Stop using gh-pages branch to host docs? Use Netlify instead? TBD...
> feat(netlify) Add static site deployment from Netlify

- Packages/ohif-cornerstone/package.js
- dcmJS was not being transpiled so it was generating an issue on IE11, 0.1.5 dcmJS version has now webpack with babel, so it will fix the issue on IE11 
Closes Issue #258
> Bump version of dcmJS into cornerstone package

- Packages/ohif-viewerbase/client/components/viewer/imageViewerViewport/imageViewerViewport.js
- Activate focus on element (viewport) only if its not activate already.  
(closes #183)
> BugFix(#183): Avoid adding focus on a viewport that is already activated

- OHIFViewer/client/config.js
- OHIFViewer/client/routes.js
- Packages/ohif-hanging-protocols/client/protocolStore/defaultStrategy.js
- Packages/ohif-servers/both/collections/currentServer.js
- Packages/ohif-servers/both/collections/servers.js
- Packages/ohif-servers/client/collections/index.js
- Packages/ohif-servers/client/collections/subscriptions.js
- Packages/ohif-servers/client/index.js
- Packages/ohif-servers/client/startup.js
- Packages/ohif-servers/server/startup.js
Addresses #275
- Add startup.js to copy public.servers into the client Minimongo collection if we are using public.clientOnly = true
- Set CurrentServer and Servers collection to client-only if clientOnly = true
- Call Meteor.disconnect() if we are using clientOnly = true
- Guard If statements requiring Meteor.settings.public, since it was not defined on the Standalone Viewer
> fix(client-only): Fix client-only Server & CurrentServer usage

- StandaloneViewer/StandaloneViewer/client/config.js
- StandaloneViewer/StandaloneViewer/routes.js
- docs/standalone-viewer/usage.md
A token fragment parameter can be specified. If present this value will be used for http bearer authorization when making requests.
A fragment parameter is used instead of a query parameter so that the token is never sent over the network.
Example :
http://localhost:3000/?url=https://some.website.io/sampleDICOM.json#token=1a2b3c4d
Fixes #140
> Standalone Viewer Authorization Header

- Packages/ohif-cornerstone/package.js
Fixed #319 by this update to the cornerstoneWADOImageLoader: 
https://github.com/cornerstonejs/cornerstoneWADOImageLoader/pull/215
> Update cornerstone libs (wado) to latest and fix Incorrect ultrasound measurement #319

- .travis.yml
There is an open issue https://github.com/OHIF/Viewers/issues/340 which is related to when someone does a fork and then open a PR, Travis ignores the encrypted environment variables and breaks the build.
In order to solve that issue, it was added a condition where if the DOCKER_PASS is null it skips the "build development docker image" and "build production docker image" stages.
"Encrypted environment variables are not available to pull requests from forks due to the security risk of exposing such information to unknown code."
> including skip configuration if the push comes from external PR

- Packages-react/extensions/ohif-dicom-microscopy-extension/src/DicomMicroscopyViewport.js
Refs in React provides a way to access the React elements (or DOM nodes) created in the render() method. DicomMicroscopyViewport makes use of this strategy to render the container.
`<div ref={this.container} />`
There is an issue which is that the viewport is not maximizing.
> adding style to fix viewport maximization

- config/oidc.json
The integration only needs read access to projects not all cloud
platform resources.
> Restrict Scope for Cloud Healthcare API Example Config

- netlify.toml
@dlwire, this should fix your Netlify direct link issues.
> docs(netlify.toml): Fix Netlify URL path issues for deploy previews

- src/connectedComponents/FlexboxLayout.css
Removed `transform` that was affecting the drag and drop position in the study browser area.
> fix(DragNDrop): add new library to handle drag and drop for mobile devices

- docs/latest/README.md
- docs/latest/package.json
We are now on the free open source plan of Netlify, so we need to display the badge prominently on our homepage according to their guidelines. 
Looks like this:
> docs(netlify): Add Netlify badge to top of docs page

- docs/latest/essentials/translating.md
- extensions/ohif-i18n/package.json
- extensions/ohif-i18n/src/index.js
- extensions/ohif-i18n/yarn.lock
- extensions/ohif-vtk-extension/package.json
- extensions/ohif-vtk-extension/yarn.lock
- package.json
- yarn.lock
This following export in `@ohif/i18n` is not working when using the Viewer tag script implementation: 
https://github.com/OHIF/Viewers/blob/cb565427b3d193b85072751a92b61a2bb9171a4b/extensions/ohif-i18n/src/index.js#L56
It's breaking and displaying the error `Object(...) is not a function`.
1 - `react-viewerbase`. — to fix the require issue in `react-dnd`. -- https://github.com/OHIF/react-viewerbase/pull/117
2 - `@ohif/extension-vtk` to update `react-viewerbase` version published above.
3 - `OHIF/Viewers` to update `react-viewerbase`, `@ohif/extension-vtk` and `@ohif/i18n`.
> fix(@ohif/i18n): Tag script implementation

- .gitattributes
- extensions/ohif-cornerstone-extension/package.json
- extensions/ohif-cornerstone-extension/src/commandsModule.js
- extensions/ohif-cornerstone-extension/src/toolbarModule.js
- package.json
- src/connectedComponents/PluginSwitch.js
- src/connectedComponents/ToolbarRow.js
- src/setupTools.js
- yarn.lock
Regarding to [this feature request](https://ohif.canny.io/feature-requests/p/update-toolbar-to-match-v1s-default-setup), here is the tools to add for cornerstone viewport:
> feat(tools): Add additional tools

- package.json
- yarn.lock
Looks like e2e tests are working, viewer.ohif.org is working, but Netlify's deploy previews are not usable due to this weird babel-core issue.
Possibly related: https://github.com/babel/babel/issues/10179
> fix(package.json): Fix issues with babel-core causes undefined _objectSpread2

- .dockerignore
- Dockerfile
- docker/Viewer-v2.x/entrypoint.sh
- docs/latest/connecting-to-image-archives/google-cloud-healthcare.md
- public/config/google.js
fix(docker-google-cloud): Update docker build process to allow Google Cloud CLIENT_ID to be passed in at runtime, update docs.
> fix(docker-google-cloud): Update docker build process for simpler GCP usage

- src/studylist/StudyListWithData.js
fix #654
Turns out the <Dropzone> component used for local file uploading is calling preventDefault on all click events.
> fix(GoogleCloud): Fix Cloud Healthcare file upload buttons

- src/connectedComponents/Viewer.js
Instead of using a default modality information for display set, start getting these from ohif-core display set
> fix(Viewer): Removes fixed modality and get the one returned from ohif-core

- src/connectedComponents/ToolbarRow.js
Use the activeButtons list to see if there are any active buttons in submenus. If there are, pass one in as the activeCommand so it gets highlighted.
Related to sitka https://github.com/trustsitka/sitka/issues/3403
> fix(ToolbarRow): Update ToolbarRow to show active submenu buttons

- src/setupTools.js
Adding the ArrowAnnotate tool to the list of supported tools.
We could also add this to the toolbar easily enough but here we go for now.
https://github.com/trustsitka/sitka/issues/3403
> add ArrowAnnotate as an available tool

- extensions/ohif-cornerstone-extension/src/commandsModule.js
- public/config/default.js
This change adds the keybindings for previousImage (down) and nextImage (up) to the default
configuration and adds the command and action necessary to support it. This pull request is
dependent upon https://github.com/cornerstonejs/cornerstoneTools/pull/1025 which exports the scroll
utility it uses.
Depends on https://github.com/cornerstonejs/cornerstoneTools/pull/1025
Contributes to https://github.com/trustsitka/sitka/issues/3426
> feat(commandsModule): Add `previousImage` and `nextImage` actions and commands

- package.json
- rollup.config.js
- src/config.js
- src/index_publish.js
- yarn.lock
Addresses #2 and #3 from this Issue: https://github.com/OHIF/Viewers/issues/521
Open to changing the name, not sure if `installViewer` is what users would expect.
Script tag usage is a bit simpler now:
```html
<div id="root"></div>
<script>
const config = {
// default: '/'
routerBasename: '/',
// default: ''
relativeWebWorkerScriptsPath: '',
servers: {
dicomWeb: [
{
name: 'DCM4CHEE',
wadoUriRoot: 'https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/wado',
qidoRoot: 'https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs',
wadoRoot: 'https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs',
qidoSupportsIncludeField: true,
imageRendering: 'wadors',
thumbnailRendering: 'wadors',
},
],
},
i18n: {
LOCIZE_PROJECTID: 'a8da3f9a-e467-4dd6-af33-474d582a0294',
LOCIZE_API_KEY: null, // Developers can …
```
> fix(script-tag): Include React and ReactDOM as dependencies, add installViewer export

- cypress/support/script-tag/index.html
- package.json
- rollup.config.js
Some of the recent changes around the script-tag support for ohif/Viewers included moving `react` and `react-dom` from `peerDependencies` to `dependencies`. This caused an error for embedded consumers of the viewer because there could be multiple versions of react included. 
The error in the console points to this link: https://reactjs.org/warnings/invalid-hook-call-warning.html.
These changes are necessary to resolve the issue for embedded users and don't seem to break the standalone version either.
> fix(package.json): Resolve react/react-dom dependency conflict for embedded users

- extensions/ohif-cornerstone-extension/src/ConnectedCornerstoneViewport.js
`onMeasurementsChanged` currently defines a function map every time it is called. This function map includes a throttle on the `modified` function which is not being used because the function is
called at most once per time it is instantiated. These changes elevate the map definition to the
file level, since what it is defining does not change based on the other executed code.
This cleans up the code a little bit, but more importantly because the `throttle` is now working as intended, the performance of the "Measurements" pane is improved.
> fix(ConnectedCornerstoneViewport): Fix definition of function map so it happens less frequently

- extensions/vtk/package.json
Looks like this was lost in the transition to monorepo and the versions fell behind a bit.
> fix: Update vtk and viewport dependencies

- platform/viewer/src/setupTools.js
Issue:
- Pan and Zoom tools should be activated by default on right and middle click respectively. 
Cause: 
- `react-cornerstone-tools` will only activate tools that are left button (1) tools and also have another button mask. 
Fix: 
- Changing `mouseButtonMask` adding button 1 into mask array.
> fix: 🐛 Activating Pan and Zoom on right and middle click by def

- platform/viewer/src/App.js
Fixed issue on not loading gcloud. Error on name variable declaration
The correct name variable is _appConfig and not appConfig
> fix: 🐛 Fix issue on not loading gcloud

- extensions/cornerstone/package.json
- extensions/vtk/package.json
- platform/core/package.json
- platform/viewer/package.json
- yarn.lock
Closes #917
Related: https://github.com/OHIF/Viewers/pull/918
> fix: bump cornerstone-tools to latest version

- extensions/vtk/src/OHIFVTKViewport.js
Wait until paint tools are implemented
> fix: Stop adding empty labelmap to VTK Viewports for now. 

- platform/ui/package.json
- platform/ui/src/utils/viewerbaseDragDropContext.js
- yarn.lock
fix: Use HTML5Backend for drag-drop if the device does not support touch, since it's less buggy
Note: still need to test the deploy preview on a real device, which is why this is marked as a draft.
> fix: Use HTML5Backend for drag-drop if the device does not support touch

- platform/core/src/studies/retrieveStudyMetadata.js
On some configurations variables named `module` may clash with the predefined JS global.
resolves #940
> Avoid using variable name "module"

- platform/viewer/src/connectedComponents/ConnectedPluginSwitch.js
- platform/viewer/src/connectedComponents/PluginSwitch.js
The Toolbar was showing 2 expandable buttons with an "etc..." icon, one of them had only 1 button, MPR.
This way, mpr is better accessible with fewer clicks to get to it.
Codewise, I removed some commented out code (don't worry, git will remember), and reduced the amount of state shared between 2 components to the bare minimum.
> ui fix: Made mpr more accessible from toolbar.

- extensions/vtk/src/OHIFVTKViewport.js
- extensions/vtk/src/commandsModule.js
- extensions/vtk/src/utils/vtkViewportSubscriptionManager.js
- yarn.lock
Syncs window leveling for vtkjs viewports in MPR 2D mode.
Closes: #558
Adds a temporary subscription manager for vtkjs viewports. This should be removed once we have more set-in-stone layout modes, and the management should be moved to the mode level.
> feat: 🎸 Synced Window Leveling

- platform/core/src/DICOMWeb/getAuthorizationHeader.js
- platform/core/src/DICOMWeb/getAuthorizationHeader.test.js
Our DICOMWeb server requires an Authorization token that is not derived from a "username:password" string. To make this as flexible as possible, `server.requestOptions.auth` can be a function that returns the entire Authorization header value.
As I added a test case for this feature, I also fixed up the input for the other test cases which passed an object instead of a string for the `auth` value.
> DICOMWeb auth function

- platform/core/src/studies/services/wado/retrieveMetadata.js
Simple change to make sure lazy study metadata load is enabled by default.
> OHIF-1002 Study lazy load should be true by default

- extensions/vtk/package.json
- yarn.lock
Includes `react-vtkjs-viewport` PRs 47, 48, 51 to improve computation of building `vtkjs` volume.
> feat: 🎸 Update vtk viewport for faster image reconstruction

- platform/ui/src/components/studyBrowser/StudyBrowser.js
- platform/ui/src/components/studyBrowser/ThumbnailEntryDragSource.js
- platform/viewer/cypress/integration/common/OHIFStudyViewer.spec.js
- platform/viewer/cypress/support/commands.js
Fixes #1001 
Prettier automatically formatted the code, that's why it seems to have more changes in this PR, but it was just a fix using the cypress alias to wait until all thumbnails were loaded and also I've added the `data-cy` attribute.
> fix: E2E Tests - Thumbnail loading

- extensions/cornerstone/src/toolbarModule.js
annotate, bidirectional and eraser had types as command but they should
be typed as setToolActive
Closes: 981
> fix: 🐛 set tools bidirectional, eraser and annotate command

- .circleci/config.yml
- package.json
We make a lot of changes but don't touch the lockfile on every PR. I don't think we need to include the branch name in the cache key. I'm checking this because the initial Checkout step in the CI process is taking 6 minutes to restore and then reupload the cache, which seems crazy: https://circleci.com/workflow-run/3938d5fd-3c82-4ff1-957e-6a04dd577df7
> ci: Set cache key to only use yarn.lock checksum

- platform/core/src/classes/metadata/StudyMetadata.js
Before this fix, SR series for a study show up sometimes, other times they cannot be seen in the left panel of the viewer.
The documentation for the _createDisplaySetsForSeries function says that it should return the display sets, however there is one case where it doesn't do that. This fixes the case so that it returns the display sets.
> Reliably show SR (structured report) series

- platform/viewer/package.json
The build is throwing weird errors on the Start command
> ci: Skip copying URL to clipboard on headless CI servers

- .webpack/webpack.base.js
- platform/i18n/src/locales/en-US/AboutModal.json
- platform/i18n/src/locales/en-US/index.js
- platform/i18n/src/locales/pt-BR/AboutModal.json
- platform/i18n/src/locales/pt-BR/index.js
- platform/ui/package.json
- platform/ui/src/components/userPreferencesModal/AboutModal.js
- platform/ui/src/design/styles/common/modal.styl
- platform/viewer/cypress/integration/common/OHIFStandaloneViewer.spec.js
- platform/viewer/cypress/integration/common/OHIFStudyViewer.spec.js
- platform/viewer/src/components/Header/Header.css
- platform/viewer/src/components/Header/Header.js
- yarn.lock
This PR adds the `Version number` near the OHIF's logo and in the About modal.
Also, it was added the `Build Number`, `Browser` and `OS` in the About Modal.
A new `i18n` namespace was added in Locize and translations for `en-US` and `pt-BR` were  made.
___
___
Fixes #529
> feat: Add browser info and app version

- platform/viewer/cypress/integration/pwa/OHIFExtensionVTK.spec.js
I just added a small improvement to avoid opening/closing the VTK menu before each test. Now, cypress will only click on the `VTK button` to open the toolbar. If the toolbar is already open, it won't click again.
> Improvement on VTK beforeEach hook

- platform/viewer/cypress/integration/common/OHIFCornerstoneToolbar.spec.js
- platform/viewer/cypress/support/commands.js
As discussed with @dannyrb, this PR is a quick fix in E2E tests that are causing intermittent failures, basically, by changing the mouse click from `top/center` to `center/top`.
> fix: E2E Intermittent Failures

- platform/viewer/src/appExtensions/MeasurementsPanel/ConnectedMeasurementTable.js
Is not possible to add Measurement Description if Relabel was not
previously selected
- On description measurement table item, set default text to '...' or a combination of label and description
#1013
> fix: 🐛 Desc of meas.table not being updated on properly

- platform/viewer/cypress/integration/common/OHIFCornerstoneToolbar.spec.js
- platform/viewer/src/components/ViewportGrid/ViewportPane.js
I've checked that #1077 is not a bug anymore -- when the layout changes to a lower number than the last active viewport, the first viewport is set as active automatically.
I've created this test to assert that the right viewport is being set to active when the layout changes.
---
Closes #1077
> e2e: set right viewport when layout is decreased

- platform/viewer/cypress/integration/common/OHIFStudyList.spec.js
The `MR` modality amount of studies was increased and since we are using hardcoded values for search result comparison, those constants needed to be updated.
> Fix for modalities search result

- .circleci/config.yml
1. `PR_OPTIONAL_VISUAL_TESTS`
2. Manual approval
3. Cypress E2E tests run with a custom command that enables `percy.io` executor
4. Captured snapshots are called out in output:
5. New status check appears for `percy`
6. Wait for comparison to process:
⚠️ We need to be careful about how much we test if we're going to stay under our quota.
Number of screenshots: 20
Checks at different dimensions: `375px` and `1280px` (2)
Number of browsers to test in: Chrome + FireFox (2)
20 * 2 * 2 = `80 screenshots`
We're limited to 30-days of history. Any important visual notes should be screen captured and shared on GitHub issues to preserve a reference. Images are archived in CircleCI as well. I'm unsure of for what duration.
Can only be initiated from a trusted branch (ie. off of `upstream`) or else …
> ci: optional visual test step

- .circleci/config.yml
- platform/viewer/package.json
Celebrated too quickly. WebGL tests crash when run with Electron.
> ci: fix webgl e2e test failures (only on CI)

- platform/ui/src/components/content/viewportDownloadForm/ViewportDownloadForm.js
We triggered two failing tests when we upgraded our version of Cypress. This PR attempts to address one of those failures. It allows for the `width` and `height` input fields to be empty.
Previously, they were `number` fields, and always had to have a value of at least `0`.
I tried not to stray too far from the task at hand, but I did consolidate a few things.
- As a user, I expect to be able to clear an input field before I begin typing
- Bad: `526` --> clear field --> `0` --> type "300" --> new value is `0300`
- Good: `526` --> clear field --> "" --> type "300" --> new value is `300`
- As a developer, I want my tests to pass ^_^
- Will likely conflict with: https://github.com/OHIF/Viewers/pull/1235
- This PR attempts to address other UX issues/bugs
- Related PR: …
> fix: allow empty values for dimensions

- .docker/Viewer-v2.x/entrypoint.sh
- platform/viewer/public/config/google.js
- platform/viewer/src/customHooks/useServer.js
- platform/viewer/src/googleCloud/api/GoogleCloudApi.js
Faster data access times for performance critical applications (i.e. primary radiologist reads) is requested by Google and it involves usage of cache that can sit transparently in front of the Cloud Healthcare API.
Currently OHIF does not allow to configure custom Cloud Healthcare API endpoint (hardcoded endpoint is https://healthcare.googleapis.com/v1beta1), so it makes impossible to use caching server.
This change adds such feature.
> Custom Healthcare API endpoint

- platform/viewer/src/connectedComponents/ViewerRetrieveStudyData.js
StudyMetadata is being mistakenly purged once we load a study into the viewer and blocking the 2D MPR button component to check if the current study/series is reconstructable.
As an user: 
- I should be able to open a study twice in a row* and be able to see the 2D MPR button everytime it is required.
It should fix the issue number 1 reported on #1326 :
> Issue 1: 2D MPR button is not displayed if user clicks on Study List and selects the same Patient
> When user is viewing a Patient series that is reconstructable the 2D MPR button will be displayed as expected. But if user decides to click on Study List link and then selects the same Patient, the 2d MPR button will not be displayed anymore. If user reloads the page, the button will be displayed again.
> 
> Although I tested this in …
> fix: 🐛 Metadata is being mistakenly purged

- platform/core/src/studies/services/wado/studyInstanceHelpers.js
- platform/viewer/src/lib/localFileLoaders/dicomFileLoader.js
We previously had a palette color cache object which stored retrieve palette color lookup tables. This was accidentally removed during the switch to the monorepo, which caused some images to stop displaying (#1350).
> Add palette color cache object back to core (fix #1350)

- platform/viewer/package.json
The dependency `ffmpeg-installer` was added in order to fix one of failures that we were having on CircleCI related to the videos recorded by Percy during visual regression tests.
But since we are not recording the execution of the tests anymore, there's no point in keeping this dependency on the project's package list. 
> Removing dependency ffmpeg-installer

- extensions/cornerstone/package.json
- extensions/cornerstone/src/init.js
- extensions/vtk/package.json
- platform/core/package.json
- platform/viewer/package.json
- yarn.lock
Once the latest cornerstone-tools is published we can update package.json and merge this. It adds DICOM Group 6xxx overlay rendering to the viewer, which people have been asking for for a long time.
> Add DICOM Group 6xxx Overlay Plane rendering

- platform/core/src/studies/services/wado/retrieveMetadataLoader.js
- platform/core/src/utils/isDisplaySetReconstructable.js
- platform/viewer/src/connectedComponents/ViewerRetrieveStudyData.js
This addresses the issues brought up in #1280 and very slightly improves the horrible error handling we have which made this issue hard to debug.
> Fix issues with isDisplaySetReconstructable when we have empty tags

- platform/ui/src/components/contextMenu/ContextMenu.js
- platform/viewer/src/connectedComponents/ToolContextMenu.js
Hi.
This PR prevents the native context menu from appearing when right-clicking on a measurement or angle (https://github.com/OHIF/Viewers/issues/1406).
@dannyrb, can you review, please?
> fix: prevent the native context menu from appearing when right-clicking on a measurement or angle (https://github.com/OHIF/Viewers/issues/1406)

- .eslintrc.json
- package.json
- yarn.lock
Adds a new eslint rule to prevent spreading props. The main goal is to avoid as much as possible the use of props spreading like: 
```javascript
const Component = (props) => <Component {...props} />
```
This ends up being bad for tests since we can't know exactly what props are being passed and it can make things very confusing/difficult to debug.
--
Related: https://github.com/OHIF/Viewers/pull/1504#discussion_r390704222
> feat: Add new eslint rule: props-no-spreading

- platform/ui/doczrc.js
- platform/ui/package.json
- platform/ui/src/components/Button/Button.mdx
- platform/ui/src/components/ButtonGroup/ButtonGroup.mdx
- platform/ui/src/components/Icon/icon.mdx
- platform/ui/src/components/Input/Input.mdx
- platform/ui/src/components/Label/Label.mdx
- platform/ui/src/components/Typography/Typography.mdx
- platform/ui/src/gatsby-theme-docz/components/Header/index.js
- platform/ui/src/gatsby-theme-docz/components/Layout/index.js
- platform/ui/src/gatsby-theme-docz/components/Sidebar/index.js
- platform/ui/src/gatsby-theme-docz/theme.css
- platform/ui/src/views/StudyList/StudyList.mdx
- platform/ui/tailwind.config.js
Create `docz` theme/page to better showcase **`Views`**.
It was created customization of the standard `docz` theme to make a switchable menu.
The theme files were basically copied from the [original `gatsby-theme-docz` components](https://github.com/doczjs/docz/blob/v2.2.0/core/gatsby-theme-docz/src/components) and minor changes were made to accomplish our needs.
**Menu Opened**
**Menu Closed**
> feat: uiv2 docz custom page

- platform/ui/src/assets/icons/arrow-down.svg
- platform/ui/src/components/Icon/getIcon.jsx
- platform/ui/src/views/StudyList/components/StudyListPagination.js
**OHIF-40**
- Per page `select` is now using an icon to make it be displayed with the same style in all browsers.
- Buttons padding/width is fixed.
**(expected)**
_There's a slight fix to do in the arrow-down icon. I'll ask Dan to export the correct icon for us to be used in the `select`_.
> fix: UI v2 Pagination Fixes

- platform/ui/src/components/measurementTable/MeasurementTableItem.styl
Fixes issue https://github.com/OHIF/Viewers/issues/1377 delete button was disappearing due to overflowing into a row new when spanish is the selected language
> fix: [measurements panel] rendering delete button when text is too wide for parent div

- platform/viewer/src/utils/initWebWorkers.js
- platform/viewer/src/utils/initWebWorkers.test.js
When embedded in a SPA, the `initWebWorkers` method should only be called once per page.
When the DOM element the viewer is attached to is rendered within a React component, the `installViewer` method may be called multiple times per page if user navigation is causing that DOM element to be created and removed multiple times.
Because of [this line of code](https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/master/src/imageLoader/webWorkerManager.js#L153), Cornerstone will throw an exception if this is tried. Cornerstone does not export the control object such that consumers could base their logic on that, so I created my own control object.
This gets past the exception within Cornerstone, but causes the logs to be noisy as multiple other parts of the viewer are loaded …
> Only permit web workers to be initialized once.

- platform/ui/index.js
- platform/ui/src/contextProviders/ModalProvider.js
- platform/ui/src/contextProviders/index.js
We need a context provider to wrap our application and be able to access the context on any place in the application.
This context provider let us to display modals triggered by any internal component on our application. 
The is no preview of it yet as its not an UI component and jsut a context provider implementation. 
Once we have a Modal Component created we should use then together.
> OHIF-43: Create Modal Context Provider 

- platform/core/src/redux/reducers/viewports.js
In https://github.com/OHIF/Viewers/pull/1544, I introduced `immer` to avoid wasteful mutation of state in `viewports` reducer.
But, it turns out that `Immer automatically freezes any state trees that are modified using produce.`
https://immerjs.github.io/immer/docs/freezing
This is causing some issue - I noticed one, but there could be more.
e.g. You start `2D MPR`, then `Exit 2D MPR` and then try to start it again - it fails with an error in console.
It turns out that rule of immutability of objects in Redux state is broken in some places.
e.g. `mpr2d` command in `vtk` extension.
It grabs a `viewportSpecificData` off the Redux state, 
https://github.com/OHIF/Viewers/blob/16866a47a0e8d6b9200cb503da714a9a29773bdb/extensions/vtk/src/commandsModule.js#L222-L223
passes it to `setMPRLayout` …
> Urgent: disable autoFreeze of immer, even in dev mode

- platform/ui/index.js
- platform/ui/src/components/EmptyStudies/EmptyStudies.js
- platform/ui/src/components/EmptyStudies/EmptyStudies.mdx
- platform/ui/src/components/EmptyStudies/index.js
- platform/ui/src/components/index.js
- platform/ui/src/views/StudyList/components/StudyListTable.js
**OHIF-51**
Creates an EmptyStudies component to be used in the StudyList when the study list is empty.
> feat: UI v2 EmptyStudies Component

- extensions/dicom-segmentation/src/OHIFDicomSegSopClassHandler.js
- extensions/dicom-segmentation/src/components/SegmentationPanel/SegmentationPanel.js
- platform/core/src/classes/metadata/StudyMetadata.js
- platform/viewer/src/components/ViewportGrid/ViewportGrid.js
#1564
This fix the issue of segmentations not being loaded. 
Updated the useEffect that calls loadAndCacheDerivedDisplaySets inside ViewportGrid to watch studies along with viewportData.
> 1564: Fix segmentation not loading

- platform/core/src/classes/metadata/StudyMetadata.js
- platform/viewer/public/config/default.js
- platform/viewer/src/connectedComponents/ViewerRetrieveStudyData.js
Further enhancements to series loading, to be able to show first meaningful display at the earliest.
Concurrent loading of series metadata fills the request queue with metadata requests. 
Requests for thumbnail and viewport image get queued up after all the metadata requests.
As browser limits concurrent requests to a domain to 4, the thumbnail image and viewport image fetch requests get blocked.
Ultimately, thumbnail and viewport image is displayed only after all (actually, all - 3) metadata requests are done.
This could be a long wait,  if number of series are more and especially if server is slow to responding metadata requests. (https://github.com/OHIF/Viewers/issues/1536)
Solution implemented is to limit the max concurrent series metadata requests to 3 so that it leaves room for more …
> Limit concurrent series metadata requests

- platform/ui/src/assets/styles/styles.css
- platform/ui/src/components/NavBar/NavBar.jsx
- platform/ui/src/components/Thumbnail/Thumbnail.jsx
- platform/ui/src/components/ViewportActionBar/ViewportActionBar.jsx
- platform/ui/src/components/ViewportGrid/ViewportGrid.jsx
- platform/ui/src/views/StudyList/StudyList.mdx
- platform/ui/src/views/StudyList/components/Header.js
- platform/ui/src/views/ToolbarHeader/ToolbarHeader.mdx
- platform/ui/src/views/Viewer/components/Header.js
- platform/ui/src/views/Viewer/components/ViewportToolBar.js
Fix: Active Viewport border width discrepancy causes resize
Fix: Z-index issue for “annotation tools” overlay Viewport ActionBar
Fix: Header shouldn’t be sticky on Viewer Route
Fix scrollbar on Firefox
- Firefox scroll bars
- Tooltip 
- Non-Sticky header on Viewer
- Border width change without resize
> OHIF UI-v2 Issues

- docs/latest/deployment/index.md
Update to the Deployment section of documentation to explain using the ?URL parameter and JSON instead of DicomWeb.
First contribution - so please let me know if I have missed anything or messed up the process!
I created a new branch for this update - not sure if this should be on the 'gh-pages' branch when doing documentation?
Also, was not sure if I need to do any build/test for documentation for git-book? or is this update sufficient.
thanks
> updated deployment section with info for using JSON 

- platform/viewer/src/routes/routesUtil.js
This route support appears to have been accidentally removed and it is not caught by any tests.
> fix: Add IHEInvokeImageDisplay routes back into viewer

- platform/core/src/utils/metadataProvider/fetchPaletteColorLookupTableData.js
Addresses https://github.com/OHIF/Viewers/issues/1689. Instead of using a Uint8Array for all lookup table byte arrays, first check to see whether the palette colors are 8 or 16 bits, and use the appropriately sized Uint array. Thanks @swederik.
> use bit-appropriate array for palette lookup tables

- platform/viewer/src/App.js
This can help developers explore and access some
internal functionaltiy for debugging in the console.
For example, this command can download the currently
viewed study:
ohif.app.commandsManager.runCommand("downloadAndZip", {listOfUIDs: [window.location.href.split("/").pop()]})
TODO: collect this example and other handy functions on a wiki page
Co-authored-by: dannyrb <danny.ri.brown@gmail.com>
- [x ] Brief description of changes
- [n/a] Links to any relevant issues
- [n/a ] User cases if changes impact the user's experience
> feat: expose some app internals as window.app

- platform/core/src/classes/metadata/StudyMetadata.js
- platform/viewer/cypress/integration/common/OHIFStudyList.spec.js
- platform/viewer/cypress/support/commands.js
- platform/viewer/src/connectedComponents/ViewerRetrieveStudyData.js
Description from #1776 
> When the same study containing SEG/SR series is opened for the second time, segmentations do not show up in the drop-down. After "Empty cache and hard reload", everything loads as normal.
**FIXED:** The `derivedDisplaySets` wasn't being cached in the `studyMetadata`.
---
@JamesAPetts can you please review it? -- thanks!
> Fix: #1776 - Segmentations not loading

- extensions/cornerstone/src/init.js
- extensions/cornerstone/src/utils/measurementServiceMappings/ArrowAnnotate.js
- extensions/cornerstone/src/utils/measurementServiceMappings/Bidirectional.js
- extensions/cornerstone/src/utils/measurementServiceMappings/EllipticalRoi.js
- extensions/cornerstone/src/utils/measurementServiceMappings/Length.js
- extensions/cornerstone/src/utils/measurementServiceMappings/constants/supportedTools.js
- extensions/cornerstone/src/utils/measurementServiceMappings/measurementServiceMappingsFactory.js
- extensions/cornerstone/src/utils/measurementServiceMappings/utils/getHandlesFromPoints.js
- extensions/cornerstone/src/utils/measurementServiceMappings/utils/getPointsFromHandles.js
- extensions/cornerstone/src/utils/measurementServiceMappings/utils/getSOPInstanceAttributes.js
- extensions/measurement-tracking/src/panels/PanelMeasurementTableTracking/index.js
- platform/core/src/services/MeasurementService/MeasurementService.js
- platform/ui/src/components/MeasurementTable/MeasurementTable.jsx
One way cornerstoneTools measurements => measurements service.
Do we need to implement the toAnnotation functions at the current time? They are unused for now, and likely not a priority until we have multiple sources of annotations (cornerstoneTools, vtk).
The originally proposed pattern of having each measurement fit to one SCOORD type doesn't gel well with SR, so we'll need to discuss @dannyrb.
I removed mathematical calculations from the UI, as these can be cashed in the measurement service representation, and shouldn't be calculated every render.
> v2 - Feat/ohif 156

- extensions/default/src/ViewerLayout/ToolbarButtonNestedMenu.jsx
- extensions/default/src/ViewerLayout/index.jsx
- extensions/default/src/getToolbarModule.js
- platform/core/src/services/ToolBarService/ToolBarService.js
- platform/ui/src/components/ToolbarButton/ToolbarButton.jsx
If a tool in the more menu is activated the "..." icon of the more menu should be replaced with the active tool.
If an action in the toolbar menu is clicked the more menu should close and the icon should remain as it is ("..." or active tool from the more menu).
> OHIF-151: Replace the "..." icon in more menu with active tool in menu.

- README.md
Change `window.OHIFStandaloneViewer` to `window.OHIFViewer`, since the former is undefined. 
> Fix README.md Quick Start Deployment instructions

- extensions/cornerstone/package.json
- extensions/default/package.json
- extensions/dicom-html/package.json
- extensions/dicom-rt/package.json
- extensions/dicom-segmentation/package.json
- extensions/dicom-sr/package.json
- extensions/dicom-sr/src/getSopClassHandlerModule.js
- extensions/measurement-tracking/package.json
- extensions/vtk/package.json
- platform/core/package.json
- platform/viewer/package.json
Fixes editability of bidirectional tool after import by this change to dcmjs: https://github.com/dcmjs-org/dcmjs/pull/133
Sometime between CST 4.3 and 4.16.1 some fields where added to the bidirectional tool schema which are actually breaking schema changes, the above PR updates the dcmjs cornerstone adapter to deal with this.
> [OHIF-231] Update dcmjs to fix bidirectional issue.

- extensions/dicom-sr/src/OHIFCornerstoneSRViewport.js
- extensions/dicom-sr/src/getSopClassHandlerModule.js
- extensions/measurement-tracking/src/panels/PanelMeasurementTableTracking/index.js
- platform/viewer/src/components/ViewportGrid.jsx
Defer processing of SR until it is loaded in the viewport, to decrease initial viewer load times if hundreds of SRs present.
> [OHIF-235] Lazy processing of DICOM SR for viewport.

- extensions/measurement-tracking/src/viewports/TrackedCornerstoneViewport.js
- extensions/measurement-tracking/src/viewports/ViewportLoadingIndicator.js
> OHIF-250: The cornerstone viewport should not display "Loading 0%" when attempting to view an unloaded image. It should say "Loading"

- extensions/dicom-sr/src/OHIFCornerstoneSRViewport.js
- extensions/measurement-tracking/src/panels/PanelStudyBrowserTracking/PanelStudyBrowserTracking.jsx
- extensions/measurement-tracking/src/viewports/TrackedCornerstoneViewport.js
- platform/ui/src/components/ThumbnailNoImage/ThumbnailNoImage.jsx
- platform/ui/src/components/ThumbnailTracked/ThumbnailTracked.jsx
- platform/ui/src/contextProviders/ViewportGridProvider.jsx
**Part 1**
Viewports with matching displaysets currently use the same letter label:
- Viewport 1: DisplaySet 1 --> A
- Viewport 2: DisplaySet 1 --> A
- Viewport 3: DisplaySet 2 --> B
Regardless of the displayset, lettering should be sequential:
- Viewport 1: DisplaySet 1 --> A
- Viewport 2: DisplaySet 1 --> B
- Viewport 3: DisplaySet 2 --> C
**Part 2**
Each thumbnail should list each viewport label they are displayed in. For example, if DisplaySet 1 is the displayset in all 9 viewports in a 3x3 grid, it's label should be: A, B, C, D, E, F, G, H, I
A provisional design was created for when the series is being shown in more than 3 viewports.
Series in 3 viewports:
Series in more than 3 viewports (icon with a tooltip):
Tracked Series in more than 3 viewports:
Viewport:
> fix: OHIF-219 - Viewport Labels should be sequential

- platform/ui/src/components/ViewportPane/ViewportPane.jsx
- platform/viewer/src/components/ViewportGrid.jsx
Block canvas events if viewport is not active.
> OHIF-308: The first `mousedown` or `click` on a viewport should not place an annotation if the viewport is not already active

- platform/ui/src/components/ViewportActionBar/ViewportActionBar.jsx
Information text will be truncated and the max-width will depend on the num of viewport cols. When the mouse hovers over the text, it will display its complete information.
> fix: OHIF-215 - Patient information should truncate w/ ellipsis instead of expanding box

- .netlify/build-deploy-preview.sh
- netlify-lerna-cache.sh
- netlify-lerna-restore.sh
- netlify.toml
- package.json
- platform/ui/gatsby-node.js
* fix: Use same config for branch deploys as for deploy previews
* chore: remove unnecessary duplicate build-deploy-preview.sh file
* fix: Attempt to workaround Netlify cache issues for Lerna repos
* chore: Remove useless debug file
* fix: try to make Gatsby less slow
> fix: Use same config for branch deploys as for deploy previews (#1893)

- extensions/cornerstone/src/commandsModule.js
- extensions/cornerstone/src/init.js
- extensions/dicom-sr/src/OHIFCornerstoneSRViewport.js
The SR viewport just needed to be emit an event to register itself to the cornerstone extension's tracker, like the tracked viewport does.
> OHIF-328 up/down arrows keys on SR viewport.

- extensions/cornerstone/package.json
- extensions/cornerstone/src/init.js
- extensions/dicom-rt/package.json
- extensions/dicom-segmentation/package.json
- extensions/dicom-sr/package.json
- extensions/measurement-tracking/package.json
- extensions/vtk/package.json
- platform/viewer/package.json
- yarn.lock
- Persist ArrowAnnotations if no label is given.
- Correctly show measurement tracking notifications after arrow annotate measurement instead of getting conflicting popups.
> Arrow Annotate workflow updates.

- extensions/dicom-sr/src/OHIFCornerstoneSRViewport.js
- extensions/measurement-tracking/src/viewports/TrackedCornerstoneViewport.js
> OHIF-311: The left/right annotation navigation arrows in the viewport's actionbar should always be visible

- extensions/cornerstone/package.json
- extensions/dicom-rt/package.json
- extensions/dicom-segmentation/package.json
- extensions/vtk/package.json
- extensions/vtk/src/OHIFVTKViewport.js
- platform/core/package.json
- platform/viewer/cypress/support/commands.js
- platform/viewer/package.json
- yarn.lock
RE: #1957  https://github.com/OHIF/react-vtkjs-viewport/pull/103
Switched to using the `cornerstone-tools` `requestPoolManager`, so that we don't send 1000 requests at the same time to the PACS on `imageDataObject.loadImage()`.
This is a breaking change, as we the `imageDataObject` no-longer has `insertPixelDataPromises`, instead the consumer may subscribe to an `imageDataObject`'s o`nPixelDataInserted` and/or `onAllPixelDataInserted `hooks. All the relavent examples have been updated to reflect this. As we are still pre-1.0, I have avoided a major version bump.
> feat: 🎸 Update react-vtkjs-viewport usage to use requestPool

- .netlify/build-deploy-preview.sh
- package.json
> fix: Avoid lerna:restore unless we are on Netlify (closes #1926, #1996)

- extensions/cornerstone/src/initCornerstoneTools.js
Hello, I am an intern at Google investigating ways in which to get optimal performance out of medical image viewers that integrate with the Google Healthcare API. One major optimization I've found is increasing the number of simultaneous requests made when fetching a series of DICOM instances/frames. So this PR adds a configuration to `cornerstoneTools.stackPrefetch` to increase the number of simultaneous http requests.
With the introduction of HTTP/2, there is no longer a limit of 6 simultaneous requests to a specific origin. Instead, one connection is made to a given origin and a hypothetically infinite number of requests can be made through that one connection (although browsers such as chrome do eventually limit these connections which appears to be around [100 …
> Increase simultaneous requests

- platform/viewer/src/connectedComponents/ViewerRetrieveStudyData.js
improve filter/promote to be applied on multiple series instances
✅ Closes: 1532
- Changes will improve current filter/promote feature to accept multiple series instances.
https://github.com/OHIF/Viewers/issues/1532
- User can filter/promote one or many series.
- Current feature is: Consider part valid part of url `viewer/1.3.6.1.4.1.25403.345050719074.3824.20170126085406.1?SeriesInstanceUID=2.25.856992923281239003733479634608709215918`
- New feature is: Consider part valid part of url `viewer/1.3.6.1.4.1.25403.345050719074.3824.20170126085406.1/?seriesInstanceUID=1.3.6.1.4.1.25403.345050719074.3824.20170126085406.2,2.25.37453262811593903479 …
> feat: 🎸 Filter/promote multiple series instances

- extensions/cornerstone/package.json
- yarn.lock
This PR updates the version of react-cornerstone-viewport to 4.0.2, which includes [this change](https://github.com/cornerstonejs/react-cornerstone-viewport/pull/101). This allows the benefits of https://github.com/OHIF/Viewers/pull/2000 to take effect.
@dannyrb 
> Update react-cornerstone-viewport to version 4.0.2

- extensions/dicom-html/src/OHIFDicomHtmlSopClassHandler.js
- extensions/dicom-microscopy/src/DicomMicroscopySopClassHandler.js
- extensions/dicom-pdf/src/OHIFDicomPDFSopClassHandler.js
- extensions/dicom-rt/src/OHIFDicomRTStructSopClassHandler.js
- extensions/dicom-segmentation/src/getOHIFDicomSegSopClassHandler.js
- platform/core/src/classes/OHIFStudyMetadataSource.js
- platform/core/src/classes/metadata/StudyMetadata.js
- platform/core/src/utils/isLowPriorityModality.js
- platform/viewer/src/connectedComponents/Viewer.js
- platform/viewer/src/connectedComponents/ViewerLocalFileData.js
- platform/viewer/src/connectedComponents/ViewerRetrieveStudyData.js
- platform/viewer/src/routes/StandaloneRouting.js
RE: #1994 
Update:
- Fix regression so that we still have low priority modalities which are sorted after.
- Switch to a clever insert rather than a sort, as sorting by SeriesNumber + SeriesDate/SeriesTime on each displaySet creation was too slow.
> [IDC-1994] Sort series list by SeriesNumber, and sort by same SeriesNumber by date/time.

- extensions/cornerstone/package.json
- extensions/dicom-html/package.json
- extensions/dicom-rt/package.json
- extensions/dicom-segmentation/package.json
- extensions/dicom-segmentation/src/getSourceDisplaySet.js
- extensions/vtk/package.json
- platform/core/package.json
- platform/viewer/package.json
- platform/viewer/src/connectedComponents/ViewerLocalFileData.js
- yarn.lock
RE: #2017 
related: https://github.com/dcmjs-org/dcmjs/pull/146
> DICOM Segmentation objects can have their referenced data encoded in multiple ways. The dcmjs cornerstone adapter now parses a greater selection, tested on a lot of TCIA cases.
Tested on a slew of IDC cases and there seems to be no issues.
> [IDC-2017] Harden segmentation import to support more SEGs

- platform/viewer/public/config/idc.js
- platform/viewer/src/connectedComponents/ViewerRetrieveStudyData.js
If you are using a backend that does not support multiple valued QIDO filters, it is not sufficient to assume this backend is google cloud. Although setting `enableGoogleCloudAdapter` to true will split up these calls (as google does not support this), setting `splitQueryParameterCalls` will also split up query filters into multiple calls, if your dicomweb server does not support multi-valued QIDO filters.
> Split query parameter calls with app config.

- extensions/debugging/src/DebugReportModal.js
- extensions/dicom-rt/src/components/RTPanel/RTPanel.js
- extensions/dicom-rt/src/tools/RTStructDisplayTool.js
- extensions/dicom-rt/src/tools/modules/rtStructModule.js
- extensions/dicom-rt/src/utils/drawCanvasCrosshairs.js
- extensions/dicom-segmentation/src/components/SegmentationPanel/SegmentationPanel.js
- extensions/dicom-segmentation/src/init.js
- extensions/dicom-segmentation/src/tools/DICOMSegTempCrosshairsTool.js
- extensions/dicom-segmentation/src/tools/TOOL_NAMES.js
- extensions/dicom-segmentation/src/utils/drawCanvasCrosshairs.js
RE: #1672 
I've added temporary crosshairs that stay until you scroll/move from the segment, as discussed on a previous call.
I added highlighting for the RT contours, which we might as well keep as well, but without the crosshairs it really wasn't clear sometimes what was being highlighted.
I'd like to add highlighting for the DICOM SEG segments, but this actually isn't straight forward with the way our labelmaps currently work. We currently have each segment set at 100% opacity, and a global opacity slider, so we can't highlight one segment for a frame without changing the way our current opacity slider works. I think we can do this in a hacky way, but won't do this unless it is priority @fedorov .
We already had good indication in the MPR view with the crosshairs, so that is left as …
> [IDC-1672] Highlight SEG segment/ RT structure when click to jump.

- extensions/measurement-tracking/src/contexts/TrackedMeasurementsContext/measurementTrackingMachine.js
- extensions/measurement-tracking/src/contexts/TrackedMeasurementsContext/promptTrackNewSeries.js
- extensions/measurement-tracking/src/contexts/TrackedMeasurementsContext/promptTrackNewStudy.js
1.  Adding measurements to existing report
- Caused by short-circuit in logic for `promptTrackNewSeries`
2.  Creating a new report while tracking measurements
- Note added in PR. Issue identified, not yet resolved.
3.  Canceling new report while tracking measurements
- Caused by short-circuit in logic for `promptTrackNewSeries`
4.  Measurements spanning multiple studies
- Similar logic short-circuit issue in `promptTrackNewStudy`
> Misc. workflow fixes [OHIF-363]

- extensions/dicom-tag-browser/src/components/DicomBrowserSelect.js
- extensions/dicom-tag-browser/src/components/DicomBrowserSelectItem.css
- extensions/dicom-tag-browser/src/components/DicomTagBrowser.css
- extensions/dicom-tag-browser/src/components/DicomTagBrowser.js
- platform/viewer/src/index.js
RE #2049.
`dcmjs` stores tags as properties on objects, so they are "unordered" with respect to their DICOM tags. This PR adds a mapping layer between the data model and the rendered table to the DICOM tag extension, in order to sort these tags for rendering. A mapping layer was necessary as the "single-list-of-rows" approach made sorting tags within sequences troublesome. The top level tags are sorted, and tags within sequence items are also sorted.
The sorting does come at a non-negligable computational cost for very large nested datasets such as RTSTRUCT or SR, sometimes taking a few seconds to load. We could make this better in the future by lazy loading + sorting groups if we decide to work on group expansion.
Additionally I added a space between indent carets (`>`) and the tag, as …
> [IDC-2049] Sort Tags in Tag browser split items in sequences, add indent after space.

- extensions/cornerstone/package.json
- platform/viewer/cypress/integration/pwa/OHIFExtensionHTMLPDF.spec.js
RE: #2060 , the update: https://github.com/cornerstonejs/react-cornerstone-viewport/pull/105
> Update react-cornerstone-viewport for performance improvements

- platform/viewer/public/manifest.json
Issue: https://github.com/OHIF/Viewers/issues/2052
This changes the value of the start_url property in the manifest.json from "./index.html" to "./"
When the installed PWA app is launched, the url set in the start_url in the manifest.json is initially opened.
But the problem is ./index.html, which is currently set for the value of the property, has no matching routes, the following error is shown.
After changing the value to "./" this shows the main page.
> PWA start url

- platform/core/src/DICOMSR/utils/findMostRecentStructuredReport.js
- Call getInstanceCount() instead of checking `instances.length`. The length did not work, as the instances property doesn't exist on the objects, and so all of the structured reports are ignored. This is why they don't show up in the measurements pane.
- likely fixes #1714, fixes #1662, fixes #1907
- might also be related to #1679, #1763, #1707 
- none
- @swederik (added the code there)
> fix: use SeriesMetadata method instead of property

- extensions/measurement-tracking/src/_shared/setCornerstoneMeasurementActive.js
for "clicking annotation arrows"; as doing _nothing_ if the image isn't loaded yet is perfectly okay
> fix: swallow update-image error

- extensions/vtk/src/commandsModule.js
- extensions/vtk/src/index.js
#2005 
If the browser does not support WebGL 2.0, and the data is too large to fit in 2D Texture memory, throw an error notification to alert the user when attempting to view MPR.
> [IDC-2005] Throw error if data too large in WebGL 1 enabled browser

- extensions/vtk/package.json
- extensions/vtk/src/toolbarModule.js
- platform/viewer/cypress/integration/pwa/OHIFExtensionVTK.spec.js
- platform/viewer/cypress/support/aliases.js
- yarn.lock
Update to react-vtkjs-viewport 0.14.1 to get this patch: https://github.com/OHIF/react-vtkjs-viewport/pull/121
Remove now unneeded rotate tool.
> Update crosshairs UI and fix bug where you could scroll offscreen.

- platform/ui/src/contextProviders/DialogProvider.js
- platform/ui/src/contextProviders/ModalProvider.js
- platform/ui/src/contextProviders/SnackbarProvider.js
Simple Refactor
Reorders variable assignments in Providers before they are being accessed. Mentioned in https://github.com/OHIF/Viewers/issues/2105
> fix: Reordered to prevent variable access before initialization

- platform/viewer/src/utils/getUserManagerForOpenIdConnectClient.js
Hello @dannyrb ,
I have removed the hard-coded  `loadUserInfo: true,` when creating the UserManager. This flag causes an additional call to the userinfo endpoint as described in the oidc-client documents:
> loadUserInfo (boolean, default: true): Flag to control if additional identity data is loaded from the user info endpoint in order to populate the user's profile.
With AzureAD this call can cause a 401 as described in this ticket: https://github.com/IdentityModel/oidc-client-js/issues/1028
By hard-coding this to true, it is not possible to work around this issue. (If not configured this value is true by default anyway, which makes this even more useless) 
Without this line of code it is now possible to disable the loadUserInfo and therefore make the oidc authentication with AzureAD …
> Remove hard-coded loadUserInfo to make it configurable

- extensions/dicom-sr/src/getSopClassHandlerModule.js
- extensions/dicom-sr/src/utils/isRehydratable.js
- extensions/dicom-sr/src/viewports/OHIFCornerstoneSRViewport.js
- extensions/measurement-tracking/src/_shared/setCornerstoneMeasurementActive.js
- extensions/measurement-tracking/src/contexts/TrackedMeasurementsContext/TrackedMeasurementsContext.jsx
- extensions/measurement-tracking/src/contexts/TrackedMeasurementsContext/measurementTrackingMachine.js
- extensions/measurement-tracking/src/viewports/TrackedCornerstoneViewport.js
- package.json
- yarn.lock
Fixed an issue where SR Viewports do not show prompt to load measurements when they are first dragged/dropped, since they haven't been parsed yet.
> fix: Call load if necessary before rehydration prompt (OHIF-369)

- platform/viewer/src/utils/initWebWorkers.js
As each webworker costs RAM and machines with more cores are available (like AMD puts out or XEON) this can and does easily crash the processes.
Added a limit of six as a variable, but it could also be defined in a way overridable during the build process.
PS: In general, many more places in the code would benefit from BUILD time variables.
> added MAX_CONCURRENCY limit to prevent crashes on bigger machines

- .circleci/config.yml
Missed some executors, and Gitbook fails to install above the last node LTS release
> ci: Fix release workflow

- extensions/cornerstone/package.json
- extensions/dicom-html/package.json
- extensions/dicom-rt/package.json
- extensions/dicom-segmentation/package.json
- extensions/dicom-segmentation/src/components/SegmentationPanel/SegmentationPanel.js
- extensions/dicom-segmentation/src/getOHIFDicomSegSopClassHandler.js
- extensions/dicom-segmentation/src/loadSegmentation.js
- extensions/dicom-tag-browser/package.json
- extensions/vtk/package.json
- extensions/vtk/src/OHIFVTKViewport.js
- platform/core/package.json
- platform/ui/src/contextProviders/SnackbarProvider.js
- platform/viewer/package.json
- platform/viewer/src/components/ViewportGrid/ViewportGrid.js
- yarn.lock
WIP: this is a work in progress PR
based on the logic implemented in https://github.com/dcmjs-org/dcmjs/pull/155 as described in point (2) in https://github.com/OHIF/Viewers/issues/2164#issuecomment-732240664.
dcmjs can return an array of LabelMaps if segments are overlapping. In this PR we load the labelMaps in the segmentation display and we define as active the first one https://github.com/OHIF/Viewers/compare/master...Punzo:IDC2164?expand=1#diff-0835569e2ca4d01ae2d66254833e8ab800b668a0cdce905e21c127e05c775f9bR105
Still to do:
- the UI does not allow to change the active label Map. It would be necessary to have in the UI, widget to see all the loaded labelMaps and pick the active one, so that one can change between:
- at the moment, when using MPR mode (vtk.js) only the active one will …
> Re #2164: load overlapping segmentation WIP

- platform/viewer/public/config/google.js
The Cloud Healthcare API and its DICOMweb API are in GA (v1).
> Update Google Healthcare API endpoint from v1beta1 to v1

- extensions/cornerstone/package.json
- extensions/dicom-html/package.json
- extensions/dicom-rt/package.json
- extensions/dicom-segmentation/package.json
- extensions/dicom-tag-browser/package.json
- extensions/vtk/package.json
- platform/core/package.json
- platform/viewer/package.json
- yarn.lock
#2252 
dcmjs
* @ohif/core: 0.17.0 → 0.17.2
* @ohif/extension-cornerstone: 0.17.0 → 0.17.2
* @ohif/extension-dicom-html: 0.17.0 → 0.17.2
* @ohif/extension-dicom-rt: 0.17.0 → 0.17.2
* @ohif/extension-dicom-segmentation: 0.17.0 → 0.17.2
* @ohif/extension-dicom-tag-browser: 0.17.0 → 0.17.2
* @ohif/extension-vtk: 0.17.0 → 0.17.2
* @ohif/viewer: 0.17.0 → 0.17.2
> Update dependency: dcmjs@0.17.2 to fix Failure to load a valid SEG object due to incorrect expectations about ReferencedSegmentNumber

- extensions/cornerstone/package.json
- extensions/dicom-html/package.json
- extensions/dicom-rt/package.json
- extensions/dicom-segmentation/package.json
- extensions/dicom-tag-browser/package.json
- extensions/vtk/package.json
- platform/core/package.json
- platform/viewer/package.json
- yarn.lock
dcmjs
* @ohif/core: 0.17.2 → 0.18.1
* @ohif/extension-cornerstone: 0.17.2 → 0.18.1
* @ohif/extension-dicom-html: 0.17.2 → 0.18.1
* @ohif/extension-dicom-rt: 0.17.2 → 0.18.1
* @ohif/extension-dicom-segmentation: 0.17.2 → 0.18.1
* @ohif/extension-dicom-tag-browser: 0.17.2 → 0.18.1
* @ohif/extension-vtk: 0.17.2 → 0.18.1
* @ohif/viewer: 0.17.2 → 0.18.1
> Update dependency: dcmjs@0.18.1

- extensions/cornerstone/package.json
- extensions/dicom-html/package.json
- extensions/dicom-rt/package.json
- extensions/dicom-segmentation/package.json
- extensions/dicom-tag-browser/package.json
- extensions/vtk/package.json
- platform/core/package.json
- platform/viewer/package.json
- yarn.lock
dcmjs
* @ohif/core: 0.18.1 → 0.18.2
* @ohif/extension-cornerstone: 0.18.1 → 0.18.2
* @ohif/extension-dicom-html: 0.18.1 → 0.18.2
* @ohif/extension-dicom-rt: 0.18.1 → 0.18.2
* @ohif/extension-dicom-segmentation: 0.18.1 → 0.18.2
* @ohif/extension-dicom-tag-browser: 0.18.1 → 0.18.2
* @ohif/extension-vtk: 0.18.1 → 0.18.2
* @ohif/viewer: 0.18.1 → 0.18.2
> Update dependency: dcmjs@0.18.2

- extensions/cornerstone/package.json
- yarn.lock
react-cornerstone-viewport
* @ohif/extension-cornerstone: 4.0.4 → 4.0.5
> Update dependency: react-cornerstone-viewport@4.0.5

- platform/core/src/utils/loadAndCacheDerivedDisplaySets.js
- platform/viewer/src/connectedComponents/ToolbarRow.js
- platform/viewer/src/connectedComponents/Viewer.js
- The ToolbarRow calls the toolbar module isDisabled function to get the state for an extension's panel tab. Now the isDisabled function depends on async data to be interpreted and used to decide whether the tab is displayed (e.g. check if this study has rt structs).
- Update ToolbarRow component so that it keeps track of derived display sets being loaded.
- Resolves issue #2288 
- Implement a pubsub utility class that studyMetadata could extend to trigger DERIVED_DISPLAY_SETS_CHANGED events that parts of the app could subscribe to update its content.
> IDC-2288: Update toolbar tabs after derived displayset loaded

- extensions/vtk/src/toolbarComponents/VTKMPRToolbarButton.js
- platform/core/src/classes/metadata/StudyMetadata.js
- platform/core/src/enums.js
- platform/core/src/utils/isDisplaySetReconstructable.js
- platform/ui/src/components/studyBrowser/StudyBrowser.js
- platform/ui/src/components/studyBrowser/Thumbnail.js
- platform/ui/src/components/studyBrowser/Thumbnail.styl
- platform/viewer/src/connectedComponents/Viewer.js
IDC 2259: https://github.com/OHIF/Viewers/issues/2259
add warning UI for series inconsistencies in the footnote of the series thumbnails. E.g.:
Other previous relevant IDC issues: 
https://github.com/OHIF/Viewers/issues/2289
https://github.com/OHIF/Viewers/issues/2113
@racacere I have removed the VTKMPRToolbarButton component memoization (i.e. PR https://github.com/OHIF/Viewers/pull/2274) since it is not anymore necessary (the 4D checks calculations have been moved to isDisplaySetReconstructable when creating the displaySet. See makeDisplaySet https://github.com/OHIF/Viewers/pull/2331/files#diff-cffb1ba058623c901e4d8ca2774946928f9bf564a4d00c77001b40bfc1cc4f65R780 and https://github.com/OHIF/Viewers/pull/2331/files#diff-7d4f87b19c454224e0282ce2d72f14c89e0d90833aa95e0f6e25e55445ca5fb3R8) …
> IDC 2259: add warning UI for series inconsistencies

- platform/core/src/utils/isDisplaySetReconstructable.js
IDC 2259 spacing warning fix for 4D datasets
> IDC2259: do not check uniform spacing in the 4th dimension for 4D datasets

- .circleci/config.yml
- platform/core/src/classes/MetadataProvider.js
- platform/core/src/utils/metadataProvider/validNumber.js
The MetadataProvider should parse string values from the dataset to valid numbers to avoid parsing issues inside libraries that consume the provider like cornerstone.
- #2360
- #2297
- #2138
> fix(MetadataProvider): Update metadata provider to resolve issues after dicomweb update/new return value

- extensions/dicom-segmentation/src/components/SegmentationPanel/SegmentationPanel.js
- extensions/dicom-segmentation/src/components/SegmentationSelect.js
- extensions/dicom-segmentation/src/getOHIFDicomSegSopClassHandler.js
- extensions/dicom-segmentation/src/getSourceDisplaySet.js
- extensions/dicom-segmentation/src/utils/setActiveLabelMap.js
- platform/core/src/classes/metadata/StudyMetadata.js
- platform/core/src/utils/loadAndCacheDerivedDisplaySets.js
- platform/viewer/src/connectedComponents/ConnectedStudyBrowser.js
- platform/viewer/src/connectedComponents/Viewer.js
- platform/viewer/src/connectedComponents/ViewerMain.js
Fix https://github.com/OHIF/Viewers/issues/2361
dataset:
http://localhost:3000/projects/idc-dev-etl/locations/us-central1/datasets/idc_tcia_dev/dicomStores/idc_tcia/study/1.3.6.1.4.1.14519.5.2.1.7695.2311.111788911924319643511738623890
> Re #2361: fix seg combobox filling

- platform/viewer/public/config/default.js
- platform/viewer/src/store/index.js
- Servers config property is cached/retrieved from local storage by default.
- This change adds a new configuration property to disable servers cache in order to always get a fresh version of servers property if changed without having to clear the browser's cache.
> IDC: Add option to disable local storage of servers

- extensions/cornerstone/package.json
- extensions/dicom-html/package.json
- extensions/dicom-html/src/DicomHtmlViewport.js
- extensions/dicom-rt/package.json
- extensions/dicom-segmentation/package.json
- extensions/dicom-tag-browser/package.json
- extensions/vtk/package.json
- platform/core/package.json
- platform/viewer/package.json
- platform/viewer/public/config/default.js
- yarn.lock
Resolve parsing issues spotted in #2348.
DICOM meta info is currently attached to a naturalized dicom object before is sent to the parsing function which expects only naturalized objects. 
This PR naturalizes the meta object and includes a separate section to display dicom meta info.
> fix(dicom-html): Add parsed dicom meta info section

- Dockerfile
Fixed issue that was caused by old version of the nginx:alpine container, that causes security scanners to report a high security alert CVE-2019-5021. Current version of nginx have already patched this vulnerability.
Please see:
https://github.com/nginx-proxy/nginx-proxy/issues/1280
> fix CVE-2019-5021 caused by nginx-apline

- platform/core/src/DICOMSR/parseDicomStructuredReport.js
- platform/core/src/classes/LogManager.js
- platform/core/src/classes/PubSub.js
- platform/core/src/classes/index.js
- platform/ui/src/contextProviders/SnackbarProvider.js
- Issue: #2526 
- Adds a log manager class to allow indirect logging or notifications throughout all packages using a pub/sub mechanism.
> OHIF-2526: Display warning messages if fails to parse sr report

- platform/docs/docs/development/getting-started.md
* the getting started page has the wrong branch name for v3, this PR fixes this
* related forum discussion: https://community.ohif.org/t/building-v3-ohif/45
> docs(OHIFv3): fix v3 branch name in getting-started

- extensions/cornerstone/src/initWADOImageLoader.js
Adds relevant headers to the xhr to prevent preflight requests in the demo (which makes the demo load faster) - [Read more](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request)
> feat: Add headers to prevent preflight requests

- extensions/measurement-tracking/src/_shared/downloadCSVReport.js
- the `_createAndDownloadFile` method in `extensions/measurement-tracking/src/_shared/downloadCSVReport.js` creates a temporary link element to download the data
- currently this temporary element is not removed after download, which leads to many `<a>` elements being appended to the body when performing multiple downloads
- with this PR the temporary element is removed after download
> fix: remove temporary link element after csv download

- platform/core/src/classes/StudyPrefetcher.js
- platform/viewer/public/config/default.js
While it is technically ok to use the default 1000 concurrent prefetch requests with HTTP/2, the event loop in js really doesn't like that. I tested on a large study (20+ series, 70/140 instances each).
cornerstone contains this commented out snippet:
```
// TODO: This is the reason things aren't going as fast as expected
// const maxSimultaneousRequests = getMaxSimultaneousRequests()
// this.maxNumRequests = {
//   interaction: Math.max(maxSimultaneousRequests, 1),
//   thumbnail: Math.max(maxSimultaneousRequests - 2, 1),
//   prefetch: Math.max(maxSimultaneousRequests - 1, 1),
// }
```
So, with the default study prefetch settings (closest 3 series), if the user clicks, say, the 5th series and tries to scroll the stack, it will get stuck in "Loading..." until the first 3 series are …
> feature: configurable max prefetch request count

- extensions/cornerstone/package.json
- extensions/default/package.json
- extensions/dicom-sr/package.json
- extensions/dicom-sr/src/viewports/OHIFCornerstoneSRViewport.js
- extensions/measurement-tracking/package.json
- modes/longitudinal/package.json
- platform/cli/templates/extension/dependencies.json
- platform/cli/templates/mode/dependencies.json
- platform/cli/templates/mode/src/index.js
- platform/core/package.json
- platform/core/src/extensions/ExtensionManager.js
- platform/core/src/extensions/ExtensionManager.test.js
- platform/core/src/utils/index.js
- platform/core/src/utils/index.test.js
- platform/docs/docs/platform/extensions/installation.md
- platform/viewer/package.json
- platform/viewer/src/routes/buildModeRoutes.js
- platform/viewer/src/routes/checkExtensionDependencies.js
- platform/viewer/src/routes/index.js
When constructing modes, check all extension dependencies are correct.
This is useful when multiple modes use the same extensions, and we can throw if the one installed doesn't satisfy one of the modes (i.e. one of the modes needs to be upgraded in order to be compatible in the same OHIF build.
> verify extensions when constructing modes.

- extensions/cornerstone/package.json
- extensions/dicom-html/package.json
- extensions/dicom-rt/package.json
- extensions/dicom-segmentation/package.json
- extensions/dicom-tag-browser/package.json
- extensions/vtk/package.json
- platform/core/package.json
- platform/viewer/package.json
- yarn.lock
Update to dcmjs 0.19.3. Fix: https://github.com/dcmjs-org/dcmjs/issues/232
> IDC: update dcmjs to version 0.19.3

- platform/core/package.json
- platform/viewer/package.json
- yarn.lock
Bump lodash and immer to avoid vulnerabilities.
> refactor: 💡 Bump lodash and immer to avoid vulnerabilities

- platform/core/src/classes/MetadataProvider.js
I've had issues visualizing WADO DICOM files that had the `imagePixelModule` tag for the Image Loader.
It used to work on the master branch and while diving in, I realized the problem came from trying to parse a string value to a number one.
According to the [DICOM standards](https://dicom.innolitics.com/ciods/ct-image/image-pixel/00280004), `photometricInterpretation` should be a string (ex. "RGB", "HSV"...). In V3, a validation on numbers was added to all keys of the metadata object, including `photometricInterpretation` which returns undefined if it does not parse to a number. 
This PR suggests to remove the `validNumber` check for that key.
looks like #2420 , https://github.com/OHIF/Viewers/issues/2426#issuecomment-887435505
Before:
After:
[blog]: …
> Remove validNumber for photometricInterpretation key

- extensions/default/src/DicomJSONDataSource/index.js
There was a typo in DicomJSON datasource to retrieve metadata. This was
causing an error in Mode.jsx (line 52)
This is almost the same as in #2717 
> fix(dicom-json): Series metadata retrieve

- extensions/cornerstone/package.json
- extensions/dicom-html/package.json
- extensions/dicom-rt/package.json
- extensions/dicom-segmentation/package.json
- extensions/dicom-tag-browser/package.json
- extensions/vtk/package.json
- platform/core/package.json
- platform/viewer/package.json
- yarn.lock
dcmjs
* @ohif/core: 0.19.7 → 0.19.8
* @ohif/extension-cornerstone: 0.19.7 → 0.19.8
* @ohif/extension-dicom-html: 0.19.7 → 0.19.8
* @ohif/extension-dicom-rt: 0.19.7 → 0.19.8
* @ohif/extension-dicom-segmentation: 0.19.7 → 0.19.8
* @ohif/extension-dicom-tag-browser: 0.19.7 → 0.19.8
* @ohif/extension-vtk: 0.19.7 → 0.19.8
* @ohif/viewer: 0.19.7 → 0.19.8
> Update dependency: dcmjs@0.19.8

- extensions/cornerstone/package.json
- extensions/dicom-html/package.json
- extensions/dicom-rt/package.json
- extensions/dicom-segmentation/package.json
- extensions/dicom-segmentation/src/components/SegmentationPanel/SegmentationPanel.js
- extensions/dicom-segmentation/src/utils/setActiveLabelMap.js
- extensions/dicom-tag-browser/package.json
- extensions/vtk/package.json
- platform/core/package.json
- platform/core/src/utils/loadAndCacheDerivedDisplaySets.js
- platform/viewer/package.json
- platform/viewer/src/connectedComponents/Viewer.js
- platform/viewer/src/connectedComponents/ViewerMain.js
- platform/viewer/src/googleCloud/DicomStorePickerModal.js
- yarn.lock
Fix:
https://github.com/OHIF/Viewers/issues/2765
https://github.com/OHIF/Viewers/issues/2761
Fix summary: 
1) running conditions and updates for parsing segmentation UI panel when loading segmentations at first startup (i.e. clicking the source thumbnail)
2) fix several issues, when DICOM miss referenced instance UIDs (malformed/missing attributes in the DICOM). In these cases we use the alternative logic with geometrical search (i.e. ImagePatientPosition).
this PR needs https://github.com/dcmjs-org/dcmjs/pull/258
> Re IDC #2765 AND #2761: fix loading of segmentations at first startup

- extensions/cornerstone-dicom-sr/package.json
- extensions/cornerstone/package.json
- extensions/default/package.json
- extensions/dicom-pdf/package.json
- extensions/dicom-video/package.json
- extensions/measurement-tracking/package.json
- platform/core/package.json
- platform/core/src/services/HangingProtocolService/HangingProtocolService.js
- platform/docs/docs/platform/services/data/HangingProtocolService.md
- platform/ui/src/contextProviders/DialogProvider.tsx
- platform/ui/src/contextProviders/SnackbarProvider.tsx
- platform/viewer/package.json
- yarn.lock
> bump: dependency versions to fix hydration bugs

- extensions/cornerstone-dicom-sr/package.json
- extensions/cornerstone/package.json
- yarn.lock
Bump cornerstone tools and core version to fix terser build error
Related issue:  https://github.com/OHIF/Viewers/issues/2880
@sedghi @wayfarer3130
> Bump cornerstrone tools and core version to fix terser bug v3-stable

- extensions/dicom-rt/src/components/RTPanel/RTPanel.js
- extensions/dicom-segmentation/src/components/SegmentationPanel/SegmentationPanel.js
- platform/core/src/classes/StudyLoadingListener.js
- platform/core/src/classes/metadata/StudyMetadata.js
- platform/core/src/services/MeasurementService/MeasurementService.js
- platform/core/src/utils/StackManager.js
IDC: Fix minor issues https://github.com/ImagingDataCommons/IDC-WebApp/issues/1030
> IDC: Fix minor issues IDC

- extensions/cornerstone/src/services/ViewportService/CornerstoneViewportService.ts
- extensions/cornerstone/src/utils/interleaveCenterLoader.ts
- extensions/cornerstone/src/utils/interleaveTopToBottom.ts
- extensions/default/src/DicomWebDataSource/index.js
- extensions/tmtv/src/Panels/PanelPetSUV.tsx
- extensions/tmtv/src/commandsModule.js
- modes/tmtv/src/index.js
- platform/core/src/services/DicomMetadataStore/DicomMetadataStore.js
- platform/core/src/services/DicomMetadataStore/createStudyMetadata.js
- platform/core/src/services/DisplaySetService/DisplaySetService.js
- platform/core/src/services/DisplaySetService/IDisplaySet.ts
- platform/core/src/services/HangingProtocolService/HPMatcher.js
- platform/core/src/services/HangingProtocolService/HangingProtocolService.test.js
- platform/core/src/services/HangingProtocolService/HangingProtocolService.ts
- platform/core/src/services/HangingProtocolService/ProtocolEngine.js
- platform/core/src/services/HangingProtocolService/lib/validator.js
- platform/docs/docs/platform/services/data/DisplaySetService.md
- platform/docs/versioned_docs/version-3.0/platform/services/data/DisplaySetService.md
- platform/viewer/src/components/ViewportGrid.tsx
- platform/viewer/src/routes/Mode/Mode.tsx
- We don't need to suppress events on displaySet service, we can just wait, since after the async metadata the part for instances add -> displaySet creation is syncronous.
- The PR broke the PanelSUV which is fixed now
- A new event on the HP (`PROTOCOL_CHANGED`), to let subscribers know that the protocol match for viewports is performed
- We had so many matchdetails in the HP service, I refactored all to be more clear and added many types for HP
~~Todo: DisplaySetService makes the displayset when ALL instances are added
However, making a displayset only requires one instance and one instance only
you can look at the sopClassHandlers which you will see only the first instance
is used to make the displayset. This is a huge performance bottleneck
since we are waiting for all instances to be …
> fix: displaySetService no event not needed

- platform/viewer/src/appExtensions/GenericViewerCommands/commandsModule.js
https://github.com/OHIF/Viewers/issues/2870
> Fix  hotkey page up/down does not work

- extensions/default/src/DicomLocalDataSource/index.js
- platform/viewer/src/routes/Local/Local.tsx
This fix allows for multiple studies to be displayed when local files dragged have different studyUIDs
> fix: enabled multiple studies in local mode

- platform/cli/src/commands/linkPackage.js
- platform/cli/templates/extension/dependencies.json
- platform/cli/templates/mode/dependencies.json
Make the cli linkages in the OHIF root directory node modules, rather than in a sub-directory.  This makes it more consistent for yarn (really, yarn should do this automatically, but doesn't).  Otherwise, you get differences between linked and package modules that can cause conflicts.
> fix: ohif cli bug for linking

- extensions/dicom-segmentation/src/components/SegmentationPanel/SegmentationPanel.js
- extensions/dicom-segmentation/src/components/SegmentationSettings/SegmentationSettings.js
- extensions/dicom-segmentation/src/getOHIFDicomSegSopClassHandler.js
- extensions/dicom-segmentation/src/index.js
Adds https://github.com/OHIF/Viewers/issues/2918
Hera a video:
1) setting the default tolerance to 1e-7 
2) the segs loading fails
3) change parameter in the Segs settings panel
4) reload successfully the data 
https://user-images.githubusercontent.com/7985338/189641347-c203f8b9-1789-435f-81bf-1f3d5d17131e.mp4
P.S.: the default value was set to 1e-7 only for this video to demostrate the feature. The defafult one is 1e-2 (which affter many issues, we defined as a good compromise for IDC cases).
> Fix IDC Re #2918: Runtime tolerance for SEGs loading

- extensions/cornerstone/src/init.js
- extensions/cornerstone/src/services/SyncGroupService/SyncGroupService.ts
- platform/docs/versioned_docs/version-3.0/platform/services/data/HangingProtocolService.md
- platform/ui/src/contextProviders/ViewportGridProvider.tsx
Adds a registration capability to add new synchronizers
Based off the hanging protocol PR, but is intended to merge after that one.
@sedghi and @swederik  - this is a modified design that allows creating new synchronizers.  There is also a bit more cleanup of types in the hanging protocol area to make that cleaner.  The only connection between hanging protocols and the syncrhonizers is the existing syncGroups - otherwise, that area is actually identical.  I do not yet have an example synchronizer fully worked out, but I didn't want to do that until you had seen it.
> feat(syncGroups):Add registration for new synchronizers

- extensions/measurement-tracking/src/panels/PanelMeasurementTableTracking/ActionButtons.tsx
- extensions/tmtv/src/Panels/PanelPetSUV.tsx
- extensions/tmtv/src/Panels/PanelROIThresholdSegmentation/ROIThresholdConfiguration.tsx
- extensions/tmtv/src/Panels/PanelROIThresholdSegmentation/segmentationEditHandler.tsx
- platform/docs/tailwind.config.js
- platform/ui/package.json
- platform/ui/src/components/AboutModal/AboutModal.tsx
- platform/ui/src/components/Button/Button.tsx
- platform/ui/src/components/Dialog/Dialog.tsx
- platform/ui/src/components/Dialog/Header.tsx
- platform/ui/src/components/Dropdown/Dropdown.tsx
- platform/ui/src/components/Modal/Modal.css
- platform/ui/src/components/Modal/Modal.tsx
- platform/ui/src/components/Notification/Notification.tsx
- platform/ui/src/components/SidePanel/SidePanel.tsx
- platform/ui/src/components/StudyBrowser/StudyBrowser.tsx
- platform/ui/src/components/StudyItem/StudyItem.tsx
- platform/ui/src/components/StudyListFilter/StudyListFilter.tsx
- platform/ui/src/components/StudyListPagination/StudyListPagination.tsx
- platform/ui/src/components/StudyListTable/StudyListTableRow.tsx
- platform/ui/src/components/Typography/Typography.tsx
- platform/ui/src/components/UserPreferences/UserPreferences.tsx
- platform/ui/src/components/ViewportActionBar/ViewportActionBar.tsx
- platform/ui/src/components/ViewportDownloadForm/ViewportDownloadForm.tsx
- platform/ui/tailwind.config.js
- platform/viewer/package.json
- platform/viewer/src/routes/Local/Local.tsx
- platform/viewer/tailwind.config.js
- yarn.lock
Why? -> https://tailwindcss.com/blog/tailwindcss-v3
- Just in time engine
- More classes
- Arbitrary properties `m-[13px]`
Tailwind v3 classes does not overwrite the previous ones if they are coming after each other for instance `bg-black bg-primary-main` would not necessarily make the background with color of `primary-main`. It depends which CSS classes is created first. However, all some of the components in our UI library (e.g., Button.tsx) systems rely on such overwriting. There are two options moving forward for developers
- Using a third party library such as [tailwind merge](https://www.npmjs.com/package/tailwind-merge) to handle the merge 
- Introduce APIs via props (as done for Button currently) to overwrite defaults
Long term we should rework the library to enable the second …
> feat: upgrade tailwind to version 3

- platform/core/package.json
- platform/core/src/index.test.js
- platform/core/src/index.ts
- platform/core/src/services/DicomMetadataStore/StudyMetadata.ts
- platform/core/src/services/HangingProtocolService/HangingProtocolService.ts
- platform/core/src/types/Consumer.ts
- platform/core/src/types/IPubSub.ts
- platform/core/src/types/StudyMetadata.ts
- platform/core/src/types/index.ts
- platform/ui/src/components/StudyBrowser/StudyBrowser.tsx
- platform/ui/src/components/Thumbnail/Thumbnail.tsx
- platform/ui/src/components/ThumbnailList/ThumbnailList.tsx
- platform/ui/src/components/ThumbnailTracked/ThumbnailTracked.tsx
- platform/ui/src/components/ViewportActionBar/ViewportActionBar.tsx
- platform/ui/src/index.js
- platform/ui/src/types/ThumbnailType.ts
- platform/ui/src/types/index.ts
- platform/viewer/src/routes/DataSourceWrapper.tsx
This just fixes the configurability of additional data source extensions - without it, there isn't a way to define a second data source type without removing the default extension.
> fix(datasource): configurability of additional data source extensions

- extensions/default/src/getSopClassHandlerModule.js
There is a typo in instance.modality where Modality should be uppercase. Otherwise will always be undefined. This is why Xray with same series are still stacking rather than having separate display sets.
> fix: sop class handler isSingleImageModality always undefined

- extensions/cornerstone/src/Viewport/OHIFCornerstoneViewport.tsx
- extensions/cornerstone/src/Viewport/Overlays/ViewportOrientationMarkers.tsx
- extensions/cornerstone/src/services/ViewportService/CornerstoneCacheService.ts
In the cornerstone cache service, the viewport data changed was fired before the viewport data was actually fully changed.
Also, in panelPetSUV, the panel was being updated on display set changed, which was incorrect, because it actually depends on the viewport data changed event.  Updated it so that panel also uses the viewport data changed event.
> fix: cornerstone cache race condition

- extensions/cornerstone/src/getHangingProtocolModule.ts
- extensions/default/src/getHangingProtocolModule.js
- extensions/tmtv/src/getHangingProtocolModule.js
- modes/basic-dev-mode/src/index.js
- modes/tmtv/src/index.js
- platform/cli/templates/mode/src/index.tsx
- platform/core/src/extensions/ExtensionManager.js
- platform/core/src/services/HangingProtocolService/HPMatcher.js
- platform/core/src/services/HangingProtocolService/HangingProtocolService.test.js
- platform/core/src/services/HangingProtocolService/HangingProtocolService.ts
- platform/core/src/services/HangingProtocolService/ProtocolEngine.js
- platform/core/src/types/HangingProtocol.ts
- platform/docs/docs/platform/modes/index.md
- platform/docs/docs/platform/services/data/HangingProtocolService.md
- platform/docs/versioned_docs/version-3.0/platform/modes/index.md
- platform/viewer/src/routes/Mode/Mode.tsx
There had been a change made to make the hanging protocols auto initialize, but that caused problems on mode init because the couldn't specify the hanging protocols any longer. THis change restores that, and also improves the API a little bit by allowing the display set selectors to be specified by id instead of positionally.
> fix(hp):Make the updated hanging protocol compatible with modes

- Dockerfile
- extensions/cornerstone-dicom-sr/src/getSopClassHandlerModule.js
- extensions/cornerstone-dicom-sr/src/tools/DICOMSRDisplayTool.ts
```
./DicomSRValidator.sh ~/Development/github/highdicom/ohif_test.dcm 
Found Comprehensive3DSR IOD
Found Root Template TID_1500 (MeasurementReport)
Root Template Validation Complete
IOD validation complete 
```
The anonymized images were downloaded from [here](https://www.dicomlibrary.com/?manage=02ef8f31ea86a45cfce6eb297c274598).
The DICOM SR was generated by [highdicom](https://github.com/herrmannlab/highdicom) in the 'feat/add_image_library_tid1601' branch.
The attached zip file contains a series from the anonymized MR images and the DICOM SR. As you scroll through the images the rectangle moves down and to the right.
[mri_images.zip](https://github.com/OHIF/Viewers/files/9603215/mri_images.zip)
[script]: …
> Added support for TID 1410 relationship types

- extensions/cornerstone-dicom-sr/package.json
- extensions/cornerstone/package.json
- extensions/default/package.json
- extensions/dicom-pdf/package.json
- extensions/dicom-video/package.json
- extensions/measurement-tracking/package.json
- extensions/tmtv/package.json
- platform/core/package.json
- platform/viewer/package.json
- yarn.lock
Simple upgrade of dcmjs package reference.
This PR can be considered as a follow-up of https://github.com/OHIF/Viewers/pull/2973
An important feature addition for dcmjs is available from v0.28.3
https://github.com/dcmjs-org/dcmjs/pull/320
This is about supporting annotations and measurements on multi-frame DICOM files.
In previous versions, when saving measurement SRs, the "Cornerstone3D - dcmjs connector" which is now included in the dcmjs package, will decide whether to treat it as a multi-frame or not by checking "SopClassUID" against the limited list of supported UIDs.
This was causing bugs when creating SRs on many multi-frame files ( annotations / measurements were saved without frame information they were attached to ).
With the above fixes, this should be resolved, because, as of …
> dcmjs package reference upgraded to 0.28.3

- extensions/cornerstone-dicom-sr/package.json
- extensions/cornerstone/package.json
- extensions/measurement-tracking/package.json
- yarn.lock
Upgrade @cornerstonjs/core to 0.16.8 to benefit from fixes
https://github.com/cornerstonejs/cornerstone3D-beta/pull/241 fixes the bug that multi-frame files sometimes have whitening noise on the frames other than the first frame.
> upgrade cornerstonjs core 0.16.8

- platform/core/src/DICOMSR/SCOORD3D/parseSCOORD3D.js
- platform/core/src/DICOMSR/SCOORD3D/utils/getReferencedImagesList.js
Fix for https://github.com/OHIF/Viewers/issues/2965
Explanation below:
Qualitative slice-level SR annotations are within the Measurement Group container, which is obtained through https://github.com/OHIF/Viewers/blob/7aba01f534b70406ce02e1708004141c7b773904/platform/core/src/DICOMSR/SCOORD3D/parseSCOORD3D.js#L31
This particular dataset did not have any ImageLibrary, hence [getReferenceImagesList()](https://github.com/OHIF/Viewers/blob/7aba01f534b70406ce02e1708004141c7b773904/platform/core/src/DICOMSR/SCOORD3D/parseSCOORD3D.js#L30) was throwing errors. 
I modified [platform/core/src/DICOMSR/SCOORD3D/utils/getReferencedImagesList.js](https://github.com/OHIF/Viewers/blob/7aba01f534b70406ce02e1708004141c7b773904/platform/core/src/DICOMSR/SCOORD3D/utils/getReferencedImagesList.js#L4) as it …
> fix: 2965 Correct Parsing Logic for Qualitative Instance Level SR

- extensions/default/src/DicomJSONDataSource/index.js
- extensions/default/src/DicomWebDataSource/index.js
- extensions/default/src/utils/getDirectURL.js
The method "directURL" is implemented in the datasource DicomWebDataSource but is missing from the DicomJSONDataSource. This is causing the PDF and Video viewports to not work as they depend on this method.
The implementation is to abstract the method implementation as its own utility function and re-use it across both datasources
@sedghi 
> update DicomJSONDataSource to support directURL method

- extensions/cornerstone/src/utils/measurementServiceMappings/EllipticalROI.js
The easiest fix for the issue would be handling of the cases where "area" becomes "undefined"
> Fix #3020 - Elliptical Annotations not being added/tracked when created outside the actual image area

- platform/viewer/.webpack/webpack.pwa.js
Previously, the `config/` and `html-templates/` directories were copied to the `dist/` folder when building because of an incorrect reference in the webpack config.
> fix: Correctly ignore directories in CopyWebpackPlugin in webpack config

- extensions/default/src/ViewerLayout/index.tsx
- platform/viewer/.webpack/webpack.pwa.js
- platform/viewer/public/config/multiple.js
- platform/viewer/src/routes/DataSourceWrapper.tsx
- platform/viewer/src/routes/WorkList/WorkList.tsx
This change adds the ability to show the worklist against different data sources by using a path /:datasourcename.  It also fixes the various sub-paths so that they return to the correct parent data source name.  For example, in the multiple.js configuration, there are data sources:  default, aws and e2e.  Then, one can query three different back ends with:
http://localhost:3000/search/default
http://localhost:3000/search/aws
http://localhost:3000/search/e2e
You can pull/try those three examples (assuming you have a dicomweb instance on port 5000 running).
> feat(datasource):Support querying different data sources

- extensions/cornerstone/src/services/SegmentationService/SegmentationService.ts
Some DisplaySets don't have an `instance` property, thus throwing an error at this location. 
This change fixes this issue.
@sedghi Do you think this can be merged? :)
> Fix: handle undefined instance object

- extensions/default/src/DicomTagBrowser/DicomTagBrowser.tsx
In the Dicom Tag Browser if you move the instance slider and then change series, the slider won't update to the first position even though the new series displayed will start with the first instance. 
I've fixed this by giving the slider the displaySetInstanceUID as a key to force it to re-render when the series changes. I'm open to other solutions to the bug.
@sedghi Tagging you for review
> Fix Dicom Tag Browser slider doesn't update when series changed

- extensions/default/src/ViewerLayout/index.tsx
- platform/viewer/src/App.tsx
- platform/viewer/src/routes/NotFound/NotFound.tsx
- platform/viewer/src/routes/index.tsx
I followed suit with how it was implemented in the v2 branch, on the 404 page I just hid the link back to the study list if we're not configured to display it. See PR #2131
However I don't think the 404 page is being rendered correctly on `v3-stable`? I had the slightest poke but couldn't see what was going wrong there so left it alone.
@sedghi tagging you as you seem to do most the reviews in this repo :slightly_smiling_face: 
> fix: Add support for showStudyList configuration setting

- extensions/cornerstone/src/services/ViewportService/CornerstoneViewportService.ts
- modes/basic-dev-mode/src/index.js
- modes/longitudinal/src/index.js
- modes/tmtv/src/index.js
- platform/core/src/extensions/ExtensionManager.js
- platform/core/src/services/CustomizationService/CustomizationService.ts
- platform/core/src/services/DicomMetadataStore/createStudyMetadata.js
- platform/core/src/services/DisplaySetService/DisplaySetService.js
- platform/core/src/services/HangingProtocolService/HangingProtocolService.ts
- platform/core/src/services/MeasurementService/MeasurementService.js
- platform/core/src/services/ViewportGridService/ViewportGridService.ts
- platform/docs/docs/platform/extensions/index.md
- platform/docs/docs/platform/managers/service.md
- platform/docs/docs/platform/modes/lifecycle.md
- platform/ui/src/components/Button/Button.tsx
- platform/viewer/src/components/ViewportGrid.tsx
- platform/viewer/src/routes/Mode/Mode.tsx
There were a number of interacting issues, which were causing the old display set to be redisplayed.  The easiest way to demonstrate this was to display a video initially and then redisplay it, causing the display sets to get duplicated, but another way was to just show successive studies going back/forth to the studies page and seeing the flash of the old study.
> fix(grid):Grid service wasn't being reset

- .docker/Viewer-v3.x/default.conf.template
- .docker/Viewer-v3.x/entrypoint.sh
- Dockerfile
- platform/docs/docs/deployment/docker.md
- platform/docs/docs/deployment/google-cloud-healthcare.md
- platform/docs/docs/deployment/nginx--image-archive.md
- platform/docs/docs/deployment/user-account-control.md
fix: Use single quotes instead of backticks when specifying the environment variable that should be substituted for the envsubst command.
GitHub issue: #3079
Removed duplicate calls to envsubst.
Default nginx listen port is now 80.
Added markdown documentation.
https://github.com/OHIF/Viewers/issues/3079
> fix: v3-stable Docker build and run are not working

- extensions/measurement-tracking/src/panels/PanelMeasurementTableTracking/ActionButtons.tsx
- extensions/measurement-tracking/src/panels/PanelMeasurementTableTracking/index.tsx
Use the disabled Button component variant when no tracked measurements are present. Made the buttons look as per the spec.
> fix: OHIF-386 Disable Export and Create Report buttons if there are no tracked measurements

- extensions/dicom-segmentation/src/components/SegmentationPanel/SegmentationPanel.js
Fixes https://github.com/OHIF/Viewers/issues/3088
Segments visibility toggle should display/hide all segment items of only the selected/active segmentation.
The previous logic was impacting the visibility of n segment items across all segmentations , where n = no. of segment items in the active segmentation.
https://user-images.githubusercontent.com/112136540/211079104-8882321e-8aad-4e21-8aa3-cd5128372179.mp4
Test results with another dataset of non-overlapping segs in multiple seg series
Before fix:
https://user-images.githubusercontent.com/112136540/211080359-0c870259-3841-4abf-8a2f-3519a9c424cc.mp4
After fix:
https://user-images.githubusercontent.com/112136540/211080556-a3349b73-7160-45cc-bae5-671540c8b2b7.mp4
Test result with another dataset of overlapping segments from same series …
> Re IDC #3088: Fix seg toggle visibility logic

- platform/core/src/utils/isDisplaySetReconstructable.js
This fixes cases where some instances don't have this attribute, which would break on platform/core/src/utils/sortInstancesByPosition.ts:52
> fix: Require all instances to have an ImagePositionPatient attribute

- .github/ISSUE_TEMPLATE/---bug-report.md
- .github/ISSUE_TEMPLATE/---feature-request.md
- .github/pull_request_template.md
- .github/stale.yml
> chore: update issue and PR templates

- extensions/dicom-segmentation/src/commandsModule.js
- extensions/dicom-segmentation/src/components/SegmentationSettings/SegmentationSettings.js
- extensions/dicom-segmentation/src/index.js
- platform/viewer/src/connectedComponents/ConnectedStudyBrowser.js
- platform/viewer/src/connectedComponents/Viewer.js
Fixes: https://github.com/OHIF/Viewers/issues/3077
> Re IDC #3077: Seg series thumbnail selection

- extensions/cornerstone/src/commandsModule.ts
->implement firstImage lastImage commands
'home' and 'end' hotkeys call firstImage and lastImage commands. These commands were missing and have been added in extension/cornerstone/src/commandsModule.ts
- Added firstImage and lastImage commands referred by default 'home' and 'end' hotkeys
- 'home' and 'end' hotkeys now bring active viewport image to first and last slice respectively
Basic:
1. Load study with image set containing multiple slices
2. Hit 'end' key -> check viewport has changed to last slice
3. Hit 'home' key -> check viewport has changed to first image slice
Multiple
1. Load study with image set containing multiple slices
2. Change layout to 2x1 grid
3. Load image in both viewports
4. Change active to viewport 1
5. Hit 'end' key -> check viewport 1 has changed to last slice …
> fix(Hotkeys): add firstImage and lastImage commands referenced by 'home' and 'end' hotkeys

- extensions/cornerstone-dicom-seg/src/panels/PanelSegmentation.tsx
- platform/ui/src/components/SegmentationGroupTable/SegmentationGroup.tsx
- platform/ui/src/components/SegmentationGroupTable/SegmentationGroupTable.tsx
- platform/ui/src/components/SidePanel/SidePanel.tsx
- platform/ui/tailwind.config.js
- platform/viewer/tailwind.config.js
Dicom Seg Panel Sizing is incorrect. The panel is being cut when there are too many items
The changes applied were to fix the flex layout sizing for the entire right panel + seg panel.
The seg panel had a fixed height but instead its height should be the remaining flex space. The strategy applied were:
- Avoid grow/shrink of some items, but ensure it for panel seg and its direct parents. Also who put min-height:0 for such items which will ensure there is a initial minimum value allowing it to grow as needed.
Before
After (observe on Seg Panel we can see the last items)
etc.)
- [] The documentation page …
> fix(Panels): dicom seg panel sizing issue

- .docker/Nginx-Orthanc/docker-compose.yml
- extensions/cornerstone-dicom-sr/src/getSopClassHandlerModule.js
- extensions/cornerstone-dicom-sr/src/tools/DICOMSRDisplayTool.ts
- extensions/measurement-tracking/src/contexts/TrackedMeasurementsContext/promptHydrateStructuredReport.js
Annotations are not rendered properly after loading a SR and enabling measurements tracking (OHIF-341).
- Changed how Length and Bidirectional annotations are rendered to make it similar to the original annotation added by the user before saving the SR.
- SRs does not support labels that were moved to different location
- No changes pushed to ellipse and arrow annotations
- Add some Length and/or Bidirectional annotations
- Create a SR
- Load the SR created
- Once SR is loaded enable measurements tracking
- Compare how annotations are rendered before saving the SR, after loading the SR and after enabling measurements tracking.
> fix(SR): fix Length and Bidirectional tools

- platform/viewer/cypress/integration/measurement-tracking/OHIFCornerstoneToolbar.spec.js
The test in question:
'OHIF Cornerstone Toolbar'.'checks if Levels tool will change the window width and center of an image'.
Issue #3157 
The cypress test 'checks if Levels tool will change the window width and center of an image' in OHIFCornerstoneToolbar.spec.js is failing because of the double click detection changes that were made in cornerstone3D.
The test in question was performing a click near the beginning of the test that was not necessary and was throwing off the timing of the test because it was triggering an unnecessary double click detection. The click was removed.
1. Set up and run end-to-end tests as described [here](https://v3-docs.ohif.org/development/testing/).
2. Run the OHIF Cornerstone Toolbar test. It should pass.
etc.) …
> fix(cypress test): remove the click at beginning of the window level test

- extensions/cornerstone/package.json
- package.json
- platform/viewer/src/components/ViewportGrid.tsx
- yarn.lock
- Updates vtk js to 26.4.0 since cs3d has been bumped before
- For filling out the empty viewports, we should exclude non-imaging ones
> chore: update vtk js to 26.4.0

- platform/core/src/classes/ImageSet.js
Many places in the OHIF code reference the non-exposed `ImageSet.images` property directly.
Adding a `ImageSet.getNumImages` allows for a convenient way to get the number of images and there is already a `ImageSet.getImage(index)` method to accompany it.
> feat(ImageSet): Avoid exposing the images field by adding a getNumImagesMethod

- platform/viewer/src/routes/buildModeRoutes.tsx
OHIF instances that are protected by authentication would allow URL paths that include {mode}/{datasource} to be accessed without being authenticated because such routes are NOT private and thus not protected by the authentication in place.
Such routes are now marked as private.
Attempt to access say `viewer/dicomweb` without logging in for an OHIF instance protected by authentication.
etc.)
> fix(authentication): mode/datasource routes must be marked private so they can be protected via authentication.

- extensions/default/src/DicomJSONDataSource/index.js
- extensions/measurement-tracking/src/viewports/TrackedCornerstoneViewport.tsx
- platform/core/src/utils/formatPN.js
- formatPN should accept a string person name as well as an object with a Alphabetic field.
- For DICOM JSON data sources, spread in the patient data from the study object into the instance.
1. Display a DICOM JSON study, that includes a patient name, in OHIF. 
2. Click the patient info icon in the top right of a viewport.
3. The patient name is/was NOT displayed in the popup that is displayed.
The following URL depicts the incorrect behaviour prior to merging this PR...
https://v3-demo.ohif.org/viewer/dicomjson?url=https://ohif-dicom-json-example.s3.amazonaws.com/LIDC-IDRI-0001.json
- The code no longer assumes that ALL patient names are an object with an ALPHABETIC field - a check for this field is done first and if not present a string is assumed
- For DICOM JSON data sources, we are …
> fix(DicomJSON): Patient name from DICOM JSON now visible in the patient info popup

- extensions/cornerstone/src/commandsModule.ts
- extensions/cornerstone/src/init.tsx
- extensions/cornerstone/src/initCornerstoneTools.js
- extensions/cornerstone/src/initMeasurementService.js
- extensions/cornerstone/src/tools/CalibrationLineTool.ts
- extensions/cornerstone/src/utils/callInputDialog.tsx
- extensions/cornerstone/src/utils/getActiveViewportEnabledElement.ts
- modes/basic-dev-mode/src/index.js
- modes/basic-dev-mode/src/toolbarButtons.js
- modes/longitudinal/src/initToolGroups.js
- modes/longitudinal/src/toolbarButtons.js
- platform/core/src/DICOMWeb/getModalities.js
- platform/docs/docs/user-guide/viewer/toolbar.md
- platform/docs/versioned_docs/version-3.0/user-guide/viewer/toolbar.md
- platform/ui/src/assets/icons/tool-calibration.svg
- platform/ui/src/components/Button/Button.tsx
- platform/ui/src/components/Icon/getIcon.js
- platform/ui/src/components/Typography/Typography.tsx
Manual Calibration Tool implementation.
A DICOM image usually have calibration information (or pixel spacing information) that represents the mapping of real-world size and the pixels in the image. Sometimes this information is not available and even when it is available, we may want to manually re-calibrate the image.
- Similar to the line(length) tool
- but once the line is drawn, a popup shows up to collect input about the physical distance represented by the line.
- Click OK, then the viewport and all the measurements will be updated
- The re-calibration performed by this tool would be temporary and won't be persisted/uploaded back to the source image yet.
etc.)
> feat(Calibration Tool): add a calibration tool that can manually recalibrate an image and measurements on it

- extensions/tmtv/src/Panels/PanelROIThresholdSegmentation/PanelROIThresholdSegmentation.tsx
- extensions/tmtv/src/Panels/PanelROIThresholdSegmentation/ROIThresholdConfiguration.tsx
- extensions/tmtv/src/commandsModule.js
- extensions/tmtv/src/utils/getThresholdValue.ts
- Adds the CT volume data in ROI Thresholding
- Adds a new line in ROI Threshold panel to configure CT ranges
- This PR enables the user to create REOI by filtering both CT and PET data, facilitating the creation of roi in anatomical body parts with specific CT intensity ranges
> Add CT volume in PET ROI Thresholding

- platform/ui/src/assets/styles/styles.css
- platform/ui/src/components/StudyBrowser/StudyBrowser.tsx
- platform/ui/src/components/ThumbnailList/ThumbnailList.tsx
Expand the multi studies scrollbar to overflow the studies when the height limit is filled.
Automatically scrolls to the newest added measurement in the tracked measurements table when the list of measurements exceeds the maximum viewable length.
Added a study-min-hight css class to always show 2 slices per loaded study when they are expanded. Also made both scrollbars invisible.
Added measurements-panel id to the tracked measurements panel which is used to scroll to the bottom when a new item is added.
Load a set with multiple studies. Expand the studies along the left hand size and they will appear in a scrollable panel.
Track measurements on a study until the list of tracked measurements on the right hand side is filled from top to bottom. Keep adding new measurements and observe that …
> fix(thumbnails): expand multi studies scrollbar

- extensions/measurement-tracking/package.json
- extensions/measurement-tracking/src/panels/PanelMeasurementTableTracking/index.tsx
Automatically scrolls to the newest added measurement in the tracked measurements table when the list of measurements exceeds the maximum viewable length.
Added measurements-panel id to the tracked measurements panel which is used to scroll to the bottom when a new item is added.
Track measurements on a study until the list of tracked measurements on the right hand side is filled from top to bottom. Keep adding new measurements and observe that the list automatically scrolls to the bottom.
etc.)
> fix(ui): autoscroll to new measurement on measurement table

- extensions/cornerstone-dicom-sr/src/utils/getFilteredCornerstoneToolState.ts
- extensions/cornerstone-dicom-sr/src/utils/hydrateStructuredReport.js
- extensions/cornerstone/src/commandsModule.ts
- extensions/default/src/Panels/PanelMeasurementTable.tsx
- extensions/measurement-tracking/src/panels/PanelMeasurementTableTracking/index.tsx
- extensions/test-extension/src/custom-context-menu/findingsContextMenu.ts
- platform/core/src/services/MeasurementService/MeasurementService.ts
- platform/ui/src/components/MeasurementTable/MeasurementItem.tsx
- platform/ui/src/components/MeasurementTable/MeasurementTable.tsx
- yarn.lock
This change fixes saving and restoring of the site/finding information associated with a measurement, and IF the measurement has a site/finding, then adds it to the measurement display.
Must be merged after the context menu changes as it depends on that.
> feat(findingSite): Allow customizing the measurement panel and show site/finding

- modes/longitudinal/src/initToolGroups.js
- modes/longitudinal/src/toolbarButtons.js
Prior to this PR there were no (mouse/tool) bindings for pan and zoom for a Volume3DViewport.
Added bindings to the `volume3d` tool group: secondary mouse button (i.e. right button) for zoom and auxiliary (i.e. middle/mouse wheel) button for pan. Furthermore, the zoom and pan toolbar tools get explicitly set to various tool groups but NOT for the `volume3d` tool group.
For a volume 3D viewport, use drag with the left mouse button to rotate, the right mouse button to zoom and the middle/mouse wheel button to pan. Switching to either the pan or zoom toolbar tools has NO effect on the volume 3D viewport.
etc.)
[script]: …
> fix(Volume3DViewport): Added pan and zoom

- package.json
- yarn.lock
Update axios: Fixing JSON transform when data is stringified. Providing backward compatibility and complying to the JSON RFC standard (https://github.com/axios/axios/pull/4020)
> fix(axios): bump axios resolution version / supress warning

- extensions/cornerstone-dicom-seg/src/utils/_hydrateSEG.ts
- extensions/cornerstone/src/Viewport/OHIFCornerstoneViewport.tsx
- extensions/cornerstone/src/getHangingProtocolModule.ts
- extensions/cornerstone/src/services/ViewportService/CornerstoneViewportService.ts
- extensions/cornerstone/src/utils/nthLoader.ts
- extensions/default/src/getHangingProtocolModule.js
- extensions/test-extension/src/hp/index.ts
- extensions/tmtv/src/getHangingProtocolModule.js
- platform/core/src/extensions/ExtensionManager.test.js
- platform/core/src/extensions/ExtensionManager.ts
- platform/core/src/services/ViewportGridService/ViewportGridService.ts
- platform/ui/src/contextProviders/ViewportGridProvider.tsx
- platform/viewer/public/config/multiple.js
If multiple react state events occur near each other, react can decide to combine this, or can serialize them, or any combination thereof.  As well, any number of renderings or none can occur in between these.  This combination can lead to viewports
being in the midst of being created or destroyed when being rendered, or a partial new rendering occur, causing exceptions.
There are two parts to the fix.  First, not reusing viewport Id's at all means that create/destroy events on single viewport id's don't occur.  Second, making the drag and drop and segmentation updates atomic (single operation done at once) means it occurs consistently and in the same order and doesn't invoke multiple renders.  This also, incidentally, makes it faster.
To test, the easiest way is to open up the …
> fix(viewports): The display of linked viewports during drag and drop has a race

- extensions/cornerstone-dicom-sr/src/tools/DICOMSRDisplayTool.ts
Fixes ellipse not rendering correctly when viewport is rotated. This was fixed in the native cornerstone3D tool and it's adapters, but also needed to be applied to the DICOMSRDisplayTool. 
See comments on the pull request
[Pull#479](https://github.com/cornerstonejs/cornerstone3D-beta/pull/479)
Added condition to check for the rotation and select the top/bottom/left/right canvas points based on it
Now Ellipse renders correctly in all scenarios, when drawn using the native tool, or when stored and restored, It will render correctly before/after re-hydration.
_______________________________________________________________________________________________________________________
> fix(SRTool): Ellipse Display for DICOMSR Tool

- platform/core/src/utils/splitComma.ts
- platform/viewer/src/routes/Mode/Mode.tsx
Bug fix to address the series filter not supporting multiple values.
Fix the comma split to work better and use it consistently.
http://localhost:3000/viewer/ohif?StudyInstanceUIDs=1.3.6.1.4.1.25403.345050719074.3824.20170125095438.5&SeriesInstanceUID=1.3.6.1.4.1.25403.345050719074.3824.20170125095449.8&SeriesInstanceUID=1.3.6.1.4.1.25403.345050719074.3824.20170125095506.10
should show two series (may need to tweak the URL for the right datasource name)
etc.)
- [] "OS: 
- [] "Browser: …
> fix(URL): allow multi filter query

- platform/core/src/services/HangingProtocolService/HangingProtocolService.ts
The custom attribute function 'sameAs'  requires displaySetMatchDetails and displaySets to compare attributes between display sets, but these properties were not being passed into the options object. 
This pull request adds 'displaySetMatchDetails' and 'displaySets' to the options object passed to the 'findMatch' function in order to address an issue where the sameAs function was missing required data.
In the 'sameAs' function, 'displaySetMatchDetails' and 'displaySets' are required to compare attributes between display sets. However, these properties were not being passed into the 'options' object. To address this, I added the following lines of code to the object that is passed as 'options':
{
studies: this.studies,
instance: displaySet.images?.[0],
//displaySetMatchDetails: …
> fix(hp): Add displaySetMatchDetails and displaySets to options in

- .docker/Nginx-Orthanc/docker-compose.yml
Updated Orthanc docker version from 1.5.7 to 1.11.0 because saving SR was not working as expected (wrong data) and some versions before 1.11.0 does not have support for requests with `Accept: transfer-syntax=*` header. I've been using 1.11.0 for ~2 months with no problem.
> chore(version): updated Orthanc from 1.5.7 to 1.11.0

- extensions/cornerstone/src/components/DicomUpload/DicomUpload.tsx
Small tweak for the minimum height of the upload dialogue to better fit some laptops (e.g. Dell XPS 15)
Try upload on various laptops and tablets. Most should not have a scrollbar for the uploader.
etc.)
> feat(DICOM Upload): Decreased the minimum height for the upload dialog contents to better fit some laptops.

- platform/core/src/services/HangingProtocolService/HangingProtocolService.ts
The description for the numberOfDisplaySetsWithImages property was corrected. The update also involves adding a callback property that returns several objects (matchedViewports, viewportMatchDetails, displaySetMatchDetails) and returning them from the method 'findViewportProtocols'. The refactored code also has better readability.
> fix(HangingProtocolService): Add callback property & update description

- extensions/default/src/ViewerLayout/index.tsx
- platform/docs/docs/configuration/configurationFiles.md
- platform/viewer/public/config/default.js
- platform/viewer/src/index.js
- platform/viewer/src/loadDynamicConfig.js
- platform/viewer/src/routes/DataSourceWrapper.tsx
- platform/viewer/src/routes/WorkList/WorkList.tsx
This PR allows for the app config to reference a json over network. This allows for
fast swapping of data source configuration, OIDC, etc, without recompiling the application.
If the `configUrl` query string is passed, the worklist and modes will load from the referenced json
rather than the default .env config
If there is no `configUrl` path provided, the default behaviour is used and there should not be any
deviation from current user experience.
**Points to consider**
- User have to enable this feature by setting `dangerouslyUseDynamicConfig.enabled:true`. By default it is `false`.
- Regex helps to avoid easy exploit
- User must set `cross-origin = same-origin` to avoid potential harder exploit
**Sample local config**
```
/* Dynamic config allows user to pass "configUrl" query string …
```
> feat: query string dynamic app config

- extensions/cornerstone-dicom-sr/package.json
- extensions/cornerstone/package.json
- extensions/measurement-tracking/package.json
- extensions/measurement-tracking/src/viewports/TrackedCornerstoneViewport.tsx
- package.json
- platform/core/package.json
- platform/viewer/package.json
- yarn.lock
Measurements added to volume viewports of non-acquisition plane display sets are NOT tracked and thus should be rendered with dashed lines.
Use dashed lines for measurements of viewports where getCurrentImageId returns undefined since in those cases the images have been generated.
Using OHIF, launch MPR and add measurements to the non-acquisition views. Those should all be rendered with dashed lines. Measurements added to the acquisition plane display sets and tracked should continue to render with solid lines.
etc.)
> fix(Measurement): Use dashed lines for measurments of viewports where getCurrentImageId returns undefined

- extensions/cornerstone/src/commandsModule.ts
- extensions/cornerstone/src/utils/CornerstoneViewportDownloadForm.tsx
- platform/ui/src/components/ViewportDownloadForm/ViewportDownloadForm.tsx
There were various issues with the download image feature...
- pdf and video would crash the client
- keep/dismiss aspect ratio button did not work at all
- show annotations did not work at all; annotations were always excluded
- changing the size of the image made the dialogue a bit awkward
- prevented non-cornerstone viewports from showing the image download dialogue
- passed the rendering engine id to ToolGroup.addViewport to fix show annotations
- fixed the keep/dismiss aspect feature
- made some UI better scale to the image width
Attempt to use the download image feature with various image types including PDF and video. An error should display for PDF and video.
Use various features of the download image dialogue. They should all work as expected.
semantic-release format and …
> fix(Image Download): various bug fixes for image download

- extensions/cornerstone/src/initWADOImageLoader.js
When using the service userAuthenticationService one may want to add extra headers for security or other reasons. For example, a token may be valid only to a single exam and the developer may want to send that exam id as a header or for example, add a few extra headers for performance tracking (tracing id or others). 
Most places already use all headers like [HERE](https://github.com/OHIF/Viewers/blob/v3-stable/extensions/default/src/DicomWebDataSource/index.js#L113) in  DicomWebDataSource but in the initWado code was different. 
This is a simple change to enable that. 
Only a small fix in initWADO
Tested many exams reading.
Run auto test
etc.)
No Need
[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-fo …
> fix: Add all extra headers to WADO image loader

- extensions/cornerstone-dicom-sr/package.json
- extensions/cornerstone/package.json
- extensions/cornerstone/src/Viewport/OHIFCornerstoneViewport.tsx
- extensions/measurement-tracking/package.json
- extensions/measurement-tracking/src/viewports/TrackedCornerstoneViewport.tsx
- package.json
- platform/core/package.json
- platform/viewer/package.json
- yarn.lock
For a stack viewport, when swapping in a new series either by double click or drag and drop, if the swapped in series had tracked measurements, they were still being rendered with a dashed line.
For a volume viewport (like MPR), the acquisition plane viewport with tracked measurements would render the measurements with dashed lines on first entering MPR; double clicking to/from one up in MPR and swapping in a different series into the MPR view.
For a StackViewport simply rely on the SeriesInstanceUID being part of the tracked measurements or not.
For a VolumeViewport first check the image id of the current image in the viewport and then check the SeriesInstanceUID (like for a StackViewport) if an id is returned. To reliably get the id of the current image, listen for the …
> fix(Measurement): fixed line dashing of measurements in various scenarios

- extensions/default/src/commandsModule.ts
- extensions/measurement-tracking/src/panels/PanelStudyBrowserTracking/PanelStudyBrowserTracking.tsx
- platform/core/src/defaults/hotkeyBindings.js
- platform/core/src/services/HangingProtocolService/HangingProtocolService.ts
- platform/ui/src/components/ThumbnailList/ThumbnailList.tsx
In prior versions of OHIF, it was possible to associate a button with a command to navigate the series in the active viewport forward or backward.
See https://github.com/OHIF/Viewers/issues/3112
The `updateViewportDisplaySet` command was added to match the equivalent command in v2. `PgUp` and `PgDn` hotkey bindings were added to navigate to the previous and next display sets respectively. An option was included to exclude non-image modalities for the navigation.
View a multi-series study in OHIF and use the `PgUp` and `PgDn` keys to navigate the series in the active viewport.
etc.)
[script]: …
> fix(command): Added command and hotkey binding for navigate to next and previous display set.

- extensions/cornerstone-dicom-rt/src/loadRTStruct.js
- extensions/cornerstone/src/services/SegmentationService/SegmentationService.ts
-add try/catch to geometry loader to prevent single error from hanging load
-remove imageId check as ContourImageSequence checked is optional
Try/Catch:
Error in any rt struct segment will stop (hang) all segments from loading.
ContourImageSequence:
Current imageId check is checking for an optional field, causes valid dicomRTs from failing to load.
Current ContourImageSequence check is on:
https://dicom.innolitics.com/ciods/rt-structure-set/roi-contour/30060039/30060040/30060016
There is however a mandatory ContourImageSequence, but should not be checked here:
https://dicom.innolitics.com/ciods/rt-dose/structure-set/30060010/30060012/30060014/30060016
-add try/catch to geometryLoader segment to prevent error from hanging entire load process
-remove ContourImageSequence->imageId check …
> Make ContourImageSequence check under ROIContourSequence->ContourImageSequence optional

- extensions/cornerstone-dicom-seg/src/viewports/OHIFCornerstoneSEGViewport.tsx
Update displaySet metadata parsing logic to extract SpacingBetweenSlices
from SharedFunctionalGroupsSequence / PixelMeasuresSequence
✅ Closes: https://github.com/OHIF/Viewers/issues/3335
> fix: 🐛 Missing SpacingBetweenSlices prevents SEG rendering

- extensions/cornerstone/src/components/DicomUpload/DicomUploadProgressItem.tsx
- extensions/default/src/DicomWebDataSource/index.js
See #3497.
For DICOM store, the response will not be DICOM, so do not set the `Accept` header to be what would be otherwise used for retrieve/query.
See #3497 for how to test/verify that the issue is fixed.
Ensure that store/upload for other data sources (e.g. Orthanc) works properly.
etc.)
> fix(DICOM Upload): use correct Accept header for upload

- extensions/cornerstone/src/services/ViewportService/CornerstoneViewportService.ts
- extensions/cornerstone/src/services/ViewportService/Viewport.ts
The volume3d now is allowed to render the SUV changes. 
etc.)
- [] OS: 
- [] Browser:
> allow volume3d viewport for SUV rendering

- extensions/cornerstone-dicom-seg/src/viewports/OHIFCornerstoneSEGViewport.tsx
Fixes [Issue 3465](Github.com/OHIF/Viewers/issues/3465). This error resulted from the `SliceThickness` variable in `extensions/cornerstone-dicom-seg/src/viewports/OHIFCornerstoneSEGViewport.tsx` having a string value and being unable to call toFixed.
I added `parseFloat` to  a couple of lines in `extensions/cornerstone-dicom-seg/src/viewports/OHIFCornerstoneSEGViewport.tsx` and it seems to have fixed the problem I was having before and renders segmentations. These are my changes (starting at line 346):
``` tsx
...
thickness: SliceThickness ? `${parseFloat(SliceThickness).toFixed(2)}mm` : '',
spacing:
SpacingBetweenSlices !== undefined
? `${parseFloat(SpacingBetweenSlices).toFixed(2)}mm`
: '',
...
```
Before adding these changes, I was faced with a 'Something Went Wrong' warning screen as …
> Address SliceThickness.toFixed TypeError

- platform/core/src/utils/combineFrameInstance.ts
Fixes #3488 
This commit removes any undefined values from the resulting array when combining frame and instance in the `combineFrameInstance` function in the `utils` module.
This Pull Request is intended to resolve an issue with the combineFrameInstance function in the utils module of the OHIF Viewers project. Specifically, the function was previously including undefined values in the resulting array when combining frame and instance 
The effect of this change will be a cleaner output from the combineFrameInstance function, with no undefined values present in the resulting array.
Try the issue above and the provided dicom with this change
- [] My code has been well-documented …
> fix(utils): remove undefined values in combineFrameInstance

- platform/core/src/utils/combineFrameInstance.ts
Fixes https://github.com/OHIF/Viewers/issues/3432
A null check was added in `combineFrameInstance` utility so as to remove `null` `PerFrameFunctionalGroupsSequence` items
Verify that the associated issue is resolved. We were not able to obtain an offending DICOM, so @Michael-Andersen, could you please have a look at this to ensure your issue is resolved? Thank you so much.
etc.)
> fix(utils): remove undefined/null values from the PerFrameFunctionalGroupsSequence in combineFrameInstance.

- extensions/cornerstone/src/services/SegmentationService/SegmentationService.ts
- platform/ui/src/components/SegmentationGroupTable/SegmentationGroup.tsx
Fixes issue https://github.com/OHIF/Viewers/issues/3426
Use the series description for the segmentation label.
Do not allow the segmentation label to wrap in the SegmentationGroup header. Instead use an ellipsis.
Test the associated issue.
etc.)
> fix(segmentation): Use the series description for the segmentation label

- extensions/cornerstone-dicom-sr/src/viewports/OHIFCornerstoneSRViewport.tsx
- extensions/cornerstone/src/Viewport/OHIFCornerstoneViewport.tsx
This PR fixes https://github.com/OHIF/Viewers/issues/3487
Each `OHIFCornerstoneViewport` listens for the `JUMP_TO_MEASUREMENT_VIEWPORT`, but `OHIFCornerstoneSRViewport` should not since it is not a live/tracked viewport.
Ensure that the various scenarios in the issue are addressed.
etc.)
> fix(tracked-measurement): SR viewports disable jump to measurement

- extensions/measurement-tracking/src/panels/PanelStudyBrowserTracking/PanelStudyBrowserTracking.tsx
- extensions/measurement-tracking/src/viewports/TrackedCornerstoneViewport.tsx
Fixes issue https://github.com/OHIF/Viewers/issues/3482
Moved the effect for firing the measurement tracking state machine events from PanelStudyBrowserTracking to TrackedCornerstoneViewport. Since at least one TrackedCornerstoneViewport is always on screen when markups are added, measurements can be tracked even if the side study panel is closed or not even included in the app.
Ensured that the state machine events are only fired once per measurement addition.
Follow the steps in issue #3482 and ensure the desired outcome is achieved.
In general, measurements should be able to be tracked regardless of the visibility and presence of the side panel study browser.
Also ensure that only one measurement tracking state machine event is fired per measurement added. This can be done by putting a …
> fix(Measurement tracking): Side panel study browser can now be closed and measurements are still tracked

- platform/app/src/routes/WorkList/WorkList.tsx
Fixes #3531
Use the flexbox gap style property for spacing between mode buttons
Call preventDefault when the icon embedded in the disabled button is clicked.
Ensure the incorrect behaviour in #3531 is fixed.
Attempt to click the arrow icon inside a disabled mode button. No navigation should occur.
All the area surrounding/near disabled mode buttons should show the 'not allowed' mouse cursor and NOT the pointer cursor.
etc.)
> fix(Worklist): use the flexbox gap style property for spacing between mode buttons

- platform/app/src/utils/OpenIdConnectRoutes.tsx
There is an edge case where user is not defined, and we don't have access token, this gets handled next time we hit the function
etc.)
- [] OS: 
- [] Browser:
> fix(oauth): handle no user scenario

- extensions/default/src/ViewerLayout/index.tsx
- modes/longitudinal/src/index.js
- modes/microscopy/src/index.tsx
- modes/tmtv/src/index.js
- platform/app/src/appInit.js
- platform/app/src/routes/Mode/Mode.tsx
- platform/app/src/routes/WorkList/WorkList.tsx
- platform/app/src/routes/buildModeRoutes.tsx
- platform/core/src/utils/formatPN.js
- platform/docs/docs/configuration/configurationFiles.md
Allowing the override of mode's configuration through viewer config and small improvements.
- [Feature] Ability to override module configuration
- [Improvement] Hardening of patientName util
- [Improvement] Hardening default layout header's return click handler (validating dataSource before appending query params)
- [Improvement] Only render display name button in the worklist if defined in the mode configuration
- [Improvement] Pass appConfig to onModeExit and onModeEnter hooks
What are the effects of this change?
- Before vs After
- Screenshots / GIFs / Videos
-->
etc.)
- [] The documentation page has …
> feature(Mode): Ability to overwrite mode configuration and small improvements

- extensions/default/src/getPTImageIdInstanceMetadata.ts
PR to address OHIF #3411 
Allow for PatientWeight to be missing from the metadata
for a PT series - instead of throwing an exception, simply log a warning. Fixes OHIF issue 3411.
Follow the steps in OHIF #3411
etc.)
> fix(PT Metadata): Allow for PatientWeight to be missing from the metadata

- platform/ui/src/index.js
The checkbox component was not exported at the root of the ui package
etc.)
- [] OS: 
- [] Browser:
> add missing checkbox export

- extensions/default/src/utils/validations/areAllImagePositionsEqual.ts
- extensions/default/src/utils/validations/areAllImageSpacingEqual.ts
- platform/app/src/routes/Mode/Mode.tsx
The bug was introduced in the new feature "DisplaySet Messages." It didn't have proper error handling, causing promises not to settle, leading to infinite loading in the viewer.
I added proper error handling so this issue doesn't occur again and errors are correctly logged in the console.
> Fix(health imaing): studies not loading from healthimaging if imagepositionpatient is missing

- extensions/default/src/DicomJSONDataSource/index.js
- extensions/default/src/DicomWebProxyDataSource/index.js
Stemming from this community issue https://community.ohif.org/t/ohif-viewer-deployed-on-azure-blob-storage-does-not-work-for-dicomjson/1023, I discovered that DICOM JSON loading was broken.  For instance, try this URL...
https://viewer-dev.ohif.org/viewer/dicomjson?url=https://ohif-dicom-json-example.s3.amazonaws.com/LIDC-IDRI-0001.json
The data source method retrieve.series.metadata was not declared as `async` for the DICOM JSON data source and there was code recently added in `Mode.tsx` that assumed a promise was being returned.
Try loading DICOM JSON and it should work.  In particular, this link should work...
https://deploy-preview-3659--ohif-dev.netlify.app/viewer/dicomjson?url=https://ohif-dicom-json-example.s3.amazonaws.com/LIDC-IDRI-0001.json
semantic-release format and …
> fix(DicomJson): retrieve.series.metadata method is async

- platform/app/public/config/default.js
- platform/app/public/config/e2e.js
- platform/app/public/config/local_orthanc.js
- platform/app/public/config/netlify.js
- platform/docs/docs/configuration/url.md
> docs(url): fix incorrect url param in the doc

- platform/app/cypress/integration/measurement-tracking/OHIFMeasurementPanel.spec.js
- platform/app/cypress/support/commands.js
- publish-package.mjs
> chore(publish): fix timeout problem without lerna

- extensions/cornerstone-dicom-seg/src/panels/PanelSegmentation.tsx
- platform/ui/src/components/Notification/Notification.tsx
- platform/ui/src/components/PanelSection/PanelSection.tsx
- platform/ui/src/components/SegmentationGroupTable/SegmentationDropDownRow.tsx
- platform/ui/src/components/SegmentationGroupTable/SegmentationGroupTable.tsx
- https://github.com/OHIF/Viewers/issues/3685#issuecomment-1748782490
- https://github.com/OHIF/Viewers/issues/3685#issuecomment-1748789975
- https://github.com/OHIF/Viewers/issues/3685#issuecomment-1748825628
- https://github.com/OHIF/Viewers/issues/3685#issuecomment-1748833784
etc.)
- [] OS: 
- [] Browser:
> fix(segmentation scroll): and hydration bugs

- extensions/cornerstone/src/services/SegmentationService/SegmentationService.ts
- modes/tmtv/src/toolbarButtons.js
- platform/core/src/services/DicomMetadataStore/createStudyMetadata.js
- platform/docs/docs/configuration/dataSources/configuration-ui.md
- platform/docs/docs/deployment/google-cloud-healthcare.md
Use the active viewport's tool group id when adding a segment.
Small fix for exception when saving a segment.
Some doc updates for google cloud healthcare.
Removed the circle tool from TMTV mode.
A. Attempt to save a segmentation. No exception should be thrown.
B. In MPR mode, add a segmentation, then add a segment. It should work.
C. In TMTV mode, no circle tool should be present.
etc.)
> fix(segmentation):  Various fixes for segmentation mode and other

- extensions/default/src/Panels/createReportDialogPrompt.tsx
- extensions/tmtv/src/utils/dicomRTAnnotationExport/RTStructureSet/dicomRTAnnotationExport.js
- platform/core/src/utils/downloadCSVReport.js
- platform/docs/docs/configuration/configurationFiles.md
- platform/ui/src/components/SegmentationGroupTable/SegmentationGroupSegment.tsx
- fix rt import and multiple data source export
- no need for lock in disable editing mode
etc.)
- [] OS: 
- [] Browser:
> fix(export): wrong export for the tmtv RT function

- extensions/cornerstone/src/tools/CalibrationLineTool.ts
Removed unused code that might have been optimized for production builds which in turn caused an exception to skip the popup prompt.
Fixes #3724 
Removed unused code that might have been optimized for production builds which in turn caused an exception to skip the popup prompt.
See #3724
etc.)
> fix(calibration): No calibration popup caused by perhaps an unused code optimization for production builds

- extensions/cornerstone/src/components/CinePlayer/CinePlayer.tsx
- platform/app/public/config/default.js
- platform/docs/docs/configuration/configurationFiles.md
- platform/ui/src/components/CinePlayer/CinePlayer.tsx
See #2883 and #2939 and thanks go to the authors/contributors of those PRs.
If the DICOM frame time is specified for a display set, use it as the cine frame rate. For those display sets with frame time specified, optionally start playing cine based on configuration. 
Test A
1. Open https://deploy-preview-3735--ohif-dev.netlify.app/viewer?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.1188.2803.137585363493444318569098508293
2. Play cine on each of the various display sets.
3. Notice the frame rate differs per display set.
Test B
1. On a local dev server set the configuration value `autoPlayCine:true`
2. Open http://localhost:3000/viewer?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.1188.2803.137585363493444318569098508293
3. Cine should start playing as each display set is viewed/opened. …
> fix(cine): Use the frame rate specified in DICOM and optionally auto play cine

- extensions/cornerstone/src/tools/ImageOverlayViewerTool.tsx
- modes/basic-test-mode/src/initToolGroups.ts
- platform/app/public/config/e2e.js
Overlays at position 0,0 were getting x,y undefined as the tag was missing.  
Default to 0,0 for these values.
Also, add settings to ensure overlays can be fetched.
Add set to 0 if undefined for origin of overlays
Add bulkdata retrieve for e2e tests (configuration only)
Add default enabled overlay viewer tool for basic test
Find an image with an overlay
Display it, should see the overlay in the main viewer.
Overlays do not appear in the left hand thumbnail.
etc.)
- [] OS: 
- [] Browser: …
> fix(overlay): Overlays aren't shown on undefined origin

- extensions/cornerstone/src/getHangingProtocolModule.ts
- extensions/cornerstone/src/hps/fourUp.ts
- extensions/cornerstone/src/hps/main3D.ts
- extensions/cornerstone/src/hps/mpr.ts
- extensions/cornerstone/src/hps/mprAnd3DVolumeViewport.ts
- extensions/cornerstone/src/hps/only3D.ts
- extensions/cornerstone/src/hps/primary3D.ts
- extensions/cornerstone/src/hps/primaryAxial.ts
See OHIF issues #3744 and #3643.
Added new HPs as described in #3643.
The various ids of the hanging protocols added are listed below. They can be used in OHIF by appending the query parameter `@hangingProtocolId={id}`
- fourUp
- main3D
- primaryAxial
- only3D
- primary3D
etc.)
> feat(HP): Added new 3D hanging protocols to be used in the new layout selector

- extensions/cornerstone/src/tools/ImageOverlayViewerTool.tsx
Adding the ability of rendering inline binary overlays which wasn't previously supported.
Manually tested with a server that sends the overlays with an InlineBinary format.
etc.)
> feat(overlay): add inline binary overlays

- extensions/cornerstone/src/services/ViewportService/CornerstoneViewportService.ts
- extensions/cornerstone/src/services/ViewportService/Viewport.ts
There was a bug where we cannot set the colormap for stack viewports via the hanging protocol.
Add the missing colormap properties in the `_setStackViewport` method.
etc.)
- [] OS: 
- [] Browser:
> fix: colormap for stack viewports via HangingProtocol

- .circleci/config.yml
- extensions/default/package.json
- extensions/default/src/DicomWebDataSource/index.js
- extensions/default/src/utils/getDirectURL.js
- platform/app/package.json
- platform/app/public/config/e2e.js
- platform/core/package.json
- yarn.lock
fixes #3826 
Some PACS systems required requesting encapsulated PDF using multipart/related;type=application/pdf instead of application/octet-stream.  This PR enables the required fetch to be completed.
Change the retrieveBulkdata to use the dicomweb-client 0.10.4 version which allows fetching bulkdata using application/pdf, with a backup of application/octet-stream
Find an encapsulated PDF instance on a DCM4CHEE back end and ensure it displays in OHIF
etc.)
- [] OS: 
- [] Browser: …
> fix: PDF display request in v3

- extensions/default/src/MergeDataSource/index.ts
Adds a check to only reduce data when merge key is present
etc.)
- [] OS: 
- [] Browser:
> fix: 🐛 Check merge key for merge data source

- platform/core/src/utils/isDisplaySetReconstructable.js
This statement as it was doesn't even make any sense in Javascript: if you negate anything it will never result in undefined, ever. It will always be true or false.
So the second check is useless, and thus this is definitely wrong.
Also this will result in false negatives that may crash the application when the program tries to access properties of undefined if iop2 is indeed undefined.
etc.)
- [] OS: 
- [] Browser:
[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untruste …
> fix: is same orientaiton

- extensions/default/src/init.ts
When loading a PT image with missing metadata, the viewer is stuck on the loading screen.
When loading a PT image with missing metadata, `getPTImageIdInstanceMetadata` throws an error and viewer is stuck on loading screen.
Errors from `getPTImageIdInstanceMetadata` are caught and logged. Image is shown without SUV scaling. 
There are already a few early return statements in `handlePETImageMetadata`. If `getPTImageIdInstanceMetadata` throws an error, the behavior is now the same as in those early returns.
etc.)
[script]: …
> fix: catch errors in getPTImageIdInstanceMetadata

- platform/ui/src/components/ErrorBoundary/ErrorBoundary.tsx
- platform/ui/src/components/Modal/Modal.tsx
This makes the stack trace appear line by line instead of a big block of text.
```html
<p className="text-primary-light px-4">Stack: {error.stack}</p>
```
to
```html
<pre className="text-primary-light whitespace-pre-wrap px-4">Stack: {error.stack}</pre>
```
Before:
After:
> feat(errorboundary): format stack trace properly

- extensions/cornerstone/src/services/ViewportService/CornerstoneViewportService.ts
Fixes https://github.com/OHIF/Viewers/issues/4011
since presentation is map, object entries will always return an empty array, we need to iterate over it properly
> fix(presentation-state): Iterate over map properly to restore the presentation state

- extensions/cornerstone/src/services/ViewportService/CornerstoneViewportService.ts
- platform/core/src/services/HangingProtocolService/HangingProtocolService.ts
If the first layout defined, and currently applied has more than one stage and the second or later stages is applied, then the layout selector throws an exception on attempting to change layouts.
Just set the stage index to 0 on changing protocol
Use the URL
http://localhost:3000/basic-test?StudyInstanceUIDs=2.16.124.113543.6004.101.103.20021117.061159.1&hangingProtocolId=@ohif/mnGrid
on a yarn test:e2e:serve
Click comma to navigate to stage index 1 (2cd stage)
Try to change to 3x2 layout
Currently goes black with an exception, expected behaviour is to go to 3x2 layout.
etc.)
- [] The documentation page …
> fix(hp): Fails to display any layouts in the layout selector if first layout has multiple stages

- platform/app/src/routes/index.tsx
The issue was that the `handleUnauthenticated` function passed as a prop to the `PrivateRoute` component was a regular function, which caused a scope issue with `this`. In this function, `this` referred to the global object instead of the instance of `userAuthenticationService`.
-```public handleUnauthenticated() {
return this.serviceImplementation._handleUnauthenticated();
}```
The value of `this` was undefined instead of referring to the instance of `userAuthenticationService`.
I modified the code to pass an arrow function instead of a regular function to the `PrivateRoute` component. This way, `this` is correctly bound to the context of `userAuthenticationService`.
-```<PrivateRoute handleUnauthenticated={userAuthenticationService.handleUnauthenticated}>```
-```<PrivateRoute …
```
> fix(auth): bind handleUnauthenticated to correct context

- platform/ui/src/components/Toolbox/Toolbox.tsx
- platform/ui/src/components/Toolbox/ToolboxUI.tsx
- platform/ui/src/contextProviders/Toolbox/ToolboxContext.tsx
Previouusly you could not click away from the toolbox and then comback but now you can
https://github.com/OHIF/Viewers/assets/7490180/14e92b73-786f-4abd-bb6b-9be8441d1aee
etc.)
- [] OS: 
- [] Browser:
> fix(seg): should be able to navigate outside toolbox and come back later

- package.json
- yarn.lock
Link-extension was still broken due to prettier missing dependency, this PR add prettier and "prettier-plugin-tailwindcss" that are  used in extension template (the plugin needs prettier itself)
I'm not sure if these dev deps shall be add in the main package.json (as was earlier in OHIF and restaured in this PR) or in the extension / mode template
extension-link working again
Linux, node 18
> Add prettier tailwind

- extensions/tmtv/src/commandsModule.ts
We find out that the stdValue return in the cachedStats for the segment in TMTV mode is wrong. We compared it with the same image and ROI and found two different result.
What we have: 
What we should have : 
- Fix stdValue calulation
- Optimize by calculating the mean only once
etc.)
- [] OS: 
- [] Browser:
> fix: stdValue in TMTV mode

- platform/app/public/config/default.js
- playwright.config.ts
- tests/utils/visitStudy.ts
Runs tests against the
yarn test:e2e:serve
configuration e2e.js so that all tests run against the same configuration.
etc.)
- [] OS: 
- [] Browser:
> fix: Tests run against e2e config for both playwright and older tests

- .scripts/dicom-json-generator.js
- extensions/default/src/DicomJSONDataSource/index.js
When loading a multiframe dicom json with multiple instances (each instance with its unique URL) OHIF was generating the image ids using just the first instance URL. Here I'm updating the parsing so it prioritizes the instances from the JSON file
etc.)
- [] OS: 
- [] Browser:
> fix(dicom): Update multiframe DICOM JSON parsing for correct image ID generation

- platform/core/src/services/CustomizationService/types.ts
- platform/ui/src/components/MeasurementTable/MeasurementTable.tsx
Customization types do not match what already exists in custom components. Just fixing it so it comprises everything.
etc.)
- [] OS: 
- [] Browser:
> fix: customization types

- extensions/cornerstone/src/initMeasurementService.ts
Entering MPR mode could lead to unexpected measurements showing. Removing the empty object being returned by the recently introduced crosshairs mapping solved the issue. Now it will return undefined.
Before:
https://github.com/user-attachments/assets/36def401-bb8e-4c41-9fb6-fe3c76d327ba
After:
https://github.com/user-attachments/assets/b674c8db-cf5b-4c9b-b7dc-64a7959d5063
What are the effects of this change?
- Before vs After
- Screenshots / GIFs / Videos
-->
etc.)
- [] OS: 
- [] …
> fix: unexpected mpr measurements

- platform/core/src/utils/roundNumber.js
This fixes roundNumber to handle negative numbers properly. this prevents things like this:
> fix(roundNumber): handle negative numbers properly

- extensions/default/src/DicomWebDataSource/utils/retrieveMetadataFiltered.js
- platform/app/src/routes/Mode/Mode.tsx
- SeriesInstanceUID query param fallback to avoid breaking changes
- Update retrieve metadata filtered func to check enableStudyLazyLoad before merging results
The retrieveMetadataFiltered function logic was specific to lazy study load and would not work if it was disabled. If you had a configuration with disabled lazy study load then this function would not work properly because of the data format of lazy loaded studies.
etc.)
- [] OS: 
- [] Browser:
[blog]: …
> fix: 🐛 SeriesInstanceUID fallback + update retrieve metadata filtered to check for lazy

- platform/ui/src/components/Select/Select.tsx
The ohif/ui select does not work if you try to clear the selection. The onChange function throws an error because it tries to select the length property of null:
etc.)
- [] OS: 
- [] Browser:
> fix(Select): select clear button

- platform/app/src/routes/Mode/Mode.tsx
- platform/app/src/utils/OpenIdConnectRoutes.tsx
In the OpenIdConnectRoutes there was a component which was defined as asynchronous, which causes issues in react.
This caused the following error before redirect: https://react.dev/errors/31?invariant=31&args%5B%5D=%5Bobject%20Promise%5D
To prevent this issue we instead don't await the redirect promise and just return null. Redirect works as expected, but React doesn't complain about its input
Try an OpenIdConnect setup and you will not get a React error prior to redirect after this commit.
> fix(auth): oidc-react-issue

- extensions/cornerstone/src/Viewport/Overlays/ViewportImageScrollbar.tsx
This PR fix getNumberOfSlices that is not defined in 3D viewports.
Use a 3D viewport to test it
etc.)
> fix(updateIndex): getNumberOfSlices is defined when used with a 3D viewport

- extensions/cornerstone/src/services/ViewportService/CornerstoneViewportService.ts
The 3D viewport was throwing exceptions when it tries to resize due to calls to a method that is not implemented. Removing the call makes the viewport resize as expected.
This can be removed when the 3D viewport method is added.
Try the bug here: https://viewer-dev.ohif.org/viewer?StudyInstanceUIDs=2.16.840.1.114362.1.11972228.22789312658.616067305.306.2&hangingProtocolId=only3D
resize the browser
> fix(3d-viewport): exception was being thrown and 3d viewpot not getting resized.

- extensions/cornerstone/src/utils/measurementServiceMappings/LivewireContour.ts
- extensions/cornerstone/src/utils/measurementServiceMappings/PlanarFreehandROI.ts
- extensions/cornerstone/src/utils/measurementServiceMappings/SplineROI.ts
some tools were not rendering displayText if series number is 0, now we check properly for undefined.
> fix(tools): check if seriesNumber is an undefined properly

- extensions/cornerstone/src/hps/fourUp.ts
- extensions/cornerstone/src/hps/main3D.ts
- extensions/cornerstone/src/hps/mprAnd3DVolumeViewport.ts
- extensions/cornerstone/src/hps/only3D.ts
- extensions/cornerstone/src/hps/primary3D.ts
- extensions/cornerstone/src/hps/primaryAxial.ts
This makes it so when a preset is selected it chooses the active displayset.
> fix(hp-presets): select the active displaySet when toggling an HP preset, not a random one from the series panel

- extensions/cornerstone-dicom-seg/src/commandsModule.ts
- extensions/default/src/Actions/createReportAsync.tsx
The createReportDialogPrompt is used to store/export DICOM SEGs. Currently, data is stored whether one click on 'Save' or 'Cancel'. The desired behaviour is that nothing happens if the "Cancel" button is clicked;
- Fixed a condition for an early return in storeSegmentation (the function that creates the report)
- Added an early return in createReportAsync if no report has been created
- Open OHIF in segmentation mode (ex: https://viewer.ohif.org/segmentation?StudyInstanceUIDs=1.3.12.2.1107.5.2.32.35162.30000015050317233592200000046)
- Click "Add segmentation"
- Click on the "..." on the left of the segmentation name
- Click on "Export DICOM SEG"
- Click on "Cancel"
- There shouldn't be a notification indicating a success or failure 
etc.)
additions …
> fix(createReport): early return on cancel in prompt

- extensions/cornerstone/src/services/ViewportService/CornerstoneViewportService.ts
To reproduce:
- Open any study on https://viewer.ohif.org/, the viewport shows something
- Open devtools, and set `display: none` on any parent of the viewport grid (the `<html>` or `<body>` will do fine)
- As expected, nothing is visible
- Unset the `display: none`: the viewer UI is now visible again, but the viewport canvas is stuck on black. Stack scroll does nothing, window level does nothing, a window resize does nothing, the viewport for that display set is entirely black until the page is refreshed
This is unlikely to happen when OHIF itself is the top window, but is much easier to trigger when OHIF is in an iframe. For example, loading multiple OHIF frames and switching between them using `display: none` (which is how this was found)
Trying to do anything with a canvas of …
> fix: avoid black images after hiding the viewports

- platform/app/src/routes/Mode/Mode.tsx
Fixes: https://linear.app/ohif/issue/OHI-1377/[bug]-39-support-for-an-array-of-hangingprotocols-in-a-mode-is-broken
> fix(modes): don't attempt to retrieve a stage index if HPs are an array

- modes/preclinical-4d/package.json
- platform/app/cypress/support/commands.js
Currently the 4D mode is not on NPM, leading to errors when calling OHIF cli commands cuz some information can't be retrieved
example:
longitudinal
4d
> fix(cli): publish 4D preclincial mode on NPM so it can be used in the OHIF cli commands

- extensions/cornerstone/src/services/ViewportService/CornerstoneViewportService.ts
- platform/ui/src/contextProviders/ViewportGridProvider.tsx
If we resize the window in a HP containing a 3D viewport we currently have this error : 
`CornerstoneViewportService.ts:1087 Caught resize exception TypeError: Cannot convert undefined or null to object
at CornerstoneViewportService.ts:1065:29
at Array.forEach (<anonymous>)
at un.performResize (CornerstoneViewportService.ts:1059:17)
at un.resize (CornerstoneViewportService.ts:154:12)
at Object.callback (init.tsx:215:32)
at pubSubServiceInterface.ts:88:16
at Array.forEach (<anonymous>)
at N.l [as _broadcastEvent] (pubSubServiceInterface.ts:87:31)
at N.setViewportGridSizeChanged (ViewportGridService.ts:163:10)
at Object.setViewportGridSizeChanged (ViewportGridProvider.tsx:511:50)`
See also this video showing image being distorted while resizing in a HP having 3D viewport: 
[Screenity video …
> Fix : Resize was broken if 3d viewport displayed in HP

- platform/core/src/services/WorkflowStepsService/WorkflowStepsService.ts
- Users can specify an `onEnter` hook which may be a single function/command or an array of functions/commands but due to an issue it was not working for the first case.
- There is no `onExit` hook which may be very useful in some cases.
Fixed how `WorkflowStepsService` validates if `callbacks` is an array and added support for `onExit` hook.
- Define an `onEnter` hook for a single function/command in `getWorkflowSteps` and launch the viewer. You can do that in 4D mode since it is the only mode currently using `WorkflowStepsService`.
- Define an `onExit` hook for single or multiple functions/commands and verify if they are invoked after moving from step `A` to `B`.
> fix(WorkflowSteps): fixed how hooks are invoked + added support for 'onExit' hook

- platform/core/src/extensions/ExtensionManager.ts
OHIF's managers (`servicesManager`, `commandsManager`, `hotkeysManager` and `extensionManager`) need to be passed down the function call tree which can result in a considerable amount of refactoring when we need some of them in a function called at +4th level (all functions up in the call tree need to be updated until we reach one that receives desired manager as parameter). 
Added `extensionManager` along all other managers to `extension.onModeEnter`. In that way it is possible to create a extension context when `onModeEnter` is called and all managers can be stored into it. If a method at any level needs to have access to one or more managers there is no need to change the functions up in the call tree and we can solve the problem adding a single line of code:
```javascript
import …
```
> feat(extension): added 'extensionManager' to 'onModeEnter' parameter list

- platform/app/src/routes/Mode/defaultRouteInit.ts
The second `displaySetService.makeDisplaySets(...)` is an object ("options") but `defaultRouteInit` is passing `madeInClient` as a boolean making the new dynamic displaySets created without the `madeInClient` property as expected.
Fixed the way `displaySetService.makeDisplaySets` passing `{ madeInClient }` instead of a boolean value.
> fix(defaultRouteInit): fixes 'madeInClient' parameter when 'makeDisplaySets' is called

- platform/app/src/routes/WorkList/WorkList.tsx
This PR fixes bug #4580, where the Worklist component was mutating the original studies array from the DatasourceWrapper component. This mutation caused state inconsistencies when the parent component updated the studies value, leading to incorrect behavior (e.g., patient switching) during sorting and row expansion.
Before (buggy):
https://github.com/user-attachments/assets/c9e2a0ed-5714-4f60-a4ac-f710695b0136
After (fixed):
https://github.com/user-attachments/assets/01de8a9f-686f-4788-9f90-3b82df449c73
> fix(worklist): selected patient changes randomly when clicked. 

- extensions/default/src/Panels/WrappedPanelStudyBrowser.tsx
DICOM Tag Brower was not working in segmentation mode. The issue was that the commandsManager was not passed to the panel. This is now resolved.
Fixes https://github.com/OHIF/Viewers/issues/4595
> [OHI-1483] fix(tag-browser): fix dicom tag browser not loading in segmentation mode in study panel

- extensions/cornerstone-dicom-pmap/src/viewports/OHIFCornerstonePMAPViewport.tsx
- extensions/cornerstone-dicom-rt/src/loadRTStruct.js
- extensions/cornerstone-dicom-rt/src/viewports/OHIFCornerstoneRTViewport.tsx
- extensions/cornerstone-dicom-seg/src/viewports/OHIFCornerstoneSEGViewport.tsx
- extensions/cornerstone-dicom-sr/src/components/OHIFCornerstoneSRMeasurementViewport.tsx
- extensions/cornerstone/src/hps/frameView.ts
- extensions/cornerstone/src/services/SegmentationService/SegmentationService.ts
- extensions/cornerstone/src/services/ViewportService/CornerstoneViewportService.ts
- extensions/default/src/getHangingProtocolModule.js
- extensions/default/src/hangingprotocols/hpCompare.ts
- extensions/default/src/hangingprotocols/hpMNGrid.ts
- extensions/default/src/hangingprotocols/hpScale.ts
- extensions/test-extension/src/hpTestSwitch.ts
- platform/app/public/config/local_orthanc.js
- yarn.lock
fixes https://github.com/OHIF/Viewers/issues/4593
and it fixes the initial slice to load for SEG and RTSTRUCT to be the slice that has data and is not empty
> fix(seg): jump to the first slice in SEG and RT that has data

- extensions/cornerstone/src/panels/PanelSegmentation.tsx
- extensions/cornerstone/src/services/SegmentationService/SegmentationService.ts
- extensions/default/src/DicomLocalDataSource/index.js
- Adds a check for both SOPClassUID spellings: SOPClassUID, SopClassUID.
- Adds some metadata to the derived segmentation images
Fixes OHI-1479. this problem is only in local, when I tried with Orthanc there was no issues
> [OHI-1479] fix(segmentation): black preview when loading a seg, and crash on opening panel

- extensions/cornerstone/src/components/WindowLevelActionMenu/VolumeLighting.tsx
- extensions/cornerstone/src/components/WindowLevelActionMenu/VolumeRenderingOptions.tsx
- extensions/cornerstone/src/components/WindowLevelActionMenu/VolumeShade.tsx
- extensions/cornerstone/src/types/ViewportPresets.ts
Implemented disabling of light sliders when the shade option is turned off in 3D rendering mode. 
This PR has been incorporated by [FlyWheel.io](https://flywheel.io/).
Close https://github.com/OHIF/Viewers/issues/4629
A new state was added to manage the toggled status of the shade in VolumeRenderingOptions. Based on this value, I applied a disabled property to the input sliders and added the corresponding disabled CSS classes to indicate that they were inactive. With this update, the sliders will be disabled when the shade is turned off.
https://github.com/user-attachments/assets/ab0be4b0-1ab5-4e5b-8c0e-0b6f1494f815
1. Launch a study in 3D layout.
2. Select the Window Level Action menu.
3. Select Rendering Options.
4. Turn off the Shade toggle switch.
5. Observe the sliders.
6. The …
> fix(3D rendering): disabled light sliders when shade is off

- platform/app/.recipes/Nginx-Orthanc/config/nginx.conf
- platform/app/public/config/default.js
- platform/app/public/config/e2e.js
This adds a localhost datasource for orthanc, according to the recipe in platform/app/.recipes
Allows development testing against the local orthanc datasource
etc.)
- [] OS: 
- [] Browser:
> fix: orthanc datasource dev

- extensions/cornerstone/src/components/WindowLevelActionMenu/VolumeRenderingPresetsContent.tsx
- platform/ui-next/src/components/Icons/Icons.tsx
- platform/ui-next/src/components/Icons/Sources/NotificationWarning.tsx
Fixes some icons that were not being display due to small name differences, or just being missing after the migration.
Closes #4652
Closes OHI-1538
> [OHI-1538] fix(icons): icons missing for volume presets and others

- .docker/Viewer-v3.x/entrypoint.sh
Docker compression step was not being triggered if APP_CONFIG is not present, but it should still do if a user mounts a file using volumes.
Fixes OHIF-1547
Closes #4669
> [OHI-1547] fix(docker): run compression regardless of APP_CONFIG being present ( in cases such as volume mount)

- platform/docs/docs/migration-guide/3p8-to-3p9/5-StateSyncService.md
[extensions/default/src/utils/reuseCachedLayouts.ts](https://github.com/OHIF/Viewers/blob/7a13c28eb3560466896bbf1c76fc178e02d96fee/extensions/default/src/utils/reuseCachedLayouts.ts#L31)
[extensions/default/src/commandsModule.ts](https://github.com/OHIF/Viewers/blob/7a13c28eb3560466896bbf1c76fc178e02d96fee/extensions/default/src/commandsModule.ts#L180)
I think .getState() is required for useViewportGridStore()
> migration docs typo (3.8 -> 3.9, useViewportGridStore())

- platform/core/src/hooks/useToolbar.tsx
- Measurement tools, crosshair tools and window level tools are enabled in the volume3D viewport.
- This PR has been incorporated by [FlyWheel.io](https://flywheel.io/).
- Close https://github.com/OHIF/Viewers/issues/4676
Changes to  add LAYOUT_CHANGED event to refresh toolbar state, which will update the tools in the header toolbar
Results:
Disable Measurement, crosshair and window level tools  if voulme3D viewport is active.
https://github.com/user-attachments/assets/f5e94dd1-8429-40dc-8604-3d9f57af7b15
- Select 3D primary layout from the grid layout
- Activate volume viewport (not volume3D).
- Switch to 3D Only layout
- Verify the header tools like crosshair, measurement tools, windowlevel are disabled if volume3D viepwort is active.
etc.) …
> fix(header tools in volume3D): All header tools are enabled in volume3D viewport 

- extensions/cornerstone/src/commandsModule.ts
- extensions/cornerstone/src/components/WindowLevelActionMenu/WindowLevelActionMenu.tsx
- extensions/measurement-tracking/src/contexts/TrackedMeasurementsContext/TrackedMeasurementsContext.tsx
- After disabling the prompts, the initial image calculation for the SR issue was fixed.
- This PR has been incorporated by [FlyWheel.io](https://flywheel.io/).
- Close https://github.com/OHIF/Viewers/issues/4731
- Added initial image options to the viewport options while setting the displaysets from trackedMeasurementsContext.tsx file in order to get the initailImageIndex to be loaded after loading an SR after disabling the prompts.
- Added a null checking in WindowlevelActionMenu inorder to prevent the error displayd while loading the SR after disabling the prompts.
Initial image is correctly loaded now after disabling the prompt and loading the SR.
etc.)
[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrust …
> Fix for initialImageIndex mismatch issue for loading SR after disabling prompts

- extensions/default/src/customizations/onDropHandlerCustomization.ts
- extensions/default/src/getCustomizationModule.tsx
- platform/app/src/components/ViewportGrid.tsx
- platform/docs/docs/platform/services/customization-service/sampleCustomizations.tsx
- An option has been implemented to allow custom onDropHandler in viewort grid. This enhancement enables users for handling of additional functionalities during the onDrop event to the viewport.
- This PR has been incorporated by [FlyWheel.io](https://flywheel.io/).
- Introduced a custom onDropHandler to handle additional functionalities during the onDrop to the viewpor
etc.)
> Feat/custom onDropHandler for viewportGrid

- platform/ui-next/src/components/SegmentationTable/SegmentationSegments.tsx
We removed the logic where the panel should take 200px by number of segments due to the fact that it can't work with Tailwind.
Writing something like `h-[${segmentCount * 200}px]` does not work because Tailwind does not know which number of segments to generate in advance.
Removed non-functional logic for dynamic height of the segmentation panel
etc.)
- [] OS: 
- [] Browser:
[script]: …
> feat: Remove non-functional Tailwind class for SegmentationPanel

- extensions/cornerstone/src/panels/PanelSegmentation.tsx
- extensions/default/src/Components/MoreDropdownMenu.tsx
- extensions/default/src/customizations/studyBrowserCustomization.ts
In segmentation mode, exporting a segmentation would incorrectly prioritize the `storeSegmentation` command from the `cornerstone-dicom-seg` extension instead of first invoking the regular `cornerstone` extension command to retrieve the data source before passing it to the second command.
This behavior occurred because `storeSegmentation` exists in both modules, causing it to default to `cornerstone-dicom-seg` first. Other commands did not face this issue since they do not exist in `cornerstone-dicom-seg`, allowing them to fall back to `cornerstone` as expected. 
This has been resolved by explicitly passing the `CORNERSTONE` context name to ensure the correct command execution order.
Fixes #4584 
Fixes OHI-1445
> [OHI-1445] fix(store-segmentation): storing segmentations was hitting the wrong command resulting in an undefined datasource

- platform/ui/src/components/ContextMenu/ContextMenu.tsx
Fixing regression introduced by PR https://github.com/OHIF/Viewers/issues/4727
Longer/taller context menus are incorrectly opening from bottom to top and are getting clipped.
In most cases, taller (custom) context menus are opening "bottom-to-top" from the click point even though there is enough space to open them (the desired) "top-to-bottom". Furthermore, the menus are also getting clipped at the top of the browser window. See the screen shot below...
In this screen shot there is plenty of space to open the menu in its traditional sense. Yet, look at how it opens "bottom-to-top" and is clipped at the top.
The logic in ContextMenu.tsx was incorrectly adding the height of the menu to the bottom max point to test if the menu were off the screen. This was changed to just test the bottom max …
> fix(context-menu):  Fixing regression introduced by PR #4727

- platform/app/src/state/appConfig.tsx
- platform/core/src/services/UIModalService/index.ts
- platform/docs/docs/platform/services/ui/ui-modal-service.md
- platform/ui/src/contextProviders/ModalProvider.tsx
- Added support for a custom Modal component in ModalProvider without modifying App.tsx.
- Exposed setAppConfig in the appConfig provider to allow adding custom configurations without modifying App.
- Implemented new logic in UIModalService and ModalProvider to support a custom Modal component without modifying App. If no custom component is provided, the default modal will be rendered. Users can set a custom component through the setServiceImplementation method.
```
uiModalService.setServiceImplementation({
component: Modal,
});
```
- Exposed setAppConfig from the appConfig provider to allow adding custom configurations from the application without modifying App.tsx. 
**Modal**
- Create a new Modal component 
-  Set the new component using the setServiceImplementation method.
``` …
```
> feat: Add support for Custom Modal component in Modal Service

- extensions/dicom-microscopy/src/DicomMicroscopyViewport.tsx
- extensions/dicom-microscopy/src/components/ViewportOverlay/index.tsx
- extensions/dicom-microscopy/src/index.tsx
- platform/core/src/contextProviders/SystemProvider.tsx
Making the `extensions/dicom-microscopy/src/DicomMicroscopyViewport.tsx` a functional component to use the `useAppState` hook and pass down the app config in order to enable viewport overlays.
Before (no overlays):
After (possibility of adding overlays with config): 
etc.)
- [] OS: 
- [] Browser:
> feat: add viewport overlays to microscopy mode

- extensions/cornerstone-dicom-rt/src/viewports/OHIFCornerstoneRTViewport.tsx
- extensions/cornerstone-dicom-seg/src/viewports/OHIFCornerstoneSEGViewport.tsx
- extensions/cornerstone/src/index.tsx
- extensions/cornerstone/src/utils/index.ts
- extensions/cornerstone/src/utils/segmentUtils.ts
- platform/ui-next/src/components/DataRow/DataRow.tsx
Implements/fixes [[feat] Selected Segment is not used when iterating over #4614](https://github.com/OHIF/Viewers/issues/4614).
The navigation between segments when using viewport arrows was inconsistent when selecting manually a SEG and then using arrow. 
The functionality was improved by
a) Synchronizing index of arrow looping with the selected segment. If the SEG is changed manually to any position the next time an arrow is pressed the selected segment is retrieved and used to continue navigation from there and not the previous position.
b) I noticed that Segments (and RTS segments also) can be so many that the list must be scrolled to detect the selected segment. Previously when arrows were used the selected segment was not visible on the list. Now it is but if you press right arrow …
> feat(Segments Looping) : Fixed looping through Segments of SEG

- platform/app/src/components/ViewportGrid.tsx
This PR fixes the broken activateViewportBeforeInteraction setting that was causing issues with viewport interaction. The previous implementation was not properly controlling viewport activation behavior.
Modified `onInteractionHandler` in `ViewerViewportGrid.jsx` to only call `preventDefault()` and `stopPropagation()` when `activateViewportBeforeInteraction` is enabled
Previously, the activateViewportBeforeInteraction setting was not working correctly. The code attempted to use the pointer-events-none CSS class, but this approach was not effective for controlling viewport interaction.
Now, the `activateViewportBeforeInteraction` setting properly controls viewport behavior:
- When enabled: Users must first click a viewport to activate it before using tools
- When disabled: Users can …
> Fix broken activateViewportBeforeInteraction behavior

- extensions/default/src/DicomTagBrowser/DicomTagTable.tsx
Currently, when you collapse a row the heights of the rows are not recalculated, which may cause rows with wrong heights and missing/unreadable text. This PR fixed it by forcing it to recalculate the heights once a row is collapsed or expanded.
**Before:**
Expanded with correct heights
But collapsed with wrong heights
**After:**
Expanded with correct heights
And also collapsed with correct heights
etc.)
- [] OS: 
- [] Browser:
[blog]: …
> fix: dicom tag browser row height on toggle

- platform/app/src/components/ViewportGrid.tsx
- platform/ui-next/src/components/Viewport/ViewportPane.tsx
- platform/ui-next/src/contextProviders/ViewportGridProvider.tsx
This removes the viewport gap and updates the border behavior.
I weighted different options to achieve this, and I believe this is the most reasonable. I wanted to go for a grid approach, but that would break how hanging protocols work and their custom viewport positioning, so we need to stay on the current approach of absolute positioning with a calculated width and a height. For this reason I added a `getBorderStyle` function that can help us get the right borders without needing a display grid parent.
https://github.com/user-attachments/assets/f723a49c-f8e6-48e1-a94b-01c3d3de515d
Fixes: https://linear.app/ohif/issue/OHI-1640
@sedghi @dan-rukas
> feat(viewport-gap): remove viewport gap and update border behavior

- extensions/cornerstone/src/utils/measurementServiceMappings/CircleROI.ts
Area calculations on SM and other non-stack/volume modalities can't compute pixel value units.  This just hides "NaN" for circle annotations for now, and shows perimiter if defined instead.
etc.)
- [] OS: 
- [] Browser:
> fix: Skip showing NaN for average pixel/max value

- extensions/default/src/customizations/reportDialogCustomization.tsx
- extensions/default/src/utils/promptSaveReport.tsx
- platform/core/src/extensions/ExtensionManager.ts
Datasource selection is not working when saving a SR. Instead it is always saving to the active datasource. 
This PR will accomplish the following:
1. Now the datasource selection will work and OHIF will attempt to save to the selected datasource
2. The first suggestions will always be the active datasource for a better UX
3. Improve naming of the `activeDatasource` private variable inside the ExtensionManager, which actually representes only the name of the active datasource.
Before:
https://github.com/user-attachments/assets/52001fbe-1eda-478e-ab16-cef8b0195183
After:
https://github.com/user-attachments/assets/ba2f136c-3ce9-4146-804e-8daab964e544
- [] My code has been …
> fix: make datasource selection work

- extensions/dicom-microscopy/src/utils/dicomWebClient.ts
- platform/core/src/extensions/ExtensionManager.ts
The `dicomWebClient.ts` file was directly accessing a private property (named `activeDataSource` in the past, but recently renamed to `activeDataSourceName`) from the `ExtensionsManager`. This private access caused issues in certain features, such as microscopy mode which was broken.
This PR resolves the issue by introducing a public getter for `activeDataSourceName` in `ExtensionsManager` and updates `dicomWebClient` to use the getter, ensuring proper encapsulation and avoiding direct access to internal properties.
etc.) …
> fix(dicomWebClient): use public getter for activeDataSourceName instead of accessing private property

- extensions/cornerstone-dicom-seg/src/commandsModule.ts
- extensions/default/src/DicomWebProxyDataSource/index.ts
Added ability to save Segmentation files back to Kheops
Before: Not able to save Segmentation files back to Kheops applications when hosting the new Segmentation Mode locally, but storing the data in a remote server. After: The Segmentation files save as expected.
Host this branch locally, ensuring the config file is pointing to Kheops. Open a study from a remote server, change the url to localhost:3000/Segmentation... then save a Segmentation. It should appear in the series list for that study.
etc.)
- [] OS: 
- [] Browser:
[script]: …
> fix(DicomWebProxyDataSource): bug fix to save Segmentation files back to Kheops

- platform/app/src/routes/index.tsx
When `showStudyList` is set to `false`, the not found boundary redirects to an inexisting study list. 
I've fixed the code so that it only redirects if `showStudyList` is `true`
You can test it by visiting http://localhost:3000/notfoundstudy, in `default.js` you toggle `showStudyList` between true and false.
etc.)
additions or removals. 
> fix(NotFoundStudy): Fixed the viewer not-found page when showStudyList: false

- platform/core/src/services/ViewportGridService/ViewportGridService.ts
This allows for creating a decorated version of an existing provider.
Take for example the following snippet of code that replaces the base, cornerstone seg presentation id provider to limit which viewports display segmentations.
```
const segmentationPresentationTypeId = 'segmentationPresentationId';
baseSegPresentationIdProvider = viewportGridService.getPresentationIdProvider(
segmentationPresentationTypeId
);
const mySegPresentationIdProvider = (
id: string,
props: {
viewport: AppTypes.ViewportGrid.Viewport;
viewports: AppTypes.ViewportGrid.Viewports;
isUpdatingSameViewport: boolean;
servicesManager: AppTypes.ServicesManager;
}
): string | undefined => {
if (id !== segmentationPresentationTypeId) {
return;
}
const baseSegPresentationId = baseSegPresentationIdProvider(id, props);
const …
```
> feat(viewport): Added getter for presentation id provider.

- bun.lock
- platform/ui-next/src/components/Dialog/Dialog.tsx
- platform/ui-next/src/contextProviders/ManagedDialog.tsx
- platform/ui/src/components/ContextMenu/ContextMenu.tsx
See #5048 .
Moved the reposition logic from the context menu to the dialog component. This has two benefits...
- the context menu should not reposition itself by changing coordinates that its ancestor is using to position it
- dialogs that are fixed position should have reposition logic in general
The problematic behaviour seen in #5048  should no longer occur.
etc.)
> fix(context-menu): Move the reposition logic from the context menu to the dialog component.

- bun.lock
- extensions/cornerstone/src/synchronizers/frameViewSynchronizer.ts
See #4689 
Listen for STACK_VIEWPORT_SCROLL instead of CAMERA_MODIFIED in frameViewSynchronizer.
CAMERA_MODIFIED is also called by the pan-zoom synchronizer and thus clashes with stack scrolling.
#4689  should be fixed.
Scroll, window level, pan and zoom should all be synchronized for frame view.
etc.)
> fix(frame-view): After pan and/or zoom, stack scroll is now synchronized for frame view

- bun.lock
- extensions/cornerstone/src/utils/CornerstoneViewportDownloadForm.tsx
While assessing #3799 I noticed that the `Include annotations` setting was NOT being respected in the image capture dialogue. Here are some steps to reproduce what I witnessed...
1. Launch https://viewer-dev.ohif.org/viewer?StudyInstanceUIDs=1.3.6.1.4.1.25403.345050719074.3824.20170125095438.5
2. Add an annotation to the series displayed.
3. Click the `Capture` tool icon.
4. The `Download High Quality Image` dialogue appears. Note that the annotation added previously is displayed on the image (as it should).
5. Clear the `Include annotations` radio button.
6. Notice that the annotation still appears on the image (but it shouldn't)
7. Click the `Save` button.
8. View the downloaded image and notice that the annotation appears there too (but it shouldn't).
The title of the PR says it all. 😊 …
> fix(capture): Disable or enable the tool group based on the show flag.

- bun.lock
- extensions/cornerstone/src/components/WindowLevelActionMenu/VolumeRenderingPresetsContent.tsx
- extensions/cornerstone/src/components/WindowLevelActionMenu/WindowLevelActionMenu.tsx
- extensions/cornerstone/src/hooks/useViewportRendering.tsx
- platform/ui-next/src/components/AllInOneMenu/Menu.tsx
See issue #5112 
The top level `AllInOneMenu` must update the menu path if its props change.
Use better initialization for the `is3DVolume` to avoid a flicker of the window level menu. 
Grab the `commandsManager` with the `useSystem` hook.
Issue #5112 should be fixed.
etc.)
> fix(WindowLevelActionMenu): The window level menu must show different contents for 3D volume viewports

- platform/app/cypress/integration/ImageConsistency.spec.js
- platform/docs/docs/migration-guide/3p9-to-3p10/3-UI/2-Migration-3p10-Icons.md
- platform/docs/docs/migration-guide/3p9-to-3p10/3-UI/8-Migration-3p10-DialogService.md
- platform/docs/docs/migration-guide/3p9-to-3p10/3-UI/9-Migration-3p10-ModalService.md
This pull request updates the migration guides for transitioning to OHIF 3.10, focusing on UI components like custom icons, dialog service, and modal service. Key changes include introducing new patterns for creating and managing custom icons, updating dialog and modal APIs, and improving the structure of footer action buttons.
* Added a new section on migrating custom icons from SVG imports to React component-based icons for better consistency and type safety. Steps include converting SVG files to React components and registering them with the `Icons` service. (`platform/docs/docs/migration-guide/3p9-to-3p10/3-UI/2-Migration-3p10-Icons.md`, [platform/docs/docs/migration-guide/3p9-to-3p10/3-UI/2-Migration-3p10-Icons.mdR136-R196](diffhunk://#diff-d963fd0f608be1b5fc96db6eb32ed46e90c1defe555e …
> docs: improved migration guides for 3p10

- extensions/cornerstone/src/getToolbarModule.tsx
Currently the image slice sync tool is never marked as enabled, because there is a bug in getting the synchronizer type.
The bug is caused by the fact that `commands` is a child of `button.props`, not `button`.
The check for `synchronizers.length <= 1` makes sure the tool is marked as disabled after enabling and then disabling.
Before:
After:
etc.)
- [] OS: 
- [] Browser:
> fix(getToolbarModule): fix enabled state of image slice sync

- platform/core/src/services/ToolBarService/ToolbarService.ts
This change allows us to define hideWhenDisabled at the prop level in the case of having multiple evaluators
```ts
{
id: 'orientationMenu',
uiType: 'ohif.viewportOrientationMenu',
props: {
label: 'Orientation',
tooltip:
'Change viewport orientation between axial, sagittal, coronal and acquisition planes',
evaluate: [
{
name: 'evaluate.orientationMenu',
},
{
name: 'evaluate.viewport.supported',
unsupportedViewportTypes: ['video', 'volume3d'],
},
],
hideWhenDisabled: true,
},
},
``
> fix(action-corners): check hideWhenDisabled at both the evaluator and prop levels

- platform/core/src/services/HangingProtocolService/HangingProtocolService.ts
- platform/core/src/types/HangingProtocol.ts
Adds `onStageChange` callback for hanging protocols, currently we have:
```
onProtocolExit -> leaving HP
onProtocolEnter -> entering HP
onLayoutChange -> grid layout tool (setViewportGridLayout)
onViewportDataInitialized -> data load
```
This adds `onStageChange`
``
onStageChange -> going back/forward in the HP stages
``
> feat(hp): add onStageChange callback

- extensions/cornerstone/src/commandsModule.ts
The measurement update call was not passing in the existing measurement and just the label, leading to the measurement becoming just a label...
> fix(labeling): measurement labeling dialog was overwriting the entire measurement and breaking it

- extensions/cornerstone/src/services/ViewportService/CornerstoneViewportService.ts
fixes https://github.com/OHIF/Viewers/issues/5147 
fixes https://github.com/OHIF/Viewers/issues/5059
Sometimes when properties are reset on a stack, a default colormap is set of Grayscale, however an empty opacity array is also set, which breaks the viewports
`{name: 'Grayscale', opacity: []}`
This adds a check for empty opacity arrays and removes them before setting the lut presentation
> fix(black-viewports): MPR viewports were turning black if their parent stack had it's properties reset

- extensions/default/src/DicomWebDataSource/dcm4cheeReject.js
Fixes [#5226](https://github.com/OHIF/Viewers/issues/5226)
The `dataSource.reject.series` method currently only treats HTTP 204 (No Content) as a successful response. However, the DCM4CHEE server returns HTTP 200 (OK) on success. As a result, the promise is not resolved, leading to an infinite loading state in the UI.
This PR adds support for HTTP 200 as a valid success response and includes a `default` case to handle unexpected status codes gracefully.
- Add handling for HTTP 200 response to properly resolve the `reject` request.
- Add `default` case to `switch` to reject on unexpected HTTP status codes.
- Fix missing UI response after clicking deleting.
- Open a study with available series.
- Trigger a reject operation on a series.
- Confirm that the rejection completes successfully …
> Handle 200 status response and add default error handling

- tests/SegmentationPanel.spec.ts
-test segmentation from PACS jumps to center when clicked on segmentation panel
Create test for 
1. Basic add, rename, and delete
2. Jump to center slice index when segment loaded from PACS (note that it seems this only works for segments loaded from PACS and not new segments or newly modified segments)
etc.)
- [] OS: 
- [] Browser:
> test(SegmentationPanel): add test for jump to center of segments from PACS and basic add, rename, delete from panel

- extensions/cornerstone/src/components/AdvancedRenderingControls/AdvancedRenderingControls.tsx
- extensions/cornerstone/src/components/ViewportColorbar/ViewportColorbar.tsx
- extensions/cornerstone/src/components/ViewportColorbar/ViewportColorbarsContainer.tsx
- platform/core/src/hooks/useViewportMousePosition.ts
- tests/SEGHydration.spec.ts
- tests/SEGHydrationFromMPR.spec.ts
Prior to this PR, the `AdvancedRenderingControls`  were only working and looking properly at the bottom of a viewport.
`ViewportMousePosition` now has a utility for determining if the mouse pointer is in a normalized area/range of the viewport. This is useful particularly for the `AdvancedRenderingControls` that are to be hidden and shown based on the relative mouse pointer location.
A `isHorizontal` utility function was added for the `ViewportColorbar` to determine, based on its position, whether it is horizontal or not (i.e. vertical).  This function is used in several locations to set the proper styling for the `ViewportColorbar` and to determine if the full set of colorbars should be shown or not.
In a mode, add the `AdvancedRenderingControls` to either the top or bottom middle of the …
> fix(colorbar): Allow for `AdvancedRenderingControls` to be placed at the top or bottom of the viewport.

- extensions/cornerstone-dicom-sr/src/components/OHIFCornerstoneSRMeasurementViewport.tsx
- extensions/cornerstone-dicom-sr/src/getSopClassHandlerModule.ts
- extensions/cornerstone-dicom-sr/src/utils/addSRAnnotation.ts
- modes/longitudinal/src/initToolGroups.js
- modes/usAnnotation/src/initToolGroups.js
The 3d sr loading got broken due to removing a sop class uid from a list of supported classes.
Additionally, this PR adds the view reference to the unloaded SOP class to help with navigation.
Use the two point example SR from  https://github.com/OHIF/Viewers/issues/5082
Hydrate the SR, and you should see two lesion annotations, displayed as probe instances.
The points are not visible until after hydration - there is an issue with needing an image id to navigate to in the SR display set,
AND with needing an image id to be visible in the stack viewport.  This isn't an issue after rehydration.
etc.)
- [] …
> fix: load 3dsr

- extensions/cornerstone-dicom-rt/src/getSopClassHandlerModule.ts
- extensions/cornerstone-dicom-rt/src/loadRTStruct.js
- extensions/cornerstone/src/services/SegmentationService/SegmentationService.ts
While investigating the RT Struct SOP Class Handler I noticed that the DisplaySets were being loaded over again if they already were loaded previously and could live in a cache. There was a "TODO" marker to make the feature available, so I investigated it and added an implementation that I could verify that was preventing new loading calls to be done, by early exiting the `_load` function if the RTStruct and Segmentation are already loaded.
Made the commits atomic and well commented so they document themselves, except by the one responsible for the main reason for the PR itself, that is documented below:
4d01f40e75f6607a3ec85e54cbfe195af8d07dde: The old implementation would use the `_segmentationExistsInCache` function to validate if the display set needed to be loaded again, but it was …
> fix(cornerstone-dicom-rt): adding caching usage to cornerstone-dicom-rt SOP Class Handler

- extensions/cornerstone/src/initCornerstoneTools.js
- modes/segmentation/src/index.tsx
- modes/segmentation/src/initToolGroups.ts
- modes/segmentation/src/toolbarButtons.ts
The objective of this step is to introduce a new tool called LabelMapEditWithContourTool to the existing label map tools. In CS3D this tool can be seen in the `labelmapEditWithContourAutomatic` example.  `bun run example labelmapEditWithContourAutomatic`
Added the tool.
Note that the icon will be updated once it is decided upon.
1. Load a study with SEG series.
2. Activate the Label Map Edit with Contour tool.
3. Start the tool in an existing label map segment. Once the you are finished drawing the contour with tool, the underlying label map the tool was started on will stretch out to occupy the area drawn - even if the area drawn stretches into another label map segment.
etc.)
[blog]: …
> feat(segmentation): Added the LabelMapEditWithContourTool.

- extensions/cornerstone/src/commandsModule.ts
- modes/longitudinal/src/index.ts
- modes/longitudinal/src/toolbarButtons.ts
In PR #5422 I dropped the segmentation label tool from longitudinal/basic viewer mode.
This restores it.
1. Launch longitudinal mode with a study that has SEG series (e.g. https://viewer-dev.ohif.org/viewer?StudyInstanceUIDs=1.3.12.2.1107.5.2.32.35162.30000015050317233592200000046)
2. Hydrate the SEG series.
3. The segmentation label tool should appear under the more menu.
etc.)
> fix(segmentation): Restored segment label tool in longitudinal mode.

- extensions/cornerstone/src/commandsModule.ts
- extensions/cornerstone/src/services/SegmentationService/SegmentationService.test.ts
- modes/segmentation/src/toolbarButtons.ts
- platform/ui-next/src/components/OHIFToolSettings/ToolSettings.tsx
@dan-rukas pointed out that for tool settings we were using checkbox components, however the OHIF standard should be to use a switch component.
Changed to using a switch component instead of a checkbox.
All of the contour tool options should use a switch component. Use this [link](https://multi-tab-seg.netlify.app/) to test.
etc.)
> fix(ToolSettings): Added Switch component to ToolSettings. In general, we should use Switch instead of Checkbox.

- platform/core/src/services/StudyPrefetcherService/StudyPrefetcherService.ts
Sometimes, when switching hanging protocols, the `activeViewport` can be undefined.
This caused errors because the code assumed that an active viewport would always be present.
Added a guard clause in `_syncWithActiveViewport` to safely handle case where:
- `activeViewport` is undefined.
- Ensures prefetching logic only runs when a valid `viewport` exists.
Changing hanging protocols could throw errors when no active viewport was set.
The app now gracefully skips syncing when there is no active viewport.
etc.)
> Safely handle missing active viewport
